// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/imageLibrary/imageLibrary.proto

package imageLibrary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageLibraryService_UploadImage_FullMethodName = "/image_library.ImageLibraryService/UploadImage"
	ImageLibraryService_EditImage_FullMethodName   = "/image_library.ImageLibraryService/EditImage"
	ImageLibraryService_DeleteImage_FullMethodName = "/image_library.ImageLibraryService/DeleteImage"
	ImageLibraryService_ListImages_FullMethodName  = "/image_library.ImageLibraryService/ListImages"
)

// ImageLibraryServiceClient is the client API for ImageLibraryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `ImageLibraryService` handles all operations related to managing images for tables.
type ImageLibraryServiceClient interface {
	// Uploads an image using a client-side stream to handle large files efficiently.
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageRequest, UploadImageResponse], error)
	// Edits the metadata of an existing image (e.g., its name).
	EditImage(ctx context.Context, in *EditImageRequest, opts ...grpc.CallOption) (*Image, error)
	// Deletes an image from the library.
	DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Lists all images associated with a specific table using pagination.
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
}

type imageLibraryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageLibraryServiceClient(cc grpc.ClientConnInterface) ImageLibraryServiceClient {
	return &imageLibraryServiceClient{cc}
}

func (c *imageLibraryServiceClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadImageRequest, UploadImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageLibraryService_ServiceDesc.Streams[0], ImageLibraryService_UploadImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadImageRequest, UploadImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageLibraryService_UploadImageClient = grpc.ClientStreamingClient[UploadImageRequest, UploadImageResponse]

func (c *imageLibraryServiceClient) EditImage(ctx context.Context, in *EditImageRequest, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, ImageLibraryService_EditImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageLibraryServiceClient) DeleteImage(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ImageLibraryService_DeleteImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageLibraryServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, ImageLibraryService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageLibraryServiceServer is the server API for ImageLibraryService service.
// All implementations must embed UnimplementedImageLibraryServiceServer
// for forward compatibility.
//
// The `ImageLibraryService` handles all operations related to managing images for tables.
type ImageLibraryServiceServer interface {
	// Uploads an image using a client-side stream to handle large files efficiently.
	UploadImage(grpc.ClientStreamingServer[UploadImageRequest, UploadImageResponse]) error
	// Edits the metadata of an existing image (e.g., its name).
	EditImage(context.Context, *EditImageRequest) (*Image, error)
	// Deletes an image from the library.
	DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error)
	// Lists all images associated with a specific table using pagination.
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	mustEmbedUnimplementedImageLibraryServiceServer()
}

// UnimplementedImageLibraryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageLibraryServiceServer struct{}

func (UnimplementedImageLibraryServiceServer) UploadImage(grpc.ClientStreamingServer[UploadImageRequest, UploadImageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImageLibraryServiceServer) EditImage(context.Context, *EditImageRequest) (*Image, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditImage not implemented")
}
func (UnimplementedImageLibraryServiceServer) DeleteImage(context.Context, *DeleteImageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteImage not implemented")
}
func (UnimplementedImageLibraryServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedImageLibraryServiceServer) mustEmbedUnimplementedImageLibraryServiceServer() {}
func (UnimplementedImageLibraryServiceServer) testEmbeddedByValue()                             {}

// UnsafeImageLibraryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageLibraryServiceServer will
// result in compilation errors.
type UnsafeImageLibraryServiceServer interface {
	mustEmbedUnimplementedImageLibraryServiceServer()
}

func RegisterImageLibraryServiceServer(s grpc.ServiceRegistrar, srv ImageLibraryServiceServer) {
	// If the following call pancis, it indicates UnimplementedImageLibraryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageLibraryService_ServiceDesc, srv)
}

func _ImageLibraryService_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageLibraryServiceServer).UploadImage(&grpc.GenericServerStream[UploadImageRequest, UploadImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageLibraryService_UploadImageServer = grpc.ClientStreamingServer[UploadImageRequest, UploadImageResponse]

func _ImageLibraryService_EditImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageLibraryServiceServer).EditImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageLibraryService_EditImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageLibraryServiceServer).EditImage(ctx, req.(*EditImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageLibraryService_DeleteImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageLibraryServiceServer).DeleteImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageLibraryService_DeleteImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageLibraryServiceServer).DeleteImage(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageLibraryService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageLibraryServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageLibraryService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageLibraryServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageLibraryService_ServiceDesc is the grpc.ServiceDesc for ImageLibraryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageLibraryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "image_library.ImageLibraryService",
	HandlerType: (*ImageLibraryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EditImage",
			Handler:    _ImageLibraryService_EditImage_Handler,
		},
		{
			MethodName: "DeleteImage",
			Handler:    _ImageLibraryService_DeleteImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _ImageLibraryService_ListImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadImage",
			Handler:       _ImageLibraryService_UploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pb/imageLibrary/imageLibrary.proto",
}
