// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/character/service.proto

package character

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CharacterService_CreateCharacter_FullMethodName = "/character.CharacterService/CreateCharacter"
	CharacterService_GetCharacter_FullMethodName    = "/character.CharacterService/GetCharacter"
	CharacterService_ListCharacter_FullMethodName   = "/character.CharacterService/ListCharacter"
	CharacterService_SubscribeSheet_FullMethodName  = "/character.CharacterService/SubscribeSheet"
	CharacterService_UpdateSheet_FullMethodName     = "/character.CharacterService/UpdateSheet"
	CharacterService_DeleteSheet_FullMethodName     = "/character.CharacterService/DeleteSheet"
)

// CharacterServiceClient is the client API for CharacterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CharacterServiceClient interface {
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error)
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterResponse, error)
	ListCharacter(ctx context.Context, in *ListCharacterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCharacterResponse], error)
	SubscribeSheet(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SheetUpdate, SheetUpdate], error)
	UpdateSheet(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CharacterUpdateRequest, CharacterUpdateResponse], error)
	DeleteSheet(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error)
}

type characterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharacterServiceClient(cc grpc.ClientConnInterface) CharacterServiceClient {
	return &characterServiceClient{cc}
}

func (c *characterServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCharacterResponse)
	err := c.cc.Invoke(ctx, CharacterService_CreateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*GetCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCharacterResponse)
	err := c.cc.Invoke(ctx, CharacterService_GetCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *characterServiceClient) ListCharacter(ctx context.Context, in *ListCharacterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetCharacterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CharacterService_ServiceDesc.Streams[0], CharacterService_ListCharacter_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListCharacterRequest, GetCharacterResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_ListCharacterClient = grpc.ServerStreamingClient[GetCharacterResponse]

func (c *characterServiceClient) SubscribeSheet(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SheetUpdate, SheetUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CharacterService_ServiceDesc.Streams[1], CharacterService_SubscribeSheet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SheetUpdate, SheetUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_SubscribeSheetClient = grpc.BidiStreamingClient[SheetUpdate, SheetUpdate]

func (c *characterServiceClient) UpdateSheet(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CharacterUpdateRequest, CharacterUpdateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CharacterService_ServiceDesc.Streams[2], CharacterService_UpdateSheet_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CharacterUpdateRequest, CharacterUpdateResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_UpdateSheetClient = grpc.BidiStreamingClient[CharacterUpdateRequest, CharacterUpdateResponse]

func (c *characterServiceClient) DeleteSheet(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCharacterResponse)
	err := c.cc.Invoke(ctx, CharacterService_DeleteSheet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharacterServiceServer is the server API for CharacterService service.
// All implementations must embed UnimplementedCharacterServiceServer
// for forward compatibility.
type CharacterServiceServer interface {
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error)
	GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterResponse, error)
	ListCharacter(*ListCharacterRequest, grpc.ServerStreamingServer[GetCharacterResponse]) error
	SubscribeSheet(grpc.BidiStreamingServer[SheetUpdate, SheetUpdate]) error
	UpdateSheet(grpc.BidiStreamingServer[CharacterUpdateRequest, CharacterUpdateResponse]) error
	DeleteSheet(context.Context, *GetCharacterRequest) (*DeleteCharacterResponse, error)
	mustEmbedUnimplementedCharacterServiceServer()
}

// UnimplementedCharacterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCharacterServiceServer struct{}

func (UnimplementedCharacterServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedCharacterServiceServer) GetCharacter(context.Context, *GetCharacterRequest) (*GetCharacterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCharacter not implemented")
}
func (UnimplementedCharacterServiceServer) ListCharacter(*ListCharacterRequest, grpc.ServerStreamingServer[GetCharacterResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListCharacter not implemented")
}
func (UnimplementedCharacterServiceServer) SubscribeSheet(grpc.BidiStreamingServer[SheetUpdate, SheetUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSheet not implemented")
}
func (UnimplementedCharacterServiceServer) UpdateSheet(grpc.BidiStreamingServer[CharacterUpdateRequest, CharacterUpdateResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateSheet not implemented")
}
func (UnimplementedCharacterServiceServer) DeleteSheet(context.Context, *GetCharacterRequest) (*DeleteCharacterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSheet not implemented")
}
func (UnimplementedCharacterServiceServer) mustEmbedUnimplementedCharacterServiceServer() {}
func (UnimplementedCharacterServiceServer) testEmbeddedByValue()                          {}

// UnsafeCharacterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharacterServiceServer will
// result in compilation errors.
type UnsafeCharacterServiceServer interface {
	mustEmbedUnimplementedCharacterServiceServer()
}

func RegisterCharacterServiceServer(s grpc.ServiceRegistrar, srv CharacterServiceServer) {
	// If the following call pancis, it indicates UnimplementedCharacterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CharacterService_ServiceDesc, srv)
}

func _CharacterService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_GetCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CharacterService_ListCharacter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCharacterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CharacterServiceServer).ListCharacter(m, &grpc.GenericServerStream[ListCharacterRequest, GetCharacterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_ListCharacterServer = grpc.ServerStreamingServer[GetCharacterResponse]

func _CharacterService_SubscribeSheet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CharacterServiceServer).SubscribeSheet(&grpc.GenericServerStream[SheetUpdate, SheetUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_SubscribeSheetServer = grpc.BidiStreamingServer[SheetUpdate, SheetUpdate]

func _CharacterService_UpdateSheet_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CharacterServiceServer).UpdateSheet(&grpc.GenericServerStream[CharacterUpdateRequest, CharacterUpdateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CharacterService_UpdateSheetServer = grpc.BidiStreamingServer[CharacterUpdateRequest, CharacterUpdateResponse]

func _CharacterService_DeleteSheet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterServiceServer).DeleteSheet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterService_DeleteSheet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterServiceServer).DeleteSheet(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CharacterService_ServiceDesc is the grpc.ServiceDesc for CharacterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharacterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "character.CharacterService",
	HandlerType: (*CharacterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCharacter",
			Handler:    _CharacterService_CreateCharacter_Handler,
		},
		{
			MethodName: "GetCharacter",
			Handler:    _CharacterService_GetCharacter_Handler,
		},
		{
			MethodName: "DeleteSheet",
			Handler:    _CharacterService_DeleteSheet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCharacter",
			Handler:       _CharacterService_ListCharacter_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSheet",
			Handler:       _CharacterService_SubscribeSheet_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateSheet",
			Handler:       _CharacterService_UpdateSheet_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/character/service.proto",
}
