// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/character/service.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCharacterRequest_SystemKey int32

const (
	CreateCharacterRequest_NONE       CreateCharacterRequest_SystemKey = 0
	CreateCharacterRequest_TORMENTA20 CreateCharacterRequest_SystemKey = 1
	CreateCharacterRequest_DeD5e      CreateCharacterRequest_SystemKey = 2
	CreateCharacterRequest_GURPS      CreateCharacterRequest_SystemKey = 3
)

// Enum value maps for CreateCharacterRequest_SystemKey.
var (
	CreateCharacterRequest_SystemKey_name = map[int32]string{
		0: "NONE",
		1: "TORMENTA20",
		2: "DeD5e",
		3: "GURPS",
	}
	CreateCharacterRequest_SystemKey_value = map[string]int32{
		"NONE":       0,
		"TORMENTA20": 1,
		"DeD5e":      2,
		"GURPS":      3,
	}
)

func (x CreateCharacterRequest_SystemKey) Enum() *CreateCharacterRequest_SystemKey {
	p := new(CreateCharacterRequest_SystemKey)
	*p = x
	return p
}

func (x CreateCharacterRequest_SystemKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateCharacterRequest_SystemKey) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_character_service_proto_enumTypes[0].Descriptor()
}

func (CreateCharacterRequest_SystemKey) Type() protoreflect.EnumType {
	return &file_pb_character_service_proto_enumTypes[0]
}

func (x CreateCharacterRequest_SystemKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateCharacterRequest_SystemKey.Descriptor instead.
func (CreateCharacterRequest_SystemKey) EnumDescriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{10, 0}
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	TableId       uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_pb_character_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCharacterRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *GetCharacterRequest) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

type ListCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharacterRequest) Reset() {
	*x = ListCharacterRequest{}
	mi := &file_pb_character_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharacterRequest) ProtoMessage() {}

func (x *ListCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharacterRequest.ProtoReflect.Descriptor instead.
func (*ListCharacterRequest) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCharacterRequest) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sheet         *Sheet                 `protobuf:"bytes,1,opt,name=sheet,proto3" json:"sheet,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_pb_character_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharacterResponse) GetSheet() *Sheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *GetCharacterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCharacterResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// Wrapper to abilities
type AbilityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abilities     []*Ability             `protobuf:"bytes,1,rep,name=abilities,proto3" json:"abilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbilityList) Reset() {
	*x = AbilityList{}
	mi := &file_pb_character_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbilityList) ProtoMessage() {}

func (x *AbilityList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbilityList.ProtoReflect.Descriptor instead.
func (*AbilityList) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{3}
}

func (x *AbilityList) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

// Wrapper to Attack
type AttackList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attacks       []*Attack              `protobuf:"bytes,1,rep,name=attacks,proto3" json:"attacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackList) Reset() {
	*x = AttackList{}
	mi := &file_pb_character_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackList) ProtoMessage() {}

func (x *AttackList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackList.ProtoReflect.Descriptor instead.
func (*AttackList) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{4}
}

func (x *AttackList) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

// Wrapper to EquipamentItems
type EquipmentItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipmentItem []*EquipmentItem       `protobuf:"bytes,1,rep,name=equipment_item,json=equipmentItem,proto3" json:"equipment_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentItemList) Reset() {
	*x = EquipmentItemList{}
	mi := &file_pb_character_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentItemList) ProtoMessage() {}

func (x *EquipmentItemList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentItemList.ProtoReflect.Descriptor instead.
func (*EquipmentItemList) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{5}
}

func (x *EquipmentItemList) GetEquipmentItem() []*EquipmentItem {
	if x != nil {
		return x.EquipmentItem
	}
	return nil
}

type CharacterUpdateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CharacterId          uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	TableId              uint32                 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	CharacterName        string                 `protobuf:"bytes,3,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	Sheet                *Sheet                 `protobuf:"bytes,4,opt,name=sheet,proto3" json:"sheet,omitempty"`
	ExpectedLastModfield *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=expected_last_modfield,json=expectedLastModfield,proto3" json:"expected_last_modfield,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CharacterUpdateRequest) Reset() {
	*x = CharacterUpdateRequest{}
	mi := &file_pb_character_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterUpdateRequest) ProtoMessage() {}

func (x *CharacterUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterUpdateRequest.ProtoReflect.Descriptor instead.
func (*CharacterUpdateRequest) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterUpdateRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *CharacterUpdateRequest) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CharacterUpdateRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CharacterUpdateRequest) GetSheet() *Sheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *CharacterUpdateRequest) GetExpectedLastModfield() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpectedLastModfield
	}
	return nil
}

type CharacterUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=characterName,proto3" json:"characterName,omitempty"`
	Sheet         *Sheet                 `protobuf:"bytes,3,opt,name=sheet,proto3" json:"sheet,omitempty"`
	LastModfield  *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=last_modfield,json=lastModfield,proto3" json:"last_modfield,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterUpdateResponse) Reset() {
	*x = CharacterUpdateResponse{}
	mi := &file_pb_character_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterUpdateResponse) ProtoMessage() {}

func (x *CharacterUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterUpdateResponse.ProtoReflect.Descriptor instead.
func (*CharacterUpdateResponse) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterUpdateResponse) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CharacterUpdateResponse) GetSheet() *Sheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *CharacterUpdateResponse) GetLastModfield() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModfield
	}
	return nil
}

type SheetUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CharacterID          uint32                 `protobuf:"varint,1,opt,name=characterID,proto3" json:"characterID,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sheet                *Sheet                 `protobuf:"bytes,13,opt,name=sheet,proto3" json:"sheet,omitempty"`
	ExpectedLastModified *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=expected_last_modified,json=expectedLastModified,proto3" json:"expected_last_modified,omitempty"`
	// Types that are valid to be assigned to UpdateAction:
	//
	//	*SheetUpdate_NewAttributes
	//	*SheetUpdate_NewAbilities
	//	*SheetUpdate_NewArmor
	//	*SheetUpdate_NewAttacks
	//	*SheetUpdate_NewItems
	//	*SheetUpdate_NewClassAndLevel
	//	*SheetUpdate_NewHpPoints
	//	*SheetUpdate_NewManaPoints
	//	*SheetUpdate_NewCharacterInfo
	UpdateAction  isSheetUpdate_UpdateAction `protobuf_oneof:"updateAction"`
	Skills        map[string]*Skill          `protobuf:"bytes,14,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SheetUpdate) Reset() {
	*x = SheetUpdate{}
	mi := &file_pb_character_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetUpdate) ProtoMessage() {}

func (x *SheetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetUpdate.ProtoReflect.Descriptor instead.
func (*SheetUpdate) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{8}
}

func (x *SheetUpdate) GetCharacterID() uint32 {
	if x != nil {
		return x.CharacterID
	}
	return 0
}

func (x *SheetUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SheetUpdate) GetSheet() *Sheet {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *SheetUpdate) GetExpectedLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpectedLastModified
	}
	return nil
}

func (x *SheetUpdate) GetUpdateAction() isSheetUpdate_UpdateAction {
	if x != nil {
		return x.UpdateAction
	}
	return nil
}

func (x *SheetUpdate) GetNewAttributes() *Attributes {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewAttributes); ok {
			return x.NewAttributes
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewAbilities() *AbilityList {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewAbilities); ok {
			return x.NewAbilities
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewArmor() *Armor {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewArmor); ok {
			return x.NewArmor
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewAttacks() *AttackList {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewAttacks); ok {
			return x.NewAttacks
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewItems() *EquipmentItemList {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewItems); ok {
			return x.NewItems
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewClassAndLevel() *ClassAndLevel {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewClassAndLevel); ok {
			return x.NewClassAndLevel
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewHpPoints() *HpPoints {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewHpPoints); ok {
			return x.NewHpPoints
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewManaPoints() *ManaPoints {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewManaPoints); ok {
			return x.NewManaPoints
		}
	}
	return nil
}

func (x *SheetUpdate) GetNewCharacterInfo() *CharacterInfo {
	if x != nil {
		if x, ok := x.UpdateAction.(*SheetUpdate_NewCharacterInfo); ok {
			return x.NewCharacterInfo
		}
	}
	return nil
}

func (x *SheetUpdate) GetSkills() map[string]*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type isSheetUpdate_UpdateAction interface {
	isSheetUpdate_UpdateAction()
}

type SheetUpdate_NewAttributes struct {
	NewAttributes *Attributes `protobuf:"bytes,3,opt,name=new_attributes,json=newAttributes,proto3,oneof"`
}

type SheetUpdate_NewAbilities struct {
	NewAbilities *AbilityList `protobuf:"bytes,4,opt,name=new_abilities,json=newAbilities,proto3,oneof"`
}

type SheetUpdate_NewArmor struct {
	NewArmor *Armor `protobuf:"bytes,5,opt,name=new_armor,json=newArmor,proto3,oneof"`
}

type SheetUpdate_NewAttacks struct {
	NewAttacks *AttackList `protobuf:"bytes,6,opt,name=new_attacks,json=newAttacks,proto3,oneof"`
}

type SheetUpdate_NewItems struct {
	NewItems *EquipmentItemList `protobuf:"bytes,7,opt,name=new_items,json=newItems,proto3,oneof"`
}

type SheetUpdate_NewClassAndLevel struct {
	NewClassAndLevel *ClassAndLevel `protobuf:"bytes,8,opt,name=new_class_and_level,json=newClassAndLevel,proto3,oneof"`
}

type SheetUpdate_NewHpPoints struct {
	NewHpPoints *HpPoints `protobuf:"bytes,9,opt,name=new_hp_points,json=newHpPoints,proto3,oneof"`
}

type SheetUpdate_NewManaPoints struct {
	NewManaPoints *ManaPoints `protobuf:"bytes,10,opt,name=new_mana_points,json=newManaPoints,proto3,oneof"`
}

type SheetUpdate_NewCharacterInfo struct {
	NewCharacterInfo *CharacterInfo `protobuf:"bytes,11,opt,name=new_character_info,json=newCharacterInfo,proto3,oneof"`
}

func (*SheetUpdate_NewAttributes) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewAbilities) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewArmor) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewAttacks) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewItems) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewClassAndLevel) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewHpPoints) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewManaPoints) isSheetUpdate_UpdateAction() {}

func (*SheetUpdate_NewCharacterInfo) isSheetUpdate_UpdateAction() {}

type UpdateSheetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSheetResponse) Reset() {
	*x = UpdateSheetResponse{}
	mi := &file_pb_character_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSheetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSheetResponse) ProtoMessage() {}

func (x *UpdateSheetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSheetResponse.ProtoReflect.Descriptor instead.
func (*UpdateSheetResponse) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSheetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSheetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateCharacterRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TableUserId uint32                 `protobuf:"varint,1,opt,name=table_user_id,json=tableUserId,proto3" json:"table_user_id,omitempty"`
	// uint32 table_User = 2;
	PlayerName    string                           `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	CharacterName string                           `protobuf:"bytes,4,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	SystemKey     CreateCharacterRequest_SystemKey `protobuf:"varint,5,opt,name=system_key,json=systemKey,proto3,enum=character.CreateCharacterRequest_SystemKey" json:"system_key,omitempty"` // Sheet sheet_data = 6;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_pb_character_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCharacterRequest) GetTableUserId() uint32 {
	if x != nil {
		return x.TableUserId
	}
	return 0
}

func (x *CreateCharacterRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *CreateCharacterRequest) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CreateCharacterRequest) GetSystemKey() CreateCharacterRequest_SystemKey {
	if x != nil {
		return x.SystemKey
	}
	return CreateCharacterRequest_NONE
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	SheetData     *Sheet                 `protobuf:"bytes,3,opt,name=sheet_data,json=sheetData,proto3" json:"sheet_data,omitempty"`
	SystemKey     string                 `protobuf:"bytes,4,opt,name=system_key,json=systemKey,proto3" json:"system_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_pb_character_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateCharacterResponse) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *CreateCharacterResponse) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *CreateCharacterResponse) GetSheetData() *Sheet {
	if x != nil {
		return x.SheetData
	}
	return nil
}

func (x *CreateCharacterResponse) GetSystemKey() string {
	if x != nil {
		return x.SystemKey
	}
	return ""
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageStatus string                 `protobuf:"bytes,1,opt,name=message_status,json=messageStatus,proto3" json:"message_status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_pb_character_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_pb_character_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCharacterResponse) GetMessageStatus() string {
	if x != nil {
		return x.MessageStatus
	}
	return ""
}

func (x *DeleteCharacterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_character_service_proto protoreflect.FileDescriptor

const file_pb_character_service_proto_rawDesc = "" +
	"\n" +
	"\x1apb/character/service.proto\x12\tcharacter\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18pb/character/sheet.proto\"S\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\"1\n" +
	"\x14ListCharacterRequest\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\"\x8d\x01\n" +
	"\x14GetCharacterResponse\x12&\n" +
	"\x05sheet\x18\x01 \x01(\v2\x10.character.SheetR\x05sheet\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"?\n" +
	"\vAbilityList\x120\n" +
	"\tabilities\x18\x01 \x03(\v2\x12.character.AbilityR\tabilities\"9\n" +
	"\n" +
	"AttackList\x12+\n" +
	"\aattacks\x18\x01 \x03(\v2\x11.character.AttackR\aattacks\"T\n" +
	"\x11EquipmentItemList\x12?\n" +
	"\x0eequipment_item\x18\x01 \x03(\v2\x18.character.EquipmentItemR\requipmentItem\"\xf7\x01\n" +
	"\x16CharacterUpdateRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\rR\atableId\x12%\n" +
	"\x0echaracter_name\x18\x03 \x01(\tR\rcharacterName\x12&\n" +
	"\x05sheet\x18\x04 \x01(\v2\x10.character.SheetR\x05sheet\x12P\n" +
	"\x16expected_last_modfield\x18d \x01(\v2\x1a.google.protobuf.TimestampR\x14expectedLastModfield\"\xa8\x01\n" +
	"\x17CharacterUpdateResponse\x12$\n" +
	"\rcharacterName\x18\x02 \x01(\tR\rcharacterName\x12&\n" +
	"\x05sheet\x18\x03 \x01(\v2\x10.character.SheetR\x05sheet\x12?\n" +
	"\rlast_modfield\x18d \x01(\v2\x1a.google.protobuf.TimestampR\flastModfield\"\x8e\a\n" +
	"\vSheetUpdate\x12 \n" +
	"\vcharacterID\x18\x01 \x01(\rR\vcharacterID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x05sheet\x18\r \x01(\v2\x10.character.SheetR\x05sheet\x12P\n" +
	"\x16expected_last_modified\x18d \x01(\v2\x1a.google.protobuf.TimestampR\x14expectedLastModified\x12>\n" +
	"\x0enew_attributes\x18\x03 \x01(\v2\x15.character.AttributesH\x00R\rnewAttributes\x12=\n" +
	"\rnew_abilities\x18\x04 \x01(\v2\x16.character.AbilityListH\x00R\fnewAbilities\x12/\n" +
	"\tnew_armor\x18\x05 \x01(\v2\x10.character.ArmorH\x00R\bnewArmor\x128\n" +
	"\vnew_attacks\x18\x06 \x01(\v2\x15.character.AttackListH\x00R\n" +
	"newAttacks\x12;\n" +
	"\tnew_items\x18\a \x01(\v2\x1c.character.EquipmentItemListH\x00R\bnewItems\x12I\n" +
	"\x13new_class_and_level\x18\b \x01(\v2\x18.character.ClassAndLevelH\x00R\x10newClassAndLevel\x129\n" +
	"\rnew_hp_points\x18\t \x01(\v2\x13.character.HpPointsH\x00R\vnewHpPoints\x12?\n" +
	"\x0fnew_mana_points\x18\n" +
	" \x01(\v2\x15.character.ManaPointsH\x00R\rnewManaPoints\x12H\n" +
	"\x12new_character_info\x18\v \x01(\v2\x18.character.CharacterInfoH\x00R\x10newCharacterInfo\x12:\n" +
	"\x06skills\x18\x0e \x03(\v2\".character.SheetUpdate.SkillsEntryR\x06skills\x1aK\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.character.SkillR\x05value:\x028\x01B\x0e\n" +
	"\fupdateAction\"I\n" +
	"\x13UpdateSheetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8d\x02\n" +
	"\x16CreateCharacterRequest\x12\"\n" +
	"\rtable_user_id\x18\x01 \x01(\rR\vtableUserId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12%\n" +
	"\x0echaracter_name\x18\x04 \x01(\tR\rcharacterName\x12J\n" +
	"\n" +
	"system_key\x18\x05 \x01(\x0e2+.character.CreateCharacterRequest.SystemKeyR\tsystemKey\";\n" +
	"\tSystemKey\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"TORMENTA20\x10\x01\x12\t\n" +
	"\x05DeD5e\x10\x02\x12\t\n" +
	"\x05GURPS\x10\x03\"\xb1\x01\n" +
	"\x17CreateCharacterResponse\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12/\n" +
	"\n" +
	"sheet_data\x18\x03 \x01(\v2\x10.character.SheetR\tsheetData\x12\x1d\n" +
	"\n" +
	"system_key\x18\x04 \x01(\tR\tsystemKey\"Z\n" +
	"\x17DeleteCharacterResponse\x12%\n" +
	"\x0emessage_status\x18\x01 \x01(\tR\rmessageStatus\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x85\x04\n" +
	"\x10CharacterService\x12X\n" +
	"\x0fCreateCharacter\x12!.character.CreateCharacterRequest\x1a\".character.CreateCharacterResponse\x12O\n" +
	"\fGetCharacter\x12\x1e.character.GetCharacterRequest\x1a\x1f.character.GetCharacterResponse\x12S\n" +
	"\rListCharacter\x12\x1f.character.ListCharacterRequest\x1a\x1f.character.GetCharacterResponse0\x01\x12D\n" +
	"\x0eSubscribeSheet\x12\x16.character.SheetUpdate\x1a\x16.character.SheetUpdate(\x010\x01\x12X\n" +
	"\vUpdateSheet\x12!.character.CharacterUpdateRequest\x1a\".character.CharacterUpdateResponse(\x010\x01\x12Q\n" +
	"\vDeleteSheet\x12\x1e.character.GetCharacterRequest\x1a\".character.DeleteCharacterResponseBDZBgithub.com/GarotoCowboy/vttProject/api/grpc/pb/character;characterb\x06proto3"

var (
	file_pb_character_service_proto_rawDescOnce sync.Once
	file_pb_character_service_proto_rawDescData []byte
)

func file_pb_character_service_proto_rawDescGZIP() []byte {
	file_pb_character_service_proto_rawDescOnce.Do(func() {
		file_pb_character_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_character_service_proto_rawDesc), len(file_pb_character_service_proto_rawDesc)))
	})
	return file_pb_character_service_proto_rawDescData
}

var file_pb_character_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_character_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_character_service_proto_goTypes = []any{
	(CreateCharacterRequest_SystemKey)(0), // 0: character.CreateCharacterRequest.SystemKey
	(*GetCharacterRequest)(nil),           // 1: character.GetCharacterRequest
	(*ListCharacterRequest)(nil),          // 2: character.ListCharacterRequest
	(*GetCharacterResponse)(nil),          // 3: character.GetCharacterResponse
	(*AbilityList)(nil),                   // 4: character.AbilityList
	(*AttackList)(nil),                    // 5: character.AttackList
	(*EquipmentItemList)(nil),             // 6: character.EquipmentItemList
	(*CharacterUpdateRequest)(nil),        // 7: character.CharacterUpdateRequest
	(*CharacterUpdateResponse)(nil),       // 8: character.CharacterUpdateResponse
	(*SheetUpdate)(nil),                   // 9: character.SheetUpdate
	(*UpdateSheetResponse)(nil),           // 10: character.UpdateSheetResponse
	(*CreateCharacterRequest)(nil),        // 11: character.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),       // 12: character.CreateCharacterResponse
	(*DeleteCharacterResponse)(nil),       // 13: character.DeleteCharacterResponse
	nil,                                   // 14: character.SheetUpdate.SkillsEntry
	(*Sheet)(nil),                         // 15: character.Sheet
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
	(*Ability)(nil),                       // 17: character.Ability
	(*Attack)(nil),                        // 18: character.Attack
	(*EquipmentItem)(nil),                 // 19: character.EquipmentItem
	(*Attributes)(nil),                    // 20: character.Attributes
	(*Armor)(nil),                         // 21: character.Armor
	(*ClassAndLevel)(nil),                 // 22: character.ClassAndLevel
	(*HpPoints)(nil),                      // 23: character.HpPoints
	(*ManaPoints)(nil),                    // 24: character.ManaPoints
	(*CharacterInfo)(nil),                 // 25: character.CharacterInfo
	(*Skill)(nil),                         // 26: character.Skill
}
var file_pb_character_service_proto_depIdxs = []int32{
	15, // 0: character.GetCharacterResponse.sheet:type_name -> character.Sheet
	16, // 1: character.GetCharacterResponse.deleted_at:type_name -> google.protobuf.Timestamp
	17, // 2: character.AbilityList.abilities:type_name -> character.Ability
	18, // 3: character.AttackList.attacks:type_name -> character.Attack
	19, // 4: character.EquipmentItemList.equipment_item:type_name -> character.EquipmentItem
	15, // 5: character.CharacterUpdateRequest.sheet:type_name -> character.Sheet
	16, // 6: character.CharacterUpdateRequest.expected_last_modfield:type_name -> google.protobuf.Timestamp
	15, // 7: character.CharacterUpdateResponse.sheet:type_name -> character.Sheet
	16, // 8: character.CharacterUpdateResponse.last_modfield:type_name -> google.protobuf.Timestamp
	15, // 9: character.SheetUpdate.sheet:type_name -> character.Sheet
	16, // 10: character.SheetUpdate.expected_last_modified:type_name -> google.protobuf.Timestamp
	20, // 11: character.SheetUpdate.new_attributes:type_name -> character.Attributes
	4,  // 12: character.SheetUpdate.new_abilities:type_name -> character.AbilityList
	21, // 13: character.SheetUpdate.new_armor:type_name -> character.Armor
	5,  // 14: character.SheetUpdate.new_attacks:type_name -> character.AttackList
	6,  // 15: character.SheetUpdate.new_items:type_name -> character.EquipmentItemList
	22, // 16: character.SheetUpdate.new_class_and_level:type_name -> character.ClassAndLevel
	23, // 17: character.SheetUpdate.new_hp_points:type_name -> character.HpPoints
	24, // 18: character.SheetUpdate.new_mana_points:type_name -> character.ManaPoints
	25, // 19: character.SheetUpdate.new_character_info:type_name -> character.CharacterInfo
	14, // 20: character.SheetUpdate.skills:type_name -> character.SheetUpdate.SkillsEntry
	0,  // 21: character.CreateCharacterRequest.system_key:type_name -> character.CreateCharacterRequest.SystemKey
	15, // 22: character.CreateCharacterResponse.sheet_data:type_name -> character.Sheet
	26, // 23: character.SheetUpdate.SkillsEntry.value:type_name -> character.Skill
	11, // 24: character.CharacterService.CreateCharacter:input_type -> character.CreateCharacterRequest
	1,  // 25: character.CharacterService.GetCharacter:input_type -> character.GetCharacterRequest
	2,  // 26: character.CharacterService.ListCharacter:input_type -> character.ListCharacterRequest
	9,  // 27: character.CharacterService.SubscribeSheet:input_type -> character.SheetUpdate
	7,  // 28: character.CharacterService.UpdateSheet:input_type -> character.CharacterUpdateRequest
	1,  // 29: character.CharacterService.DeleteSheet:input_type -> character.GetCharacterRequest
	12, // 30: character.CharacterService.CreateCharacter:output_type -> character.CreateCharacterResponse
	3,  // 31: character.CharacterService.GetCharacter:output_type -> character.GetCharacterResponse
	3,  // 32: character.CharacterService.ListCharacter:output_type -> character.GetCharacterResponse
	9,  // 33: character.CharacterService.SubscribeSheet:output_type -> character.SheetUpdate
	8,  // 34: character.CharacterService.UpdateSheet:output_type -> character.CharacterUpdateResponse
	13, // 35: character.CharacterService.DeleteSheet:output_type -> character.DeleteCharacterResponse
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pb_character_service_proto_init() }
func file_pb_character_service_proto_init() {
	if File_pb_character_service_proto != nil {
		return
	}
	file_pb_character_sheet_proto_init()
	file_pb_character_service_proto_msgTypes[8].OneofWrappers = []any{
		(*SheetUpdate_NewAttributes)(nil),
		(*SheetUpdate_NewAbilities)(nil),
		(*SheetUpdate_NewArmor)(nil),
		(*SheetUpdate_NewAttacks)(nil),
		(*SheetUpdate_NewItems)(nil),
		(*SheetUpdate_NewClassAndLevel)(nil),
		(*SheetUpdate_NewHpPoints)(nil),
		(*SheetUpdate_NewManaPoints)(nil),
		(*SheetUpdate_NewCharacterInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_character_service_proto_rawDesc), len(file_pb_character_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_character_service_proto_goTypes,
		DependencyIndexes: file_pb_character_service_proto_depIdxs,
		EnumInfos:         file_pb_character_service_proto_enumTypes,
		MessageInfos:      file_pb_character_service_proto_msgTypes,
	}.Build()
	File_pb_character_service_proto = out.File
	file_pb_character_service_proto_goTypes = nil
	file_pb_character_service_proto_depIdxs = nil
}
