// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/character/sheet.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create a character sheet to use GRPC
type Sheet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Attributes     *Attributes            `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Abilities      []*Ability             `protobuf:"bytes,2,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Armor          *Armor                 `protobuf:"bytes,3,opt,name=armor,proto3" json:"armor,omitempty"`
	Attacks        []*Attack              `protobuf:"bytes,4,rep,name=attacks,proto3" json:"attacks,omitempty"`
	EquipmentItems []*EquipmentItem       `protobuf:"bytes,5,rep,name=equipment_items,json=equipmentItems,proto3" json:"equipment_items,omitempty"`
	ClassAndLevel  *ClassAndLevel         `protobuf:"bytes,6,opt,name=class_and_level,json=classAndLevel,proto3" json:"class_and_level,omitempty"`
	HpPoints       *HpPoints              `protobuf:"bytes,7,opt,name=hp_points,json=hpPoints,proto3" json:"hp_points,omitempty"`
	ManaPoints     *ManaPoints            `protobuf:"bytes,8,opt,name=mana_points,json=manaPoints,proto3" json:"mana_points,omitempty"`
	CharacterInfo  *CharacterInfo         `protobuf:"bytes,9,opt,name=character_info,json=characterInfo,proto3" json:"character_info,omitempty"`
	Skills         map[string]*Skill      `protobuf:"bytes,10,rep,name=skills,proto3" json:"skills,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastModified   *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sheet) Reset() {
	*x = Sheet{}
	mi := &file_pb_character_sheet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sheet) ProtoMessage() {}

func (x *Sheet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sheet.ProtoReflect.Descriptor instead.
func (*Sheet) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{0}
}

func (x *Sheet) GetAttributes() *Attributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Sheet) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *Sheet) GetArmor() *Armor {
	if x != nil {
		return x.Armor
	}
	return nil
}

func (x *Sheet) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *Sheet) GetEquipmentItems() []*EquipmentItem {
	if x != nil {
		return x.EquipmentItems
	}
	return nil
}

func (x *Sheet) GetClassAndLevel() *ClassAndLevel {
	if x != nil {
		return x.ClassAndLevel
	}
	return nil
}

func (x *Sheet) GetHpPoints() *HpPoints {
	if x != nil {
		return x.HpPoints
	}
	return nil
}

func (x *Sheet) GetManaPoints() *ManaPoints {
	if x != nil {
		return x.ManaPoints
	}
	return nil
}

func (x *Sheet) GetCharacterInfo() *CharacterInfo {
	if x != nil {
		return x.CharacterInfo
	}
	return nil
}

func (x *Sheet) GetSkills() map[string]*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Sheet) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

type Attributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,2,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Constitution  int32                  `protobuf:"varint,3,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Intelligence  int32                  `protobuf:"varint,4,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,5,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Charisma      int32                  `protobuf:"varint,6,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attributes) Reset() {
	*x = Attributes{}
	mi := &file_pb_character_sheet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attributes) ProtoMessage() {}

func (x *Attributes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attributes.ProtoReflect.Descriptor instead.
func (*Attributes) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{1}
}

func (x *Attributes) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Attributes) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *Attributes) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *Attributes) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Attributes) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *Attributes) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

type Skill struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DefaultBaseAttribute string                 `protobuf:"bytes,1,opt,name=default_base_attribute,json=defaultBaseAttribute,proto3" json:"default_base_attribute,omitempty"`
	CurrentBaseAttribute string                 `protobuf:"bytes,2,opt,name=current_base_attribute,json=currentBaseAttribute,proto3" json:"current_base_attribute,omitempty"`
	Trained              bool                   `protobuf:"varint,3,opt,name=trained,proto3" json:"trained,omitempty"`
	Bonus                int32                  `protobuf:"varint,4,opt,name=bonus,proto3" json:"bonus,omitempty"`
	OnlyTrained          bool                   `protobuf:"varint,5,opt,name=only_trained,json=onlyTrained,proto3" json:"only_trained,omitempty"`
	ArmorPenalty         bool                   `protobuf:"varint,6,opt,name=armor_penalty,json=armorPenalty,proto3" json:"armor_penalty,omitempty"`
	OtherBonus           int32                  `protobuf:"varint,7,opt,name=other_bonus,json=otherBonus,proto3" json:"other_bonus,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_pb_character_sheet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{2}
}

func (x *Skill) GetDefaultBaseAttribute() string {
	if x != nil {
		return x.DefaultBaseAttribute
	}
	return ""
}

func (x *Skill) GetCurrentBaseAttribute() string {
	if x != nil {
		return x.CurrentBaseAttribute
	}
	return ""
}

func (x *Skill) GetTrained() bool {
	if x != nil {
		return x.Trained
	}
	return false
}

func (x *Skill) GetBonus() int32 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *Skill) GetOnlyTrained() bool {
	if x != nil {
		return x.OnlyTrained
	}
	return false
}

func (x *Skill) GetArmorPenalty() bool {
	if x != nil {
		return x.ArmorPenalty
	}
	return false
}

func (x *Skill) GetOtherBonus() int32 {
	if x != nil {
		return x.OtherBonus
	}
	return 0
}

type Ability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_pb_character_sheet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{3}
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ManaPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actual        int32                  `protobuf:"varint,1,opt,name=actual,proto3" json:"actual,omitempty"`
	MaxMana       int32                  `protobuf:"varint,2,opt,name=max_mana,json=maxMana,proto3" json:"max_mana,omitempty"`
	TempMana      int32                  `protobuf:"varint,3,opt,name=temp_mana,json=tempMana,proto3" json:"temp_mana,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManaPoints) Reset() {
	*x = ManaPoints{}
	mi := &file_pb_character_sheet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManaPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManaPoints) ProtoMessage() {}

func (x *ManaPoints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManaPoints.ProtoReflect.Descriptor instead.
func (*ManaPoints) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{4}
}

func (x *ManaPoints) GetActual() int32 {
	if x != nil {
		return x.Actual
	}
	return 0
}

func (x *ManaPoints) GetMaxMana() int32 {
	if x != nil {
		return x.MaxMana
	}
	return 0
}

func (x *ManaPoints) GetTempMana() int32 {
	if x != nil {
		return x.TempMana
	}
	return 0
}

type HpPoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actual        int32                  `protobuf:"varint,1,opt,name=actual,proto3" json:"actual,omitempty"`
	MaxHp         int32                  `protobuf:"varint,2,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	TempHp        int32                  `protobuf:"varint,3,opt,name=temp_hp,json=tempHp,proto3" json:"temp_hp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HpPoints) Reset() {
	*x = HpPoints{}
	mi := &file_pb_character_sheet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HpPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HpPoints) ProtoMessage() {}

func (x *HpPoints) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HpPoints.ProtoReflect.Descriptor instead.
func (*HpPoints) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{5}
}

func (x *HpPoints) GetActual() int32 {
	if x != nil {
		return x.Actual
	}
	return 0
}

func (x *HpPoints) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *HpPoints) GetTempHp() int32 {
	if x != nil {
		return x.TempHp
	}
	return 0
}

type EquipmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Weight        float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipmentItem) Reset() {
	*x = EquipmentItem{}
	mi := &file_pb_character_sheet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentItem) ProtoMessage() {}

func (x *EquipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentItem.ProtoReflect.Descriptor instead.
func (*EquipmentItem) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{6}
}

func (x *EquipmentItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *EquipmentItem) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ClassAndLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassAndLevel) Reset() {
	*x = ClassAndLevel{}
	mi := &file_pb_character_sheet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassAndLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassAndLevel) ProtoMessage() {}

func (x *ClassAndLevel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassAndLevel.ProtoReflect.Descriptor instead.
func (*ClassAndLevel) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{7}
}

func (x *ClassAndLevel) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *ClassAndLevel) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Attack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AttackTest    string                 `protobuf:"bytes,2,opt,name=attack_test,json=attackTest,proto3" json:"attack_test,omitempty"`
	Damage        string                 `protobuf:"bytes,3,opt,name=damage,proto3" json:"damage,omitempty"`
	Critical      string                 `protobuf:"bytes,4,opt,name=critical,proto3" json:"critical,omitempty"`
	DamageType    string                 `protobuf:"bytes,5,opt,name=damage_type,json=damageType,proto3" json:"damage_type,omitempty"`
	Range         string                 `protobuf:"bytes,6,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attack) Reset() {
	*x = Attack{}
	mi := &file_pb_character_sheet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attack) ProtoMessage() {}

func (x *Attack) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attack.ProtoReflect.Descriptor instead.
func (*Attack) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{8}
}

func (x *Attack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Attack) GetAttackTest() string {
	if x != nil {
		return x.AttackTest
	}
	return ""
}

func (x *Attack) GetDamage() string {
	if x != nil {
		return x.Damage
	}
	return ""
}

func (x *Attack) GetCritical() string {
	if x != nil {
		return x.Critical
	}
	return ""
}

func (x *Attack) GetDamageType() string {
	if x != nil {
		return x.DamageType
	}
	return ""
}

func (x *Attack) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

type CharacterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deity         string                 `protobuf:"bytes,1,opt,name=deity,proto3" json:"deity,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Race          string                 `protobuf:"bytes,4,opt,name=race,proto3" json:"race,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInfo) Reset() {
	*x = CharacterInfo{}
	mi := &file_pb_character_sheet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInfo) ProtoMessage() {}

func (x *CharacterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInfo.ProtoReflect.Descriptor instead.
func (*CharacterInfo) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{9}
}

func (x *CharacterInfo) GetDeity() string {
	if x != nil {
		return x.Deity
	}
	return ""
}

func (x *CharacterInfo) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CharacterInfo) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CharacterInfo) GetRace() string {
	if x != nil {
		return x.Race
	}
	return ""
}

type Armor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Defense        int32                  `protobuf:"varint,1,opt,name=defense,proto3" json:"defense,omitempty"`
	DexterityBonus bool                   `protobuf:"varint,2,opt,name=dexterity_bonus,json=dexterityBonus,proto3" json:"dexterity_bonus,omitempty"`
	ArmorBonus     int32                  `protobuf:"varint,3,opt,name=armor_bonus,json=armorBonus,proto3" json:"armor_bonus,omitempty"`
	ShieldBonus    int32                  `protobuf:"varint,4,opt,name=shield_bonus,json=shieldBonus,proto3" json:"shield_bonus,omitempty"`
	OtherBonus     int32                  `protobuf:"varint,5,opt,name=other_bonus,json=otherBonus,proto3" json:"other_bonus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Armor) Reset() {
	*x = Armor{}
	mi := &file_pb_character_sheet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Armor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Armor) ProtoMessage() {}

func (x *Armor) ProtoReflect() protoreflect.Message {
	mi := &file_pb_character_sheet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Armor.ProtoReflect.Descriptor instead.
func (*Armor) Descriptor() ([]byte, []int) {
	return file_pb_character_sheet_proto_rawDescGZIP(), []int{10}
}

func (x *Armor) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *Armor) GetDexterityBonus() bool {
	if x != nil {
		return x.DexterityBonus
	}
	return false
}

func (x *Armor) GetArmorBonus() int32 {
	if x != nil {
		return x.ArmorBonus
	}
	return 0
}

func (x *Armor) GetShieldBonus() int32 {
	if x != nil {
		return x.ShieldBonus
	}
	return 0
}

func (x *Armor) GetOtherBonus() int32 {
	if x != nil {
		return x.OtherBonus
	}
	return 0
}

var File_pb_character_sheet_proto protoreflect.FileDescriptor

const file_pb_character_sheet_proto_rawDesc = "" +
	"\n" +
	"\x18pb/character/sheet.proto\x12\tcharacter\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x05\n" +
	"\x05Sheet\x125\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x15.character.AttributesR\n" +
	"attributes\x120\n" +
	"\tabilities\x18\x02 \x03(\v2\x12.character.AbilityR\tabilities\x12&\n" +
	"\x05armor\x18\x03 \x01(\v2\x10.character.ArmorR\x05armor\x12+\n" +
	"\aattacks\x18\x04 \x03(\v2\x11.character.AttackR\aattacks\x12A\n" +
	"\x0fequipment_items\x18\x05 \x03(\v2\x18.character.EquipmentItemR\x0eequipmentItems\x12@\n" +
	"\x0fclass_and_level\x18\x06 \x01(\v2\x18.character.ClassAndLevelR\rclassAndLevel\x120\n" +
	"\thp_points\x18\a \x01(\v2\x13.character.HpPointsR\bhpPoints\x126\n" +
	"\vmana_points\x18\b \x01(\v2\x15.character.ManaPointsR\n" +
	"manaPoints\x12?\n" +
	"\x0echaracter_info\x18\t \x01(\v2\x18.character.CharacterInfoR\rcharacterInfo\x124\n" +
	"\x06skills\x18\n" +
	" \x03(\v2\x1c.character.Sheet.SkillsEntryR\x06skills\x12?\n" +
	"\rlast_modified\x18d \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x1aK\n" +
	"\vSkillsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.character.SkillR\x05value:\x028\x01\"\xc2\x01\n" +
	"\n" +
	"Attributes\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\x02 \x01(\x05R\tdexterity\x12\"\n" +
	"\fconstitution\x18\x03 \x01(\x05R\fconstitution\x12\"\n" +
	"\fintelligence\x18\x04 \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\x05 \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bcharisma\x18\x06 \x01(\x05R\bcharisma\"\x8c\x02\n" +
	"\x05Skill\x124\n" +
	"\x16default_base_attribute\x18\x01 \x01(\tR\x14defaultBaseAttribute\x124\n" +
	"\x16current_base_attribute\x18\x02 \x01(\tR\x14currentBaseAttribute\x12\x18\n" +
	"\atrained\x18\x03 \x01(\bR\atrained\x12\x14\n" +
	"\x05bonus\x18\x04 \x01(\x05R\x05bonus\x12!\n" +
	"\fonly_trained\x18\x05 \x01(\bR\vonlyTrained\x12#\n" +
	"\rarmor_penalty\x18\x06 \x01(\bR\farmorPenalty\x12\x1f\n" +
	"\vother_bonus\x18\a \x01(\x05R\n" +
	"otherBonus\"?\n" +
	"\aAbility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\\\n" +
	"\n" +
	"ManaPoints\x12\x16\n" +
	"\x06actual\x18\x01 \x01(\x05R\x06actual\x12\x19\n" +
	"\bmax_mana\x18\x02 \x01(\x05R\amaxMana\x12\x1b\n" +
	"\ttemp_mana\x18\x03 \x01(\x05R\btempMana\"R\n" +
	"\bHpPoints\x12\x16\n" +
	"\x06actual\x18\x01 \x01(\x05R\x06actual\x12\x15\n" +
	"\x06max_hp\x18\x02 \x01(\x05R\x05maxHp\x12\x17\n" +
	"\atemp_hp\x18\x03 \x01(\x05R\x06tempHp\"S\n" +
	"\rEquipmentItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x02R\x06weight\";\n" +
	"\rClassAndLevel\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xa8\x01\n" +
	"\x06Attack\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vattack_test\x18\x02 \x01(\tR\n" +
	"attackTest\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\tR\x06damage\x12\x1a\n" +
	"\bcritical\x18\x04 \x01(\tR\bcritical\x12\x1f\n" +
	"\vdamage_type\x18\x05 \x01(\tR\n" +
	"damageType\x12\x14\n" +
	"\x05range\x18\x06 \x01(\tR\x05range\"g\n" +
	"\rCharacterInfo\x12\x14\n" +
	"\x05deity\x18\x01 \x01(\tR\x05deity\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x12\n" +
	"\x04race\x18\x04 \x01(\tR\x04race\"\xaf\x01\n" +
	"\x05Armor\x12\x18\n" +
	"\adefense\x18\x01 \x01(\x05R\adefense\x12'\n" +
	"\x0fdexterity_bonus\x18\x02 \x01(\bR\x0edexterityBonus\x12\x1f\n" +
	"\varmor_bonus\x18\x03 \x01(\x05R\n" +
	"armorBonus\x12!\n" +
	"\fshield_bonus\x18\x04 \x01(\x05R\vshieldBonus\x12\x1f\n" +
	"\vother_bonus\x18\x05 \x01(\x05R\n" +
	"otherBonusBDZBgithub.com/GarotoCowboy/vttProject/api/grpc/pb/character;characterb\x06proto3"

var (
	file_pb_character_sheet_proto_rawDescOnce sync.Once
	file_pb_character_sheet_proto_rawDescData []byte
)

func file_pb_character_sheet_proto_rawDescGZIP() []byte {
	file_pb_character_sheet_proto_rawDescOnce.Do(func() {
		file_pb_character_sheet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_character_sheet_proto_rawDesc), len(file_pb_character_sheet_proto_rawDesc)))
	})
	return file_pb_character_sheet_proto_rawDescData
}

var file_pb_character_sheet_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_character_sheet_proto_goTypes = []any{
	(*Sheet)(nil),                 // 0: character.Sheet
	(*Attributes)(nil),            // 1: character.Attributes
	(*Skill)(nil),                 // 2: character.Skill
	(*Ability)(nil),               // 3: character.Ability
	(*ManaPoints)(nil),            // 4: character.ManaPoints
	(*HpPoints)(nil),              // 5: character.HpPoints
	(*EquipmentItem)(nil),         // 6: character.EquipmentItem
	(*ClassAndLevel)(nil),         // 7: character.ClassAndLevel
	(*Attack)(nil),                // 8: character.Attack
	(*CharacterInfo)(nil),         // 9: character.CharacterInfo
	(*Armor)(nil),                 // 10: character.Armor
	nil,                           // 11: character.Sheet.SkillsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_pb_character_sheet_proto_depIdxs = []int32{
	1,  // 0: character.Sheet.attributes:type_name -> character.Attributes
	3,  // 1: character.Sheet.abilities:type_name -> character.Ability
	10, // 2: character.Sheet.armor:type_name -> character.Armor
	8,  // 3: character.Sheet.attacks:type_name -> character.Attack
	6,  // 4: character.Sheet.equipment_items:type_name -> character.EquipmentItem
	7,  // 5: character.Sheet.class_and_level:type_name -> character.ClassAndLevel
	5,  // 6: character.Sheet.hp_points:type_name -> character.HpPoints
	4,  // 7: character.Sheet.mana_points:type_name -> character.ManaPoints
	9,  // 8: character.Sheet.character_info:type_name -> character.CharacterInfo
	11, // 9: character.Sheet.skills:type_name -> character.Sheet.SkillsEntry
	12, // 10: character.Sheet.last_modified:type_name -> google.protobuf.Timestamp
	2,  // 11: character.Sheet.SkillsEntry.value:type_name -> character.Skill
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pb_character_sheet_proto_init() }
func file_pb_character_sheet_proto_init() {
	if File_pb_character_sheet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_character_sheet_proto_rawDesc), len(file_pb_character_sheet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_character_sheet_proto_goTypes,
		DependencyIndexes: file_pb_character_sheet_proto_depIdxs,
		MessageInfos:      file_pb_character_sheet_proto_msgTypes,
	}.Build()
	File_pb_character_sheet_proto = out.File
	file_pb_character_sheet_proto_goTypes = nil
	file_pb_character_sheet_proto_depIdxs = nil
}
