// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/placedImage/placedImage.proto

package placedImage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LayerType int32

const (
	// The default layer, visible to players and the GM.
	LayerType_PLAYER_LAYER LayerType = 0
	// The layer for map elements, typically below the player layer.
	LayerType_MAP_LAYER LayerType = 1
	// A layer only visible to the Game Master (GM).
	LayerType_MASTER_LAYER LayerType = 2
)

// Enum value maps for LayerType.
var (
	LayerType_name = map[int32]string{
		0: "PLAYER_LAYER",
		1: "MAP_LAYER",
		2: "MASTER_LAYER",
	}
	LayerType_value = map[string]int32{
		"PLAYER_LAYER": 0,
		"MAP_LAYER":    1,
		"MASTER_LAYER": 2,
	}
)

func (x LayerType) Enum() *LayerType {
	p := new(LayerType)
	*p = x
	return p
}

func (x LayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_placedImage_placedImage_proto_enumTypes[0].Descriptor()
}

func (LayerType) Type() protoreflect.EnumType {
	return &file_pb_placedImage_placedImage_proto_enumTypes[0]
}

func (x LayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerType.Descriptor instead.
func (LayerType) EnumDescriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{0}
}

type PlacedImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       uint64                 `protobuf:"varint,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	SceneId       uint64                 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PlacedImageId uint64                 `protobuf:"varint,3,opt,name=placed_image_id,json=placedImageId,proto3" json:"placed_image_id,omitempty"`
	PosX          int32                  `protobuf:"varint,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          int32                  `protobuf:"varint,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Rotation      int32                  `protobuf:"varint,6,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Width         uint64                 `protobuf:"varint,7,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint64                 `protobuf:"varint,8,opt,name=height,proto3" json:"height,omitempty"`
	Layer         LayerType              `protobuf:"varint,9,opt,name=layer,proto3,enum=placedImage.LayerType" json:"layer,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedImage) Reset() {
	*x = PlacedImage{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedImage) ProtoMessage() {}

func (x *PlacedImage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedImage.ProtoReflect.Descriptor instead.
func (*PlacedImage) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{0}
}

func (x *PlacedImage) GetImageId() uint64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *PlacedImage) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedImage) GetPlacedImageId() uint64 {
	if x != nil {
		return x.PlacedImageId
	}
	return 0
}

func (x *PlacedImage) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlacedImage) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlacedImage) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlacedImage) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *PlacedImage) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *PlacedImage) GetLayer() LayerType {
	if x != nil {
		return x.Layer
	}
	return LayerType_PLAYER_LAYER
}

func (x *PlacedImage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlacedImage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePlacedImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene to place the image on.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the image template to use.
	ImageId uint64 `protobuf:"varint,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// The initial X-coordinate for the image.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The initial Y-coordinate for the image.
	PosY          int32  `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Width         uint64 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint64 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlacedImageRequest) Reset() {
	*x = CreatePlacedImageRequest{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlacedImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlacedImageRequest) ProtoMessage() {}

func (x *CreatePlacedImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlacedImageRequest.ProtoReflect.Descriptor instead.
func (*CreatePlacedImageRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlacedImageRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CreatePlacedImageRequest) GetImageId() uint64 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *CreatePlacedImageRequest) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CreatePlacedImageRequest) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *CreatePlacedImageRequest) GetWidth() uint64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreatePlacedImageRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CreatePlacedImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlacedImage   *PlacedImage           `protobuf:"bytes,1,opt,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlacedImageResponse) Reset() {
	*x = CreatePlacedImageResponse{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlacedImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlacedImageResponse) ProtoMessage() {}

func (x *CreatePlacedImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlacedImageResponse.ProtoReflect.Descriptor instead.
func (*CreatePlacedImageResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlacedImageResponse) GetPlacedImage() *PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

type EditPlacedImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlacedImage   *PlacedImage           `protobuf:"bytes,1,opt,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlacedImageRequest) Reset() {
	*x = EditPlacedImageRequest{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlacedImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlacedImageRequest) ProtoMessage() {}

func (x *EditPlacedImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlacedImageRequest.ProtoReflect.Descriptor instead.
func (*EditPlacedImageRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{3}
}

func (x *EditPlacedImageRequest) GetPlacedImage() *PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

func (x *EditPlacedImageRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

type EditPlacedImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlacedImage   *PlacedImage           `protobuf:"bytes,1,opt,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlacedImageResponse) Reset() {
	*x = EditPlacedImageResponse{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlacedImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlacedImageResponse) ProtoMessage() {}

func (x *EditPlacedImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlacedImageResponse.ProtoReflect.Descriptor instead.
func (*EditPlacedImageResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{4}
}

func (x *EditPlacedImageResponse) GetPlacedImage() *PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

type DeletePlacedImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the image instance to delete.
	PlacedImageId uint64 `protobuf:"varint,1,opt,name=placed_image_id,json=placedImageId,proto3" json:"placed_image_id,omitempty"`
	// The ID of the scene the image belongs to, for validation.
	SceneId       uint64 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlacedImageRequest) Reset() {
	*x = DeletePlacedImageRequest{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlacedImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlacedImageRequest) ProtoMessage() {}

func (x *DeletePlacedImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlacedImageRequest.ProtoReflect.Descriptor instead.
func (*DeletePlacedImageRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePlacedImageRequest) GetPlacedImageId() uint64 {
	if x != nil {
		return x.PlacedImageId
	}
	return 0
}

func (x *DeletePlacedImageRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type ListAllImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SceneId       uint64                 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllImagesRequest) Reset() {
	*x = ListAllImagesRequest{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllImagesRequest) ProtoMessage() {}

func (x *ListAllImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllImagesRequest.ProtoReflect.Descriptor instead.
func (*ListAllImagesRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{6}
}

func (x *ListAllImagesRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

type ListAllImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlacedImage   []*PlacedImage         `protobuf:"bytes,1,rep,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllImagesResponse) Reset() {
	*x = ListAllImagesResponse{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllImagesResponse) ProtoMessage() {}

func (x *ListAllImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllImagesResponse.ProtoReflect.Descriptor instead.
func (*ListAllImagesResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllImagesResponse) GetPlacedImage() []*PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

type MoveImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene where the move is happening.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the image instance being moved.
	PlacedImageId uint64 `protobuf:"varint,2,opt,name=placed_image_id,json=placedImageId,proto3" json:"placed_image_id,omitempty"`
	// The new X-coordinate.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The new Y-coordinate.
	PosY          int32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveImageRequest) Reset() {
	*x = MoveImageRequest{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveImageRequest) ProtoMessage() {}

func (x *MoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveImageRequest.ProtoReflect.Descriptor instead.
func (*MoveImageRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{8}
}

func (x *MoveImageRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *MoveImageRequest) GetPlacedImageId() uint64 {
	if x != nil {
		return x.PlacedImageId
	}
	return 0
}

func (x *MoveImageRequest) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *MoveImageRequest) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

type MoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveImageResponse) Reset() {
	*x = MoveImageResponse{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveImageResponse) ProtoMessage() {}

func (x *MoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveImageResponse.ProtoReflect.Descriptor instead.
func (*MoveImageResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{9}
}

func (x *MoveImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Event triggered when a new image is placed on a scene.
type PlacedImageCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created image instance.
	PlacedImage   *PlacedImage `protobuf:"bytes,1,opt,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedImageCreated) Reset() {
	*x = PlacedImageCreated{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedImageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedImageCreated) ProtoMessage() {}

func (x *PlacedImageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedImageCreated.ProtoReflect.Descriptor instead.
func (*PlacedImageCreated) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{10}
}

func (x *PlacedImageCreated) GetPlacedImage() *PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

// Event triggered when a placed image's properties are updated.
type PlacedImageUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token instance with its updated data.
	PlacedImage   *PlacedImage `protobuf:"bytes,1,opt,name=placed_image,json=placedImage,proto3" json:"placed_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedImageUpdated) Reset() {
	*x = PlacedImageUpdated{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedImageUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedImageUpdated) ProtoMessage() {}

func (x *PlacedImageUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedImageUpdated.ProtoReflect.Descriptor instead.
func (*PlacedImageUpdated) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{11}
}

func (x *PlacedImageUpdated) GetPlacedImage() *PlacedImage {
	if x != nil {
		return x.PlacedImage
	}
	return nil
}

// Event triggered when a image is deleted from a scene.
type PlacedImageDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene from which the image was deleted.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the image instance that was deleted.
	PlacedImageId uint64 `protobuf:"varint,2,opt,name=placed_image_id,json=placedImageId,proto3" json:"placed_image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedImageDeleted) Reset() {
	*x = PlacedImageDeleted{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedImageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedImageDeleted) ProtoMessage() {}

func (x *PlacedImageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedImageDeleted.ProtoReflect.Descriptor instead.
func (*PlacedImageDeleted) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{12}
}

func (x *PlacedImageDeleted) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedImageDeleted) GetPlacedImageId() uint64 {
	if x != nil {
		return x.PlacedImageId
	}
	return 0
}

// Event triggered when a image is moved.
type PlacedImageMoved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene where the image moved.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the image instance that moved.
	PlacedImageId uint64 `protobuf:"varint,2,opt,name=placed_image_id,json=placedImageId,proto3" json:"placed_image_id,omitempty"`
	// The new X-coordinate of the image.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The new Y-coordinate of the image.
	PosY          int32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedImageMoved) Reset() {
	*x = PlacedImageMoved{}
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedImageMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedImageMoved) ProtoMessage() {}

func (x *PlacedImageMoved) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedImage_placedImage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedImageMoved.ProtoReflect.Descriptor instead.
func (*PlacedImageMoved) Descriptor() ([]byte, []int) {
	return file_pb_placedImage_placedImage_proto_rawDescGZIP(), []int{13}
}

func (x *PlacedImageMoved) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedImageMoved) GetPlacedImageId() uint64 {
	if x != nil {
		return x.PlacedImageId
	}
	return 0
}

func (x *PlacedImageMoved) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlacedImageMoved) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

var File_pb_placedImage_placedImage_proto protoreflect.FileDescriptor

const file_pb_placedImage_placedImage_proto_rawDesc = "" +
	"\n" +
	" pb/placedImage/placedImage.proto\x12\vplacedImage\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x03\n" +
	"\vPlacedImage\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\x04R\aimageId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_image_id\x18\x03 \x01(\x04R\rplacedImageId\x12\x13\n" +
	"\x05pos_x\x18\x04 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x05 \x01(\x05R\x04posY\x12\x1a\n" +
	"\brotation\x18\x06 \x01(\x05R\brotation\x12\x14\n" +
	"\x05width\x18\a \x01(\x04R\x05width\x12\x16\n" +
	"\x06height\x18\b \x01(\x04R\x06height\x12,\n" +
	"\x05layer\x18\t \x01(\x0e2\x16.placedImage.LayerTypeR\x05layer\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa8\x01\n" +
	"\x18CreatePlacedImageRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\x04R\aimageId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x04R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x04R\x06height\"X\n" +
	"\x19CreatePlacedImageResponse\x12;\n" +
	"\fplaced_image\x18\x01 \x01(\v2\x18.placedImage.PlacedImageR\vplacedImage\"\x85\x01\n" +
	"\x16EditPlacedImageRequest\x12;\n" +
	"\fplaced_image\x18\x01 \x01(\v2\x18.placedImage.PlacedImageR\vplacedImage\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"V\n" +
	"\x17EditPlacedImageResponse\x12;\n" +
	"\fplaced_image\x18\x01 \x01(\v2\x18.placedImage.PlacedImageR\vplacedImage\"]\n" +
	"\x18DeletePlacedImageRequest\x12&\n" +
	"\x0fplaced_image_id\x18\x01 \x01(\x04R\rplacedImageId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x04R\asceneId\"1\n" +
	"\x14ListAllImagesRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\"T\n" +
	"\x15ListAllImagesResponse\x12;\n" +
	"\fplaced_image\x18\x01 \x03(\v2\x18.placedImage.PlacedImageR\vplacedImage\"\x7f\n" +
	"\x10MoveImageRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_image_id\x18\x02 \x01(\x04R\rplacedImageId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY\"-\n" +
	"\x11MoveImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x12PlacedImageCreated\x12;\n" +
	"\fplaced_image\x18\x01 \x01(\v2\x18.placedImage.PlacedImageR\vplacedImage\"Q\n" +
	"\x12PlacedImageUpdated\x12;\n" +
	"\fplaced_image\x18\x01 \x01(\v2\x18.placedImage.PlacedImageR\vplacedImage\"W\n" +
	"\x12PlacedImageDeleted\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_image_id\x18\x02 \x01(\x04R\rplacedImageId\"\x7f\n" +
	"\x10PlacedImageMoved\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_image_id\x18\x02 \x01(\x04R\rplacedImageId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY*>\n" +
	"\tLayerType\x12\x10\n" +
	"\fPLAYER_LAYER\x10\x00\x12\r\n" +
	"\tMAP_LAYER\x10\x01\x12\x10\n" +
	"\fMASTER_LAYER\x10\x022\xd5\x03\n" +
	"\x12PlacedImageService\x12b\n" +
	"\x11CreatePlacedImage\x12%.placedImage.CreatePlacedImageRequest\x1a&.placedImage.CreatePlacedImageResponse\x12\\\n" +
	"\x0fEditPlacedImage\x12#.placedImage.EditPlacedImageRequest\x1a$.placedImage.EditPlacedImageResponse\x12R\n" +
	"\x11DeletePlacedToken\x12%.placedImage.DeletePlacedImageRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x14ListAllImagesOnScene\x12!.placedImage.ListAllImagesRequest\x1a\".placedImage.ListAllImagesResponse\x12J\n" +
	"\tMoveImage\x12\x1d.placedImage.MoveImageRequest\x1a\x1e.placedImage.MoveImageResponseBHZFgithub.com/GarotoCowboy/vttProject/api/grpc/pb/placedImage;placedImageb\x06proto3"

var (
	file_pb_placedImage_placedImage_proto_rawDescOnce sync.Once
	file_pb_placedImage_placedImage_proto_rawDescData []byte
)

func file_pb_placedImage_placedImage_proto_rawDescGZIP() []byte {
	file_pb_placedImage_placedImage_proto_rawDescOnce.Do(func() {
		file_pb_placedImage_placedImage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_placedImage_placedImage_proto_rawDesc), len(file_pb_placedImage_placedImage_proto_rawDesc)))
	})
	return file_pb_placedImage_placedImage_proto_rawDescData
}

var file_pb_placedImage_placedImage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_placedImage_placedImage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_placedImage_placedImage_proto_goTypes = []any{
	(LayerType)(0),                    // 0: placedImage.LayerType
	(*PlacedImage)(nil),               // 1: placedImage.PlacedImage
	(*CreatePlacedImageRequest)(nil),  // 2: placedImage.CreatePlacedImageRequest
	(*CreatePlacedImageResponse)(nil), // 3: placedImage.CreatePlacedImageResponse
	(*EditPlacedImageRequest)(nil),    // 4: placedImage.EditPlacedImageRequest
	(*EditPlacedImageResponse)(nil),   // 5: placedImage.EditPlacedImageResponse
	(*DeletePlacedImageRequest)(nil),  // 6: placedImage.DeletePlacedImageRequest
	(*ListAllImagesRequest)(nil),      // 7: placedImage.ListAllImagesRequest
	(*ListAllImagesResponse)(nil),     // 8: placedImage.ListAllImagesResponse
	(*MoveImageRequest)(nil),          // 9: placedImage.MoveImageRequest
	(*MoveImageResponse)(nil),         // 10: placedImage.MoveImageResponse
	(*PlacedImageCreated)(nil),        // 11: placedImage.PlacedImageCreated
	(*PlacedImageUpdated)(nil),        // 12: placedImage.PlacedImageUpdated
	(*PlacedImageDeleted)(nil),        // 13: placedImage.PlacedImageDeleted
	(*PlacedImageMoved)(nil),          // 14: placedImage.PlacedImageMoved
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 16: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),             // 17: google.protobuf.Empty
}
var file_pb_placedImage_placedImage_proto_depIdxs = []int32{
	0,  // 0: placedImage.PlacedImage.layer:type_name -> placedImage.LayerType
	15, // 1: placedImage.PlacedImage.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: placedImage.PlacedImage.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: placedImage.CreatePlacedImageResponse.placed_image:type_name -> placedImage.PlacedImage
	1,  // 4: placedImage.EditPlacedImageRequest.placed_image:type_name -> placedImage.PlacedImage
	16, // 5: placedImage.EditPlacedImageRequest.mask:type_name -> google.protobuf.FieldMask
	1,  // 6: placedImage.EditPlacedImageResponse.placed_image:type_name -> placedImage.PlacedImage
	1,  // 7: placedImage.ListAllImagesResponse.placed_image:type_name -> placedImage.PlacedImage
	1,  // 8: placedImage.PlacedImageCreated.placed_image:type_name -> placedImage.PlacedImage
	1,  // 9: placedImage.PlacedImageUpdated.placed_image:type_name -> placedImage.PlacedImage
	2,  // 10: placedImage.PlacedImageService.CreatePlacedImage:input_type -> placedImage.CreatePlacedImageRequest
	4,  // 11: placedImage.PlacedImageService.EditPlacedImage:input_type -> placedImage.EditPlacedImageRequest
	6,  // 12: placedImage.PlacedImageService.DeletePlacedToken:input_type -> placedImage.DeletePlacedImageRequest
	7,  // 13: placedImage.PlacedImageService.ListAllImagesOnScene:input_type -> placedImage.ListAllImagesRequest
	9,  // 14: placedImage.PlacedImageService.MoveImage:input_type -> placedImage.MoveImageRequest
	3,  // 15: placedImage.PlacedImageService.CreatePlacedImage:output_type -> placedImage.CreatePlacedImageResponse
	5,  // 16: placedImage.PlacedImageService.EditPlacedImage:output_type -> placedImage.EditPlacedImageResponse
	17, // 17: placedImage.PlacedImageService.DeletePlacedToken:output_type -> google.protobuf.Empty
	8,  // 18: placedImage.PlacedImageService.ListAllImagesOnScene:output_type -> placedImage.ListAllImagesResponse
	10, // 19: placedImage.PlacedImageService.MoveImage:output_type -> placedImage.MoveImageResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_placedImage_placedImage_proto_init() }
func file_pb_placedImage_placedImage_proto_init() {
	if File_pb_placedImage_placedImage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_placedImage_placedImage_proto_rawDesc), len(file_pb_placedImage_placedImage_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_placedImage_placedImage_proto_goTypes,
		DependencyIndexes: file_pb_placedImage_placedImage_proto_depIdxs,
		EnumInfos:         file_pb_placedImage_placedImage_proto_enumTypes,
		MessageInfos:      file_pb_placedImage_placedImage_proto_msgTypes,
	}.Build()
	File_pb_placedImage_placedImage_proto = out.File
	file_pb_placedImage_placedImage_proto_goTypes = nil
	file_pb_placedImage_placedImage_proto_depIdxs = nil
}
