// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/placedImage/placedImage.proto

package placedImage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacedImageService_CreatePlacedImage_FullMethodName    = "/placedImage.PlacedImageService/CreatePlacedImage"
	PlacedImageService_EditPlacedImage_FullMethodName      = "/placedImage.PlacedImageService/EditPlacedImage"
	PlacedImageService_DeletePlacedToken_FullMethodName    = "/placedImage.PlacedImageService/DeletePlacedToken"
	PlacedImageService_ListAllImagesOnScene_FullMethodName = "/placedImage.PlacedImageService/ListAllImagesOnScene"
	PlacedImageService_MoveImage_FullMethodName            = "/placedImage.PlacedImageService/MoveImage"
)

// PlacedImageServiceClient is the client API for PlacedImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `PlacedImageService` manages image instances that are placed on a specific scene or map.
type PlacedImageServiceClient interface {
	// Creates a new image instance on a scene.
	CreatePlacedImage(ctx context.Context, in *CreatePlacedImageRequest, opts ...grpc.CallOption) (*CreatePlacedImageResponse, error)
	// Edits the properties of an existing placed token.
	EditPlacedImage(ctx context.Context, in *EditPlacedImageRequest, opts ...grpc.CallOption) (*EditPlacedImageResponse, error)
	// Deletes a image from a scene.
	DeletePlacedToken(ctx context.Context, in *DeletePlacedImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Lists all images currently on a specific scene.
	ListAllImagesOnScene(ctx context.Context, in *ListAllImagesRequest, opts ...grpc.CallOption) (*ListAllImagesResponse, error)
	// Moves a image to a new position on the scene.
	MoveImage(ctx context.Context, in *MoveImageRequest, opts ...grpc.CallOption) (*MoveImageResponse, error)
}

type placedImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacedImageServiceClient(cc grpc.ClientConnInterface) PlacedImageServiceClient {
	return &placedImageServiceClient{cc}
}

func (c *placedImageServiceClient) CreatePlacedImage(ctx context.Context, in *CreatePlacedImageRequest, opts ...grpc.CallOption) (*CreatePlacedImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlacedImageResponse)
	err := c.cc.Invoke(ctx, PlacedImageService_CreatePlacedImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedImageServiceClient) EditPlacedImage(ctx context.Context, in *EditPlacedImageRequest, opts ...grpc.CallOption) (*EditPlacedImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditPlacedImageResponse)
	err := c.cc.Invoke(ctx, PlacedImageService_EditPlacedImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedImageServiceClient) DeletePlacedToken(ctx context.Context, in *DeletePlacedImageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlacedImageService_DeletePlacedToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedImageServiceClient) ListAllImagesOnScene(ctx context.Context, in *ListAllImagesRequest, opts ...grpc.CallOption) (*ListAllImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllImagesResponse)
	err := c.cc.Invoke(ctx, PlacedImageService_ListAllImagesOnScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedImageServiceClient) MoveImage(ctx context.Context, in *MoveImageRequest, opts ...grpc.CallOption) (*MoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveImageResponse)
	err := c.cc.Invoke(ctx, PlacedImageService_MoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacedImageServiceServer is the server API for PlacedImageService service.
// All implementations must embed UnimplementedPlacedImageServiceServer
// for forward compatibility.
//
// The `PlacedImageService` manages image instances that are placed on a specific scene or map.
type PlacedImageServiceServer interface {
	// Creates a new image instance on a scene.
	CreatePlacedImage(context.Context, *CreatePlacedImageRequest) (*CreatePlacedImageResponse, error)
	// Edits the properties of an existing placed token.
	EditPlacedImage(context.Context, *EditPlacedImageRequest) (*EditPlacedImageResponse, error)
	// Deletes a image from a scene.
	DeletePlacedToken(context.Context, *DeletePlacedImageRequest) (*emptypb.Empty, error)
	// Lists all images currently on a specific scene.
	ListAllImagesOnScene(context.Context, *ListAllImagesRequest) (*ListAllImagesResponse, error)
	// Moves a image to a new position on the scene.
	MoveImage(context.Context, *MoveImageRequest) (*MoveImageResponse, error)
	mustEmbedUnimplementedPlacedImageServiceServer()
}

// UnimplementedPlacedImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacedImageServiceServer struct{}

func (UnimplementedPlacedImageServiceServer) CreatePlacedImage(context.Context, *CreatePlacedImageRequest) (*CreatePlacedImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlacedImage not implemented")
}
func (UnimplementedPlacedImageServiceServer) EditPlacedImage(context.Context, *EditPlacedImageRequest) (*EditPlacedImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPlacedImage not implemented")
}
func (UnimplementedPlacedImageServiceServer) DeletePlacedToken(context.Context, *DeletePlacedImageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlacedToken not implemented")
}
func (UnimplementedPlacedImageServiceServer) ListAllImagesOnScene(context.Context, *ListAllImagesRequest) (*ListAllImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllImagesOnScene not implemented")
}
func (UnimplementedPlacedImageServiceServer) MoveImage(context.Context, *MoveImageRequest) (*MoveImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveImage not implemented")
}
func (UnimplementedPlacedImageServiceServer) mustEmbedUnimplementedPlacedImageServiceServer() {}
func (UnimplementedPlacedImageServiceServer) testEmbeddedByValue()                            {}

// UnsafePlacedImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacedImageServiceServer will
// result in compilation errors.
type UnsafePlacedImageServiceServer interface {
	mustEmbedUnimplementedPlacedImageServiceServer()
}

func RegisterPlacedImageServiceServer(s grpc.ServiceRegistrar, srv PlacedImageServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlacedImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacedImageService_ServiceDesc, srv)
}

func _PlacedImageService_CreatePlacedImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlacedImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedImageServiceServer).CreatePlacedImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedImageService_CreatePlacedImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedImageServiceServer).CreatePlacedImage(ctx, req.(*CreatePlacedImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedImageService_EditPlacedImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPlacedImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedImageServiceServer).EditPlacedImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedImageService_EditPlacedImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedImageServiceServer).EditPlacedImage(ctx, req.(*EditPlacedImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedImageService_DeletePlacedToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlacedImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedImageServiceServer).DeletePlacedToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedImageService_DeletePlacedToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedImageServiceServer).DeletePlacedToken(ctx, req.(*DeletePlacedImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedImageService_ListAllImagesOnScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedImageServiceServer).ListAllImagesOnScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedImageService_ListAllImagesOnScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedImageServiceServer).ListAllImagesOnScene(ctx, req.(*ListAllImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedImageService_MoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedImageServiceServer).MoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedImageService_MoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedImageServiceServer).MoveImage(ctx, req.(*MoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacedImageService_ServiceDesc is the grpc.ServiceDesc for PlacedImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacedImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "placedImage.PlacedImageService",
	HandlerType: (*PlacedImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlacedImage",
			Handler:    _PlacedImageService_CreatePlacedImage_Handler,
		},
		{
			MethodName: "EditPlacedImage",
			Handler:    _PlacedImageService_EditPlacedImage_Handler,
		},
		{
			MethodName: "DeletePlacedToken",
			Handler:    _PlacedImageService_DeletePlacedToken_Handler,
		},
		{
			MethodName: "ListAllImagesOnScene",
			Handler:    _PlacedImageService_ListAllImagesOnScene_Handler,
		},
		{
			MethodName: "MoveImage",
			Handler:    _PlacedImageService_MoveImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/placedImage/placedImage.proto",
}
