// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/chat/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration of possible message content types.
type MessageType int32

const (
	MessageType_TEXT     MessageType = 0 // A plain text message.
	MessageType_IMAGE    MessageType = 1 // A message containing an image.
	MessageType_VIDEO    MessageType = 2 // A message containing a video.
	MessageType_AUDIO    MessageType = 3 // A message containing an audio clip.
	MessageType_DOCUMENT MessageType = 4 // A message containing a document or file.
	MessageType_SYSTEM   MessageType = 5 // A message generated by the system (e.g., "User has joined the room").
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "VIDEO",
		3: "AUDIO",
		4: "DOCUMENT",
		5: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":     0,
		"IMAGE":    1,
		"VIDEO":    2,
		"AUDIO":    3,
		"DOCUMENT": 4,
		"SYSTEM":   5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_chat_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pb_chat_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{0}
}

// Enumeration of message delivery statuses.
type MessageStatus int32

const (
	MessageStatus_SENT      MessageStatus = 0 // The message was sent by the client and received by the server.
	MessageStatus_DELIVERED MessageStatus = 1 // The message has been delivered to the recipient(s).
	MessageStatus_READ      MessageStatus = 2 // The message has been read by the recipient(s).
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "SENT",
		1: "DELIVERED",
		2: "READ",
	}
	MessageStatus_value = map[string]int32{
		"SENT":      0,
		"DELIVERED": 1,
		"READ":      2,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_chat_chat_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_pb_chat_chat_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{1}
}

// Request to list messages for a table.
type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the table (room) to list messages from.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// ID of the last message received from the previous page, used for cursor-based pagination.
	LastMessageId *string `protobuf:"bytes,2,opt,name=last_message_id,json=lastMessageId,proto3,oneof" json:"last_message_id,omitempty"`
	// The maximum number of messages to return per page.
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_pb_chat_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ListMessagesRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *ListMessagesRequest) GetLastMessageId() string {
	if x != nil && x.LastMessageId != nil {
		return *x.LastMessageId
	}
	return ""
}

func (x *ListMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Response containing the list of messages and pagination information.
type ListChatMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of retrieved messages.
	Messages []*ChatMessageResponse `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// The cursor to be used in the next request to get the following page.
	NextCursor    *string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMessageResponse) Reset() {
	*x = ListChatMessageResponse{}
	mi := &file_pb_chat_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMessageResponse) ProtoMessage() {}

func (x *ListChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ListChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ListChatMessageResponse) GetMessages() []*ChatMessageResponse {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListChatMessageResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

// Request to send a new message to a table.
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the table where the message will be sent.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// ID of the user sending the message.
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The text content of the message.
	MessageText *string `protobuf:"bytes,3,opt,name=message_text,json=messageText,proto3,oneof" json:"message_text,omitempty"`
	// The type of the message (TEXT, IMAGE, etc.).
	MessageType MessageType `protobuf:"varint,4,opt,name=messageType,proto3,enum=chat.MessageType" json:"messageType,omitempty"`
	// The initial status of the message (usually SENT).
	MessageStatus MessageStatus `protobuf:"varint,5,opt,name=messageStatus,proto3,enum=chat.MessageStatus" json:"messageStatus,omitempty"`
	// Timestamp of when the message was sent.
	SendAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	// UUID of the message to which this is a reply.
	ReplyToMessageId *string `protobuf:"bytes,7,opt,name=reply_to_message_id,json=replyToMessageId,proto3,oneof" json:"reply_to_message_id,omitempty"`
	// A list of URLs or identifiers for attachments.
	Attachments []string `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// The primary URL for media if the type is IMAGE, VIDEO, etc.
	MediaUrl      *string `protobuf:"bytes,9,opt,name=media_url,json=mediaUrl,proto3,oneof" json:"media_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pb_chat_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{2}
}

func (x *SendMessageRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *SendMessageRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendMessageRequest) GetMessageText() string {
	if x != nil && x.MessageText != nil {
		return *x.MessageText
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TEXT
}

func (x *SendMessageRequest) GetMessageStatus() MessageStatus {
	if x != nil {
		return x.MessageStatus
	}
	return MessageStatus_SENT
}

func (x *SendMessageRequest) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

func (x *SendMessageRequest) GetReplyToMessageId() string {
	if x != nil && x.ReplyToMessageId != nil {
		return *x.ReplyToMessageId
	}
	return ""
}

func (x *SendMessageRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendMessageRequest) GetMediaUrl() string {
	if x != nil && x.MediaUrl != nil {
		return *x.MediaUrl
	}
	return ""
}

// Represents a single chat message.
type ChatMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique UUID of the message.
	MessageUuid string `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	// ID of the table the message belongs to.
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// ID of the sender user.
	SenderId uint64 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Username of the sender.
	SenderUsername string `protobuf:"bytes,4,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"`
	// Text content of the message.
	MessageText string `protobuf:"bytes,5,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	// The type of the message.
	MessageType MessageType `protobuf:"varint,6,opt,name=message_type,json=messageType,proto3,enum=chat.MessageType" json:"message_type,omitempty"`
	// The status of the message (sent, delivered, read).
	MessageStatus MessageStatus `protobuf:"varint,7,opt,name=message_status,json=messageStatus,proto3,enum=chat.MessageStatus" json:"message_status,omitempty"`
	// The sent timestamp.
	SentAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// The primary media URL.
	MediaUrl *string `protobuf:"bytes,9,opt,name=media_url,json=mediaUrl,proto3,oneof" json:"media_url,omitempty"`
	// List of attachments.
	Attachments []string `protobuf:"bytes,10,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// UUID of the original message if this is a reply.
	ReplyToMessageId *string `protobuf:"bytes,11,opt,name=reply_to_message_id,json=replyToMessageId,proto3,oneof" json:"reply_to_message_id,omitempty"`
	// Flag indicating if the message has been deleted by the sender.
	IsDeleted bool `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// Timestamp of the last message update.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	// If this is a private message, this field contains the recipient's ID.
	PrivateRecipientId *uint64 `protobuf:"varint,14,opt,name=private_recipient_id,json=privateRecipientId,proto3,oneof" json:"private_recipient_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatMessageResponse) Reset() {
	*x = ChatMessageResponse{}
	mi := &file_pb_chat_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageResponse) ProtoMessage() {}

func (x *ChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessageResponse) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *ChatMessageResponse) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *ChatMessageResponse) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessageResponse) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *ChatMessageResponse) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *ChatMessageResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TEXT
}

func (x *ChatMessageResponse) GetMessageStatus() MessageStatus {
	if x != nil {
		return x.MessageStatus
	}
	return MessageStatus_SENT
}

func (x *ChatMessageResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ChatMessageResponse) GetMediaUrl() string {
	if x != nil && x.MediaUrl != nil {
		return *x.MediaUrl
	}
	return ""
}

func (x *ChatMessageResponse) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ChatMessageResponse) GetReplyToMessageId() string {
	if x != nil && x.ReplyToMessageId != nil {
		return *x.ReplyToMessageId
	}
	return ""
}

func (x *ChatMessageResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ChatMessageResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ChatMessageResponse) GetPrivateRecipientId() uint64 {
	if x != nil && x.PrivateRecipientId != nil {
		return *x.PrivateRecipientId
	}
	return 0
}

// Request to delete a message.
type DeleteMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user within the table (table_user_id) requesting the deletion.
	TableUserId uint64 `protobuf:"varint,1,opt,name=table_user_id,json=tableUserId,proto3" json:"table_user_id,omitempty"`
	// UUID of the message to be deleted.
	MessageUuid   string `protobuf:"bytes,2,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_pb_chat_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMessageRequest) GetTableUserId() uint64 {
	if x != nil {
		return x.TableUserId
	}
	return 0
}

func (x *DeleteMessageRequest) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

// Request to send a private message.
type SendPrivateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the sending user in the table.
	TableUserId uint64 `protobuf:"varint,1,opt,name=table_user_id,json=tableUserId,proto3" json:"table_user_id,omitempty"`
	// ID of the recipient user in the table.
	ToTableUserId uint64 `protobuf:"varint,2,opt,name=to_table_user_id,json=toTableUserId,proto3" json:"to_table_user_id,omitempty"`
	// Username of the sender.
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// Text content of the message.
	Message *string `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	// The unique UUID of the message.
	MessageUuid string `protobuf:"bytes,5,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	// The primary media URL, if any.
	MediaUrl *string `protobuf:"bytes,6,opt,name=media_url,json=mediaUrl,proto3,oneof" json:"media_url,omitempty"`
	// List of attachments.
	Attachments []string `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// The type of the message.
	MessageType MessageType `protobuf:"varint,8,opt,name=messageType,proto3,enum=chat.MessageType" json:"messageType,omitempty"`
	// The status of the message.
	MessageStatus MessageStatus `protobuf:"varint,9,opt,name=messageStatus,proto3,enum=chat.MessageStatus" json:"messageStatus,omitempty"`
	// The sent timestamp.
	SendAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	// UUID of the original message if this is a reply.
	ReplyToMessageId *string `protobuf:"bytes,11,opt,name=reply_to_message_id,json=replyToMessageId,proto3,oneof" json:"reply_to_message_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendPrivateMessageRequest) Reset() {
	*x = SendPrivateMessageRequest{}
	mi := &file_pb_chat_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageRequest) ProtoMessage() {}

func (x *SendPrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{5}
}

func (x *SendPrivateMessageRequest) GetTableUserId() uint64 {
	if x != nil {
		return x.TableUserId
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetToTableUserId() uint64 {
	if x != nil {
		return x.ToTableUserId
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetMediaUrl() string {
	if x != nil && x.MediaUrl != nil {
		return *x.MediaUrl
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetAttachments() []string {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendPrivateMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_TEXT
}

func (x *SendPrivateMessageRequest) GetMessageStatus() MessageStatus {
	if x != nil {
		return x.MessageStatus
	}
	return MessageStatus_SENT
}

func (x *SendPrivateMessageRequest) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

func (x *SendPrivateMessageRequest) GetReplyToMessageId() string {
	if x != nil && x.ReplyToMessageId != nil {
		return *x.ReplyToMessageId
	}
	return ""
}

// Request to update a message's content.
type UpdateMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the user in the table requesting the update.
	TableUserId uint64 `protobuf:"varint,1,opt,name=table_user_id,json=tableUserId,proto3" json:"table_user_id,omitempty"`
	// UUID of the message to be updated.
	MessageUuid string `protobuf:"bytes,2,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	// The new text content for the message.
	NewMessage string `protobuf:"bytes,3,opt,name=new_message,json=newMessage,proto3" json:"new_message,omitempty"`
	// The update timestamp.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageRequest) Reset() {
	*x = UpdateMessageRequest{}
	mi := &file_pb_chat_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageRequest) ProtoMessage() {}

func (x *UpdateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageRequest) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMessageRequest) GetTableUserId() uint64 {
	if x != nil {
		return x.TableUserId
	}
	return 0
}

func (x *UpdateMessageRequest) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *UpdateMessageRequest) GetNewMessage() string {
	if x != nil {
		return x.NewMessage
	}
	return ""
}

func (x *UpdateMessageRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Event triggered when a new message is sent.
type ChatMessageSent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message that was sent.
	Message       *ChatMessageResponse `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageSent) Reset() {
	*x = ChatMessageSent{}
	mi := &file_pb_chat_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageSent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageSent) ProtoMessage() {}

func (x *ChatMessageSent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageSent.ProtoReflect.Descriptor instead.
func (*ChatMessageSent) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessageSent) GetMessage() *ChatMessageResponse {
	if x != nil {
		return x.Message
	}
	return nil
}

// Event triggered when a message is updated.
type ChatMessageUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message with its updated content.
	Message       *ChatMessageResponse `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageUpdated) Reset() {
	*x = ChatMessageUpdated{}
	mi := &file_pb_chat_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageUpdated) ProtoMessage() {}

func (x *ChatMessageUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageUpdated.ProtoReflect.Descriptor instead.
func (*ChatMessageUpdated) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessageUpdated) GetMessage() *ChatMessageResponse {
	if x != nil {
		return x.Message
	}
	return nil
}

// Event triggered when a message is deleted.
type ChatMessageDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the message that was deleted.
	MessageUuid string `protobuf:"bytes,1,opt,name=message_uuid,json=messageUuid,proto3" json:"message_uuid,omitempty"`
	// ID of the table where the message was deleted.
	TableId       uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageDeleted) Reset() {
	*x = ChatMessageDeleted{}
	mi := &file_pb_chat_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageDeleted) ProtoMessage() {}

func (x *ChatMessageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_chat_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageDeleted.ProtoReflect.Descriptor instead.
func (*ChatMessageDeleted) Descriptor() ([]byte, []int) {
	return file_pb_chat_chat_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessageDeleted) GetMessageUuid() string {
	if x != nil {
		return x.MessageUuid
	}
	return ""
}

func (x *ChatMessageDeleted) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

var File_pb_chat_chat_proto protoreflect.FileDescriptor

const file_pb_chat_chat_proto_rawDesc = "" +
	"\n" +
	"\x12pb/chat/chat.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\x8e\x01\n" +
	"\x13ListMessagesRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12+\n" +
	"\x0flast_message_id\x18\x02 \x01(\tH\x00R\rlastMessageId\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSizeB\x12\n" +
	"\x10_last_message_id\"\x86\x01\n" +
	"\x17ListChatMessageResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.chat.ChatMessageResponseR\bmessages\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"\xc4\x03\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12&\n" +
	"\fmessage_text\x18\x03 \x01(\tH\x00R\vmessageText\x88\x01\x01\x123\n" +
	"\vmessageType\x18\x04 \x01(\x0e2\x11.chat.MessageTypeR\vmessageType\x129\n" +
	"\rmessageStatus\x18\x05 \x01(\x0e2\x13.chat.MessageStatusR\rmessageStatus\x123\n" +
	"\asend_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\x122\n" +
	"\x13reply_to_message_id\x18\a \x01(\tH\x01R\x10replyToMessageId\x88\x01\x01\x12 \n" +
	"\vattachments\x18\b \x03(\tR\vattachments\x12 \n" +
	"\tmedia_url\x18\t \x01(\tH\x02R\bmediaUrl\x88\x01\x01B\x0f\n" +
	"\r_message_textB\x16\n" +
	"\x14_reply_to_message_idB\f\n" +
	"\n" +
	"_media_url\"\xbf\x05\n" +
	"\x13ChatMessageResponse\x12!\n" +
	"\fmessage_uuid\x18\x01 \x01(\tR\vmessageUuid\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x04R\bsenderId\x12'\n" +
	"\x0fsender_username\x18\x04 \x01(\tR\x0esenderUsername\x12!\n" +
	"\fmessage_text\x18\x05 \x01(\tR\vmessageText\x124\n" +
	"\fmessage_type\x18\x06 \x01(\x0e2\x11.chat.MessageTypeR\vmessageType\x12:\n" +
	"\x0emessage_status\x18\a \x01(\x0e2\x13.chat.MessageStatusR\rmessageStatus\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12 \n" +
	"\tmedia_url\x18\t \x01(\tH\x00R\bmediaUrl\x88\x01\x01\x12 \n" +
	"\vattachments\x18\n" +
	" \x03(\tR\vattachments\x122\n" +
	"\x13reply_to_message_id\x18\v \x01(\tH\x01R\x10replyToMessageId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\bR\tisDeleted\x12>\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tupdatedAt\x88\x01\x01\x125\n" +
	"\x14private_recipient_id\x18\x0e \x01(\x04H\x03R\x12privateRecipientId\x88\x01\x01B\f\n" +
	"\n" +
	"_media_urlB\x16\n" +
	"\x14_reply_to_message_idB\r\n" +
	"\v_updated_atB\x17\n" +
	"\x15_private_recipient_id\"]\n" +
	"\x14DeleteMessageRequest\x12\"\n" +
	"\rtable_user_id\x18\x01 \x01(\x04R\vtableUserId\x12!\n" +
	"\fmessage_uuid\x18\x02 \x01(\tR\vmessageUuid\"\x95\x04\n" +
	"\x19SendPrivateMessageRequest\x12\"\n" +
	"\rtable_user_id\x18\x01 \x01(\x04R\vtableUserId\x12'\n" +
	"\x10to_table_user_id\x18\x02 \x01(\x04R\rtoTableUserId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01\x12!\n" +
	"\fmessage_uuid\x18\x05 \x01(\tR\vmessageUuid\x12 \n" +
	"\tmedia_url\x18\x06 \x01(\tH\x01R\bmediaUrl\x88\x01\x01\x12 \n" +
	"\vattachments\x18\a \x03(\tR\vattachments\x123\n" +
	"\vmessageType\x18\b \x01(\x0e2\x11.chat.MessageTypeR\vmessageType\x129\n" +
	"\rmessageStatus\x18\t \x01(\x0e2\x13.chat.MessageStatusR\rmessageStatus\x123\n" +
	"\asend_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\x122\n" +
	"\x13reply_to_message_id\x18\v \x01(\tH\x02R\x10replyToMessageId\x88\x01\x01B\n" +
	"\n" +
	"\b_messageB\f\n" +
	"\n" +
	"_media_urlB\x16\n" +
	"\x14_reply_to_message_id\"\xb9\x01\n" +
	"\x14UpdateMessageRequest\x12\"\n" +
	"\rtable_user_id\x18\x01 \x01(\x04R\vtableUserId\x12!\n" +
	"\fmessage_uuid\x18\x02 \x01(\tR\vmessageUuid\x12\x1f\n" +
	"\vnew_message\x18\x03 \x01(\tR\n" +
	"newMessage\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"F\n" +
	"\x0fChatMessageSent\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.chat.ChatMessageResponseR\amessage\"I\n" +
	"\x12ChatMessageUpdated\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.chat.ChatMessageResponseR\amessage\"R\n" +
	"\x12ChatMessageDeleted\x12!\n" +
	"\fmessage_uuid\x18\x01 \x01(\tR\vmessageUuid\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId*R\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03\x12\f\n" +
	"\bDOCUMENT\x10\x04\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x05*2\n" +
	"\rMessageStatus\x12\b\n" +
	"\x04SENT\x10\x00\x12\r\n" +
	"\tDELIVERED\x10\x01\x12\b\n" +
	"\x04READ\x10\x022\xea\x02\n" +
	"\x04Chat\x12?\n" +
	"\vSendMessage\x12\x18.chat.SendMessageRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\fListMessages\x12\x19.chat.ListMessagesRequest\x1a\x1d.chat.ListChatMessageResponse\x12C\n" +
	"\rUpdateMessage\x12\x1a.chat.UpdateMessageRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\rDeleteMessage\x12\x1a.chat.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x12SendPrivateMessage\x12\x1f.chat.SendPrivateMessageRequest\x1a\x16.google.protobuf.EmptyB:Z8github.com/GarotoCowboy/vttProject/api/grpc/pb/chat;chatb\x06proto3"

var (
	file_pb_chat_chat_proto_rawDescOnce sync.Once
	file_pb_chat_chat_proto_rawDescData []byte
)

func file_pb_chat_chat_proto_rawDescGZIP() []byte {
	file_pb_chat_chat_proto_rawDescOnce.Do(func() {
		file_pb_chat_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_chat_chat_proto_rawDesc), len(file_pb_chat_chat_proto_rawDesc)))
	})
	return file_pb_chat_chat_proto_rawDescData
}

var file_pb_chat_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_chat_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_chat_chat_proto_goTypes = []any{
	(MessageType)(0),                  // 0: chat.MessageType
	(MessageStatus)(0),                // 1: chat.MessageStatus
	(*ListMessagesRequest)(nil),       // 2: chat.ListMessagesRequest
	(*ListChatMessageResponse)(nil),   // 3: chat.ListChatMessageResponse
	(*SendMessageRequest)(nil),        // 4: chat.SendMessageRequest
	(*ChatMessageResponse)(nil),       // 5: chat.ChatMessageResponse
	(*DeleteMessageRequest)(nil),      // 6: chat.DeleteMessageRequest
	(*SendPrivateMessageRequest)(nil), // 7: chat.SendPrivateMessageRequest
	(*UpdateMessageRequest)(nil),      // 8: chat.UpdateMessageRequest
	(*ChatMessageSent)(nil),           // 9: chat.ChatMessageSent
	(*ChatMessageUpdated)(nil),        // 10: chat.ChatMessageUpdated
	(*ChatMessageDeleted)(nil),        // 11: chat.ChatMessageDeleted
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 13: google.protobuf.Empty
}
var file_pb_chat_chat_proto_depIdxs = []int32{
	5,  // 0: chat.ListChatMessageResponse.messages:type_name -> chat.ChatMessageResponse
	0,  // 1: chat.SendMessageRequest.messageType:type_name -> chat.MessageType
	1,  // 2: chat.SendMessageRequest.messageStatus:type_name -> chat.MessageStatus
	12, // 3: chat.SendMessageRequest.send_at:type_name -> google.protobuf.Timestamp
	0,  // 4: chat.ChatMessageResponse.message_type:type_name -> chat.MessageType
	1,  // 5: chat.ChatMessageResponse.message_status:type_name -> chat.MessageStatus
	12, // 6: chat.ChatMessageResponse.sent_at:type_name -> google.protobuf.Timestamp
	12, // 7: chat.ChatMessageResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: chat.SendPrivateMessageRequest.messageType:type_name -> chat.MessageType
	1,  // 9: chat.SendPrivateMessageRequest.messageStatus:type_name -> chat.MessageStatus
	12, // 10: chat.SendPrivateMessageRequest.send_at:type_name -> google.protobuf.Timestamp
	12, // 11: chat.UpdateMessageRequest.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 12: chat.ChatMessageSent.message:type_name -> chat.ChatMessageResponse
	5,  // 13: chat.ChatMessageUpdated.message:type_name -> chat.ChatMessageResponse
	4,  // 14: chat.Chat.SendMessage:input_type -> chat.SendMessageRequest
	2,  // 15: chat.Chat.ListMessages:input_type -> chat.ListMessagesRequest
	8,  // 16: chat.Chat.UpdateMessage:input_type -> chat.UpdateMessageRequest
	6,  // 17: chat.Chat.DeleteMessage:input_type -> chat.DeleteMessageRequest
	7,  // 18: chat.Chat.SendPrivateMessage:input_type -> chat.SendPrivateMessageRequest
	13, // 19: chat.Chat.SendMessage:output_type -> google.protobuf.Empty
	3,  // 20: chat.Chat.ListMessages:output_type -> chat.ListChatMessageResponse
	13, // 21: chat.Chat.UpdateMessage:output_type -> google.protobuf.Empty
	13, // 22: chat.Chat.DeleteMessage:output_type -> google.protobuf.Empty
	13, // 23: chat.Chat.SendPrivateMessage:output_type -> google.protobuf.Empty
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_pb_chat_chat_proto_init() }
func file_pb_chat_chat_proto_init() {
	if File_pb_chat_chat_proto != nil {
		return
	}
	file_pb_chat_chat_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_chat_chat_proto_msgTypes[1].OneofWrappers = []any{}
	file_pb_chat_chat_proto_msgTypes[2].OneofWrappers = []any{}
	file_pb_chat_chat_proto_msgTypes[3].OneofWrappers = []any{}
	file_pb_chat_chat_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_chat_chat_proto_rawDesc), len(file_pb_chat_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_chat_chat_proto_goTypes,
		DependencyIndexes: file_pb_chat_chat_proto_depIdxs,
		EnumInfos:         file_pb_chat_chat_proto_enumTypes,
		MessageInfos:      file_pb_chat_chat_proto_msgTypes,
	}.Build()
	File_pb_chat_chat_proto = out.File
	file_pb_chat_chat_proto_goTypes = nil
	file_pb_chat_chat_proto_depIdxs = nil
}
