// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/placedToken/placedToken.proto

package placedToken

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines the different layers a token can exist on within a scene.
type LayerType int32

const (
	// The default layer, visible to players and the GM.
	LayerType_PLAYER_LAYER LayerType = 0
	// The layer for map elements, typically below the player layer.
	LayerType_MAP_LAYER LayerType = 1
	// A layer only visible to the Game Master (GM).
	LayerType_MASTER_LAYER LayerType = 2
)

// Enum value maps for LayerType.
var (
	LayerType_name = map[int32]string{
		0: "PLAYER_LAYER",
		1: "MAP_LAYER",
		2: "MASTER_LAYER",
	}
	LayerType_value = map[string]int32{
		"PLAYER_LAYER": 0,
		"MAP_LAYER":    1,
		"MASTER_LAYER": 2,
	}
)

func (x LayerType) Enum() *LayerType {
	p := new(LayerType)
	*p = x
	return p
}

func (x LayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_placedToken_placedToken_proto_enumTypes[0].Descriptor()
}

func (LayerType) Type() protoreflect.EnumType {
	return &file_pb_placedToken_placedToken_proto_enumTypes[0]
}

func (x LayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerType.Descriptor instead.
func (LayerType) EnumDescriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{0}
}

// Represents a token instance that has been placed onto a scene.
type PlacedToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene where the token is placed.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the original token template from the library.
	TokenId uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The unique identifier for this specific instance of the token on the scene.
	PlacedTokenId uint64 `protobuf:"varint,3,opt,name=placed_token_id,json=placedTokenId,proto3" json:"placed_token_id,omitempty"`
	// The X-coordinate of the token's position on the scene grid.
	PosX int32 `protobuf:"varint,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The Y-coordinate of the token's position on the scene grid.
	PosY int32 `protobuf:"varint,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	// The layer on which the token is placed (e.g., map, player, GM layer).
	Layer LayerType `protobuf:"varint,6,opt,name=layer,proto3,enum=placedToken.LayerType" json:"layer,omitempty"`
	// The size of the token, often in grid units.
	Size int32 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// The rotation of the token in degrees.
	Rotation int32 `protobuf:"varint,8,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// Timestamp of when this token was placed on the scene.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of the last update to this placed token.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedToken) Reset() {
	*x = PlacedToken{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedToken) ProtoMessage() {}

func (x *PlacedToken) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedToken.ProtoReflect.Descriptor instead.
func (*PlacedToken) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{0}
}

func (x *PlacedToken) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedToken) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *PlacedToken) GetPlacedTokenId() uint64 {
	if x != nil {
		return x.PlacedTokenId
	}
	return 0
}

func (x *PlacedToken) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlacedToken) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *PlacedToken) GetLayer() LayerType {
	if x != nil {
		return x.Layer
	}
	return LayerType_PLAYER_LAYER
}

func (x *PlacedToken) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PlacedToken) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *PlacedToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PlacedToken) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to create a new placed token.
type CreatePlacedTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene to place the token on.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the token template to use.
	TokenId uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The initial X-coordinate for the token.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The initial Y-coordinate for the token.
	PosY          int32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlacedTokenRequest) Reset() {
	*x = CreatePlacedTokenRequest{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlacedTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlacedTokenRequest) ProtoMessage() {}

func (x *CreatePlacedTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlacedTokenRequest.ProtoReflect.Descriptor instead.
func (*CreatePlacedTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePlacedTokenRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CreatePlacedTokenRequest) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *CreatePlacedTokenRequest) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CreatePlacedTokenRequest) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// Response after creating a placed token.
type CreatePlacedTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full object of the newly created placed token.
	PlacedToken   *PlacedToken `protobuf:"bytes,1,opt,name=placed_token,json=placedToken,proto3" json:"placed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlacedTokenResponse) Reset() {
	*x = CreatePlacedTokenResponse{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlacedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlacedTokenResponse) ProtoMessage() {}

func (x *CreatePlacedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlacedTokenResponse.ProtoReflect.Descriptor instead.
func (*CreatePlacedTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePlacedTokenResponse) GetPlacedToken() *PlacedToken {
	if x != nil {
		return x.PlacedToken
	}
	return nil
}

// Request to edit a placed token.
type EditPlacedTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The placed token object with the new data. `placed_token_id` must be specified.
	PlacedToken *PlacedToken `protobuf:"bytes,1,opt,name=placed_token,json=placedToken,proto3" json:"placed_token,omitempty"`
	// A field mask to specify which fields should be updated (e.g., "size", "rotation").
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlacedTokenRequest) Reset() {
	*x = EditPlacedTokenRequest{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlacedTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlacedTokenRequest) ProtoMessage() {}

func (x *EditPlacedTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlacedTokenRequest.ProtoReflect.Descriptor instead.
func (*EditPlacedTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{3}
}

func (x *EditPlacedTokenRequest) GetPlacedToken() *PlacedToken {
	if x != nil {
		return x.PlacedToken
	}
	return nil
}

func (x *EditPlacedTokenRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// Response after editing a placed token.
type EditPlacedTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full, updated placed token object.
	PlacedToken   *PlacedToken `protobuf:"bytes,1,opt,name=placed_token,json=placedToken,proto3" json:"placed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditPlacedTokenResponse) Reset() {
	*x = EditPlacedTokenResponse{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditPlacedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditPlacedTokenResponse) ProtoMessage() {}

func (x *EditPlacedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditPlacedTokenResponse.ProtoReflect.Descriptor instead.
func (*EditPlacedTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{4}
}

func (x *EditPlacedTokenResponse) GetPlacedToken() *PlacedToken {
	if x != nil {
		return x.PlacedToken
	}
	return nil
}

// Request to delete a placed token.
type DeletePlacedTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the token instance to delete.
	PlacedTokenId uint64 `protobuf:"varint,1,opt,name=placed_token_id,json=placedTokenId,proto3" json:"placed_token_id,omitempty"`
	// The ID of the scene the token belongs to, for validation.
	SceneId       uint64 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlacedTokenRequest) Reset() {
	*x = DeletePlacedTokenRequest{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlacedTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlacedTokenRequest) ProtoMessage() {}

func (x *DeletePlacedTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlacedTokenRequest.ProtoReflect.Descriptor instead.
func (*DeletePlacedTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{5}
}

func (x *DeletePlacedTokenRequest) GetPlacedTokenId() uint64 {
	if x != nil {
		return x.PlacedTokenId
	}
	return 0
}

func (x *DeletePlacedTokenRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// Response for a delete operation.
type DeletePlacedTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An empty message indicates success.
	Empty         *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePlacedTokenResponse) Reset() {
	*x = DeletePlacedTokenResponse{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePlacedTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlacedTokenResponse) ProtoMessage() {}

func (x *DeletePlacedTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlacedTokenResponse.ProtoReflect.Descriptor instead.
func (*DeletePlacedTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePlacedTokenResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

// Request to list all tokens on a scene.
type ListAllTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene whose tokens are to be listed.
	SceneId       uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTokensRequest) Reset() {
	*x = ListAllTokensRequest{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTokensRequest) ProtoMessage() {}

func (x *ListAllTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTokensRequest.ProtoReflect.Descriptor instead.
func (*ListAllTokensRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllTokensRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// Response containing a list of all tokens on a scene.
type ListAllTokensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of placed token objects.
	PlacedTokens  []*PlacedToken `protobuf:"bytes,1,rep,name=placed_tokens,json=placedTokens,proto3" json:"placed_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTokensResponse) Reset() {
	*x = ListAllTokensResponse{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTokensResponse) ProtoMessage() {}

func (x *ListAllTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTokensResponse.ProtoReflect.Descriptor instead.
func (*ListAllTokensResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{8}
}

func (x *ListAllTokensResponse) GetPlacedTokens() []*PlacedToken {
	if x != nil {
		return x.PlacedTokens
	}
	return nil
}

// Request to move a token to a new location.
type MoveTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene where the move is happening.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the token instance being moved.
	PlacedTokenId uint64 `protobuf:"varint,2,opt,name=placed_token_id,json=placedTokenId,proto3" json:"placed_token_id,omitempty"`
	// The new X-coordinate.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The new Y-coordinate.
	PosY          int32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTokenRequest) Reset() {
	*x = MoveTokenRequest{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTokenRequest) ProtoMessage() {}

func (x *MoveTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTokenRequest.ProtoReflect.Descriptor instead.
func (*MoveTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{9}
}

func (x *MoveTokenRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *MoveTokenRequest) GetPlacedTokenId() uint64 {
	if x != nil {
		return x.PlacedTokenId
	}
	return 0
}

func (x *MoveTokenRequest) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *MoveTokenRequest) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// Response after a move operation.
type MoveTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the move was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveTokenResponse) Reset() {
	*x = MoveTokenResponse{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveTokenResponse) ProtoMessage() {}

func (x *MoveTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveTokenResponse.ProtoReflect.Descriptor instead.
func (*MoveTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{10}
}

func (x *MoveTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Event triggered when a new token is placed on a scene.
type PlacedTokenCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created token instance.
	PlacedToken   *PlacedToken `protobuf:"bytes,1,opt,name=placed_token,json=placedToken,proto3" json:"placed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedTokenCreated) Reset() {
	*x = PlacedTokenCreated{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedTokenCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedTokenCreated) ProtoMessage() {}

func (x *PlacedTokenCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedTokenCreated.ProtoReflect.Descriptor instead.
func (*PlacedTokenCreated) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{11}
}

func (x *PlacedTokenCreated) GetPlacedToken() *PlacedToken {
	if x != nil {
		return x.PlacedToken
	}
	return nil
}

// Event triggered when a placed token's properties are updated.
type PlacedTokenUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token instance with its updated data.
	PlacedToken   *PlacedToken `protobuf:"bytes,1,opt,name=placed_token,json=placedToken,proto3" json:"placed_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedTokenUpdated) Reset() {
	*x = PlacedTokenUpdated{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedTokenUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedTokenUpdated) ProtoMessage() {}

func (x *PlacedTokenUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedTokenUpdated.ProtoReflect.Descriptor instead.
func (*PlacedTokenUpdated) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{12}
}

func (x *PlacedTokenUpdated) GetPlacedToken() *PlacedToken {
	if x != nil {
		return x.PlacedToken
	}
	return nil
}

// Event triggered when a token is deleted from a scene.
type PlacedTokenDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene from which the token was deleted.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the token instance that was deleted.
	PlacedTokenId uint64 `protobuf:"varint,2,opt,name=placed_token_id,json=placedTokenId,proto3" json:"placed_token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedTokenDeleted) Reset() {
	*x = PlacedTokenDeleted{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedTokenDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedTokenDeleted) ProtoMessage() {}

func (x *PlacedTokenDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedTokenDeleted.ProtoReflect.Descriptor instead.
func (*PlacedTokenDeleted) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{13}
}

func (x *PlacedTokenDeleted) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedTokenDeleted) GetPlacedTokenId() uint64 {
	if x != nil {
		return x.PlacedTokenId
	}
	return 0
}

// Event triggered when a token is moved.
type PlacedTokenMoved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene where the token moved.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the token instance that moved.
	PlacedTokenId uint64 `protobuf:"varint,2,opt,name=placed_token_id,json=placedTokenId,proto3" json:"placed_token_id,omitempty"`
	// The new X-coordinate of the token.
	PosX int32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	// The new Y-coordinate of the token.
	PosY          int32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacedTokenMoved) Reset() {
	*x = PlacedTokenMoved{}
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacedTokenMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacedTokenMoved) ProtoMessage() {}

func (x *PlacedTokenMoved) ProtoReflect() protoreflect.Message {
	mi := &file_pb_placedToken_placedToken_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacedTokenMoved.ProtoReflect.Descriptor instead.
func (*PlacedTokenMoved) Descriptor() ([]byte, []int) {
	return file_pb_placedToken_placedToken_proto_rawDescGZIP(), []int{14}
}

func (x *PlacedTokenMoved) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *PlacedTokenMoved) GetPlacedTokenId() uint64 {
	if x != nil {
		return x.PlacedTokenId
	}
	return 0
}

func (x *PlacedTokenMoved) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *PlacedTokenMoved) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

var File_pb_placedToken_placedToken_proto protoreflect.FileDescriptor

const file_pb_placedToken_placedToken_proto_rawDesc = "" +
	"\n" +
	" pb/placedToken/placedToken.proto\x12\vplacedToken\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe9\x02\n" +
	"\vPlacedToken\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\x12&\n" +
	"\x0fplaced_token_id\x18\x03 \x01(\x04R\rplacedTokenId\x12\x13\n" +
	"\x05pos_x\x18\x04 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x05 \x01(\x05R\x04posY\x12,\n" +
	"\x05layer\x18\x06 \x01(\x0e2\x16.placedToken.LayerTypeR\x05layer\x12\x12\n" +
	"\x04size\x18\a \x01(\x05R\x04size\x12\x1a\n" +
	"\brotation\x18\b \x01(\x05R\brotation\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"z\n" +
	"\x18CreatePlacedTokenRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY\"X\n" +
	"\x19CreatePlacedTokenResponse\x12;\n" +
	"\fplaced_token\x18\x01 \x01(\v2\x18.placedToken.PlacedTokenR\vplacedToken\"\x85\x01\n" +
	"\x16EditPlacedTokenRequest\x12;\n" +
	"\fplaced_token\x18\x01 \x01(\v2\x18.placedToken.PlacedTokenR\vplacedToken\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"V\n" +
	"\x17EditPlacedTokenResponse\x12;\n" +
	"\fplaced_token\x18\x01 \x01(\v2\x18.placedToken.PlacedTokenR\vplacedToken\"]\n" +
	"\x18DeletePlacedTokenRequest\x12&\n" +
	"\x0fplaced_token_id\x18\x01 \x01(\x04R\rplacedTokenId\x12\x19\n" +
	"\bscene_id\x18\x02 \x01(\x04R\asceneId\"I\n" +
	"\x19DeletePlacedTokenResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"1\n" +
	"\x14ListAllTokensRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\"V\n" +
	"\x15ListAllTokensResponse\x12=\n" +
	"\rplaced_tokens\x18\x01 \x03(\v2\x18.placedToken.PlacedTokenR\fplacedTokens\"\x7f\n" +
	"\x10MoveTokenRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_token_id\x18\x02 \x01(\x04R\rplacedTokenId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY\"-\n" +
	"\x11MoveTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x12PlacedTokenCreated\x12;\n" +
	"\fplaced_token\x18\x01 \x01(\v2\x18.placedToken.PlacedTokenR\vplacedToken\"Q\n" +
	"\x12PlacedTokenUpdated\x12;\n" +
	"\fplaced_token\x18\x01 \x01(\v2\x18.placedToken.PlacedTokenR\vplacedToken\"W\n" +
	"\x12PlacedTokenDeleted\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_token_id\x18\x02 \x01(\x04R\rplacedTokenId\"\x7f\n" +
	"\x10PlacedTokenMoved\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12&\n" +
	"\x0fplaced_token_id\x18\x02 \x01(\x04R\rplacedTokenId\x12\x13\n" +
	"\x05pos_x\x18\x03 \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\x04 \x01(\x05R\x04posY*>\n" +
	"\tLayerType\x12\x10\n" +
	"\fPLAYER_LAYER\x10\x00\x12\r\n" +
	"\tMAP_LAYER\x10\x01\x12\x10\n" +
	"\fMASTER_LAYER\x10\x022\xe5\x03\n" +
	"\x12PlacedTokenService\x12b\n" +
	"\x11CreatePlacedToken\x12%.placedToken.CreatePlacedTokenRequest\x1a&.placedToken.CreatePlacedTokenResponse\x12\\\n" +
	"\x0fEditPlacedToken\x12#.placedToken.EditPlacedTokenRequest\x1a$.placedToken.EditPlacedTokenResponse\x12b\n" +
	"\x11DeletePlacedToken\x12%.placedToken.DeletePlacedTokenRequest\x1a&.placedToken.DeletePlacedTokenResponse\x12]\n" +
	"\x14ListAllTokensOnScene\x12!.placedToken.ListAllTokensRequest\x1a\".placedToken.ListAllTokensResponse\x12J\n" +
	"\tMoveToken\x12\x1d.placedToken.MoveTokenRequest\x1a\x1e.placedToken.MoveTokenResponseBHZFgithub.com/GarotoCowboy/vttProject/api/grpc/pb/placedToken;placedTokenb\x06proto3"

var (
	file_pb_placedToken_placedToken_proto_rawDescOnce sync.Once
	file_pb_placedToken_placedToken_proto_rawDescData []byte
)

func file_pb_placedToken_placedToken_proto_rawDescGZIP() []byte {
	file_pb_placedToken_placedToken_proto_rawDescOnce.Do(func() {
		file_pb_placedToken_placedToken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_placedToken_placedToken_proto_rawDesc), len(file_pb_placedToken_placedToken_proto_rawDesc)))
	})
	return file_pb_placedToken_placedToken_proto_rawDescData
}

var file_pb_placedToken_placedToken_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_placedToken_placedToken_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_pb_placedToken_placedToken_proto_goTypes = []any{
	(LayerType)(0),                    // 0: placedToken.LayerType
	(*PlacedToken)(nil),               // 1: placedToken.PlacedToken
	(*CreatePlacedTokenRequest)(nil),  // 2: placedToken.CreatePlacedTokenRequest
	(*CreatePlacedTokenResponse)(nil), // 3: placedToken.CreatePlacedTokenResponse
	(*EditPlacedTokenRequest)(nil),    // 4: placedToken.EditPlacedTokenRequest
	(*EditPlacedTokenResponse)(nil),   // 5: placedToken.EditPlacedTokenResponse
	(*DeletePlacedTokenRequest)(nil),  // 6: placedToken.DeletePlacedTokenRequest
	(*DeletePlacedTokenResponse)(nil), // 7: placedToken.DeletePlacedTokenResponse
	(*ListAllTokensRequest)(nil),      // 8: placedToken.ListAllTokensRequest
	(*ListAllTokensResponse)(nil),     // 9: placedToken.ListAllTokensResponse
	(*MoveTokenRequest)(nil),          // 10: placedToken.MoveTokenRequest
	(*MoveTokenResponse)(nil),         // 11: placedToken.MoveTokenResponse
	(*PlacedTokenCreated)(nil),        // 12: placedToken.PlacedTokenCreated
	(*PlacedTokenUpdated)(nil),        // 13: placedToken.PlacedTokenUpdated
	(*PlacedTokenDeleted)(nil),        // 14: placedToken.PlacedTokenDeleted
	(*PlacedTokenMoved)(nil),          // 15: placedToken.PlacedTokenMoved
	(*timestamppb.Timestamp)(nil),     // 16: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),     // 17: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),             // 18: google.protobuf.Empty
}
var file_pb_placedToken_placedToken_proto_depIdxs = []int32{
	0,  // 0: placedToken.PlacedToken.layer:type_name -> placedToken.LayerType
	16, // 1: placedToken.PlacedToken.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: placedToken.PlacedToken.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: placedToken.CreatePlacedTokenResponse.placed_token:type_name -> placedToken.PlacedToken
	1,  // 4: placedToken.EditPlacedTokenRequest.placed_token:type_name -> placedToken.PlacedToken
	17, // 5: placedToken.EditPlacedTokenRequest.mask:type_name -> google.protobuf.FieldMask
	1,  // 6: placedToken.EditPlacedTokenResponse.placed_token:type_name -> placedToken.PlacedToken
	18, // 7: placedToken.DeletePlacedTokenResponse.empty:type_name -> google.protobuf.Empty
	1,  // 8: placedToken.ListAllTokensResponse.placed_tokens:type_name -> placedToken.PlacedToken
	1,  // 9: placedToken.PlacedTokenCreated.placed_token:type_name -> placedToken.PlacedToken
	1,  // 10: placedToken.PlacedTokenUpdated.placed_token:type_name -> placedToken.PlacedToken
	2,  // 11: placedToken.PlacedTokenService.CreatePlacedToken:input_type -> placedToken.CreatePlacedTokenRequest
	4,  // 12: placedToken.PlacedTokenService.EditPlacedToken:input_type -> placedToken.EditPlacedTokenRequest
	6,  // 13: placedToken.PlacedTokenService.DeletePlacedToken:input_type -> placedToken.DeletePlacedTokenRequest
	8,  // 14: placedToken.PlacedTokenService.ListAllTokensOnScene:input_type -> placedToken.ListAllTokensRequest
	10, // 15: placedToken.PlacedTokenService.MoveToken:input_type -> placedToken.MoveTokenRequest
	3,  // 16: placedToken.PlacedTokenService.CreatePlacedToken:output_type -> placedToken.CreatePlacedTokenResponse
	5,  // 17: placedToken.PlacedTokenService.EditPlacedToken:output_type -> placedToken.EditPlacedTokenResponse
	7,  // 18: placedToken.PlacedTokenService.DeletePlacedToken:output_type -> placedToken.DeletePlacedTokenResponse
	9,  // 19: placedToken.PlacedTokenService.ListAllTokensOnScene:output_type -> placedToken.ListAllTokensResponse
	11, // 20: placedToken.PlacedTokenService.MoveToken:output_type -> placedToken.MoveTokenResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_placedToken_placedToken_proto_init() }
func file_pb_placedToken_placedToken_proto_init() {
	if File_pb_placedToken_placedToken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_placedToken_placedToken_proto_rawDesc), len(file_pb_placedToken_placedToken_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_placedToken_placedToken_proto_goTypes,
		DependencyIndexes: file_pb_placedToken_placedToken_proto_depIdxs,
		EnumInfos:         file_pb_placedToken_placedToken_proto_enumTypes,
		MessageInfos:      file_pb_placedToken_placedToken_proto_msgTypes,
	}.Build()
	File_pb_placedToken_placedToken_proto = out.File
	file_pb_placedToken_placedToken_proto_goTypes = nil
	file_pb_placedToken_placedToken_proto_depIdxs = nil
}
