// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/placedToken/placedToken.proto

package placedToken

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlacedTokenService_CreatePlacedToken_FullMethodName    = "/placedToken.PlacedTokenService/CreatePlacedToken"
	PlacedTokenService_EditPlacedToken_FullMethodName      = "/placedToken.PlacedTokenService/EditPlacedToken"
	PlacedTokenService_DeletePlacedToken_FullMethodName    = "/placedToken.PlacedTokenService/DeletePlacedToken"
	PlacedTokenService_ListAllTokensOnScene_FullMethodName = "/placedToken.PlacedTokenService/ListAllTokensOnScene"
	PlacedTokenService_MoveToken_FullMethodName            = "/placedToken.PlacedTokenService/MoveToken"
)

// PlacedTokenServiceClient is the client API for PlacedTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `PlacedTokenService` manages token instances that are placed on a specific scene or map.
type PlacedTokenServiceClient interface {
	// Creates a new token instance on a scene.
	CreatePlacedToken(ctx context.Context, in *CreatePlacedTokenRequest, opts ...grpc.CallOption) (*CreatePlacedTokenResponse, error)
	// Edits the properties of an existing placed token.
	EditPlacedToken(ctx context.Context, in *EditPlacedTokenRequest, opts ...grpc.CallOption) (*EditPlacedTokenResponse, error)
	// Deletes a token from a scene.
	DeletePlacedToken(ctx context.Context, in *DeletePlacedTokenRequest, opts ...grpc.CallOption) (*DeletePlacedTokenResponse, error)
	// Lists all tokens currently on a specific scene.
	ListAllTokensOnScene(ctx context.Context, in *ListAllTokensRequest, opts ...grpc.CallOption) (*ListAllTokensResponse, error)
	// Moves a token to a new position on the scene.
	MoveToken(ctx context.Context, in *MoveTokenRequest, opts ...grpc.CallOption) (*MoveTokenResponse, error)
}

type placedTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlacedTokenServiceClient(cc grpc.ClientConnInterface) PlacedTokenServiceClient {
	return &placedTokenServiceClient{cc}
}

func (c *placedTokenServiceClient) CreatePlacedToken(ctx context.Context, in *CreatePlacedTokenRequest, opts ...grpc.CallOption) (*CreatePlacedTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlacedTokenResponse)
	err := c.cc.Invoke(ctx, PlacedTokenService_CreatePlacedToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedTokenServiceClient) EditPlacedToken(ctx context.Context, in *EditPlacedTokenRequest, opts ...grpc.CallOption) (*EditPlacedTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditPlacedTokenResponse)
	err := c.cc.Invoke(ctx, PlacedTokenService_EditPlacedToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedTokenServiceClient) DeletePlacedToken(ctx context.Context, in *DeletePlacedTokenRequest, opts ...grpc.CallOption) (*DeletePlacedTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePlacedTokenResponse)
	err := c.cc.Invoke(ctx, PlacedTokenService_DeletePlacedToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedTokenServiceClient) ListAllTokensOnScene(ctx context.Context, in *ListAllTokensRequest, opts ...grpc.CallOption) (*ListAllTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllTokensResponse)
	err := c.cc.Invoke(ctx, PlacedTokenService_ListAllTokensOnScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *placedTokenServiceClient) MoveToken(ctx context.Context, in *MoveTokenRequest, opts ...grpc.CallOption) (*MoveTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveTokenResponse)
	err := c.cc.Invoke(ctx, PlacedTokenService_MoveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlacedTokenServiceServer is the server API for PlacedTokenService service.
// All implementations must embed UnimplementedPlacedTokenServiceServer
// for forward compatibility.
//
// The `PlacedTokenService` manages token instances that are placed on a specific scene or map.
type PlacedTokenServiceServer interface {
	// Creates a new token instance on a scene.
	CreatePlacedToken(context.Context, *CreatePlacedTokenRequest) (*CreatePlacedTokenResponse, error)
	// Edits the properties of an existing placed token.
	EditPlacedToken(context.Context, *EditPlacedTokenRequest) (*EditPlacedTokenResponse, error)
	// Deletes a token from a scene.
	DeletePlacedToken(context.Context, *DeletePlacedTokenRequest) (*DeletePlacedTokenResponse, error)
	// Lists all tokens currently on a specific scene.
	ListAllTokensOnScene(context.Context, *ListAllTokensRequest) (*ListAllTokensResponse, error)
	// Moves a token to a new position on the scene.
	MoveToken(context.Context, *MoveTokenRequest) (*MoveTokenResponse, error)
	mustEmbedUnimplementedPlacedTokenServiceServer()
}

// UnimplementedPlacedTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlacedTokenServiceServer struct{}

func (UnimplementedPlacedTokenServiceServer) CreatePlacedToken(context.Context, *CreatePlacedTokenRequest) (*CreatePlacedTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlacedToken not implemented")
}
func (UnimplementedPlacedTokenServiceServer) EditPlacedToken(context.Context, *EditPlacedTokenRequest) (*EditPlacedTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPlacedToken not implemented")
}
func (UnimplementedPlacedTokenServiceServer) DeletePlacedToken(context.Context, *DeletePlacedTokenRequest) (*DeletePlacedTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlacedToken not implemented")
}
func (UnimplementedPlacedTokenServiceServer) ListAllTokensOnScene(context.Context, *ListAllTokensRequest) (*ListAllTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllTokensOnScene not implemented")
}
func (UnimplementedPlacedTokenServiceServer) MoveToken(context.Context, *MoveTokenRequest) (*MoveTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveToken not implemented")
}
func (UnimplementedPlacedTokenServiceServer) mustEmbedUnimplementedPlacedTokenServiceServer() {}
func (UnimplementedPlacedTokenServiceServer) testEmbeddedByValue()                            {}

// UnsafePlacedTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlacedTokenServiceServer will
// result in compilation errors.
type UnsafePlacedTokenServiceServer interface {
	mustEmbedUnimplementedPlacedTokenServiceServer()
}

func RegisterPlacedTokenServiceServer(s grpc.ServiceRegistrar, srv PlacedTokenServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlacedTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlacedTokenService_ServiceDesc, srv)
}

func _PlacedTokenService_CreatePlacedToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlacedTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedTokenServiceServer).CreatePlacedToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedTokenService_CreatePlacedToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedTokenServiceServer).CreatePlacedToken(ctx, req.(*CreatePlacedTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedTokenService_EditPlacedToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPlacedTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedTokenServiceServer).EditPlacedToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedTokenService_EditPlacedToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedTokenServiceServer).EditPlacedToken(ctx, req.(*EditPlacedTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedTokenService_DeletePlacedToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlacedTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedTokenServiceServer).DeletePlacedToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedTokenService_DeletePlacedToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedTokenServiceServer).DeletePlacedToken(ctx, req.(*DeletePlacedTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedTokenService_ListAllTokensOnScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedTokenServiceServer).ListAllTokensOnScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedTokenService_ListAllTokensOnScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedTokenServiceServer).ListAllTokensOnScene(ctx, req.(*ListAllTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlacedTokenService_MoveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlacedTokenServiceServer).MoveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlacedTokenService_MoveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlacedTokenServiceServer).MoveToken(ctx, req.(*MoveTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlacedTokenService_ServiceDesc is the grpc.ServiceDesc for PlacedTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlacedTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "placedToken.PlacedTokenService",
	HandlerType: (*PlacedTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlacedToken",
			Handler:    _PlacedTokenService_CreatePlacedToken_Handler,
		},
		{
			MethodName: "EditPlacedToken",
			Handler:    _PlacedTokenService_EditPlacedToken_Handler,
		},
		{
			MethodName: "DeletePlacedToken",
			Handler:    _PlacedTokenService_DeletePlacedToken_Handler,
		},
		{
			MethodName: "ListAllTokensOnScene",
			Handler:    _PlacedTokenService_ListAllTokensOnScene_Handler,
		},
		{
			MethodName: "MoveToken",
			Handler:    _PlacedTokenService_MoveToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/placedToken/placedToken.proto",
}
