// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/permission/permission.proto

package permission

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PermissionService_UpdatePlacedObjectAccess_FullMethodName      = "/permission.PermissionService/UpdatePlacedObjectAccess"
	PermissionService_UpdateLibraryObjectVisibility_FullMethodName = "/permission.PermissionService/UpdateLibraryObjectVisibility"
)

// PermissionServiceClient is the client API for PermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `PermissionService` handles access control for various in-game objects.
type PermissionServiceClient interface {
	// Updates who can view and modify an object that has been placed on the table (e.g., a token on the map).
	UpdatePlacedObjectAccess(ctx context.Context, in *UpdatePlacedObjectAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Updates the visibility of an object within a shared library (e.g., making a token visible to all players in the token library).
	UpdateLibraryObjectVisibility(ctx context.Context, in *UpdateLibraryObjectVisibilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type permissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPermissionServiceClient(cc grpc.ClientConnInterface) PermissionServiceClient {
	return &permissionServiceClient{cc}
}

func (c *permissionServiceClient) UpdatePlacedObjectAccess(ctx context.Context, in *UpdatePlacedObjectAccessRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PermissionService_UpdatePlacedObjectAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *permissionServiceClient) UpdateLibraryObjectVisibility(ctx context.Context, in *UpdateLibraryObjectVisibilityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PermissionService_UpdateLibraryObjectVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PermissionServiceServer is the server API for PermissionService service.
// All implementations must embed UnimplementedPermissionServiceServer
// for forward compatibility.
//
// The `PermissionService` handles access control for various in-game objects.
type PermissionServiceServer interface {
	// Updates who can view and modify an object that has been placed on the table (e.g., a token on the map).
	UpdatePlacedObjectAccess(context.Context, *UpdatePlacedObjectAccessRequest) (*emptypb.Empty, error)
	// Updates the visibility of an object within a shared library (e.g., making a token visible to all players in the token library).
	UpdateLibraryObjectVisibility(context.Context, *UpdateLibraryObjectVisibilityRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPermissionServiceServer()
}

// UnimplementedPermissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPermissionServiceServer struct{}

func (UnimplementedPermissionServiceServer) UpdatePlacedObjectAccess(context.Context, *UpdatePlacedObjectAccessRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlacedObjectAccess not implemented")
}
func (UnimplementedPermissionServiceServer) UpdateLibraryObjectVisibility(context.Context, *UpdateLibraryObjectVisibilityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLibraryObjectVisibility not implemented")
}
func (UnimplementedPermissionServiceServer) mustEmbedUnimplementedPermissionServiceServer() {}
func (UnimplementedPermissionServiceServer) testEmbeddedByValue()                           {}

// UnsafePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PermissionServiceServer will
// result in compilation errors.
type UnsafePermissionServiceServer interface {
	mustEmbedUnimplementedPermissionServiceServer()
}

func RegisterPermissionServiceServer(s grpc.ServiceRegistrar, srv PermissionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPermissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PermissionService_ServiceDesc, srv)
}

func _PermissionService_UpdatePlacedObjectAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlacedObjectAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).UpdatePlacedObjectAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_UpdatePlacedObjectAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).UpdatePlacedObjectAccess(ctx, req.(*UpdatePlacedObjectAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PermissionService_UpdateLibraryObjectVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLibraryObjectVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PermissionServiceServer).UpdateLibraryObjectVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PermissionService_UpdateLibraryObjectVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PermissionServiceServer).UpdateLibraryObjectVisibility(ctx, req.(*UpdateLibraryObjectVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PermissionService_ServiceDesc is the grpc.ServiceDesc for PermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "permission.PermissionService",
	HandlerType: (*PermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePlacedObjectAccess",
			Handler:    _PermissionService_UpdatePlacedObjectAccess_Handler,
		},
		{
			MethodName: "UpdateLibraryObjectVisibility",
			Handler:    _PermissionService_UpdateLibraryObjectVisibility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/permission/permission.proto",
}
