// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/bar/bar.proto

package bar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single bar with its properties.
type Bar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the bar.
	BarId uint64 `protobuf:"varint,1,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	// The ID of the token this bar belongs to.
	TokenId uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The name of the bar (e.g., "Health", "Stamina").
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The current value of the bar.
	Value int32 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	// The maximum possible value for the bar.
	MaxValue int32 `protobuf:"varint,5,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	// A string representing the color of the bar, e.g., a hex code like "#FF0000".
	Color         string `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_pb_bar_bar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{0}
}

func (x *Bar) GetBarId() uint64 {
	if x != nil {
		return x.BarId
	}
	return 0
}

func (x *Bar) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *Bar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bar) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Bar) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *Bar) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Request to create a new bar.
type CreateBarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the token to which the new bar will be attached.
	TokenId uint64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The name for the new bar.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The initial value of the bar.
	Value int32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// The maximum value of the bar.
	MaxValue int32 `protobuf:"varint,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	// The color for the new bar.
	Color         string `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBarRequest) Reset() {
	*x = CreateBarRequest{}
	mi := &file_pb_bar_bar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarRequest) ProtoMessage() {}

func (x *CreateBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarRequest.ProtoReflect.Descriptor instead.
func (*CreateBarRequest) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBarRequest) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *CreateBarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBarRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CreateBarRequest) GetMaxValue() int32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *CreateBarRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Response after creating a bar, containing the newly created bar object.
type CreateBarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete bar object as it was created.
	Bar           *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBarResponse) Reset() {
	*x = CreateBarResponse{}
	mi := &file_pb_bar_bar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBarResponse) ProtoMessage() {}

func (x *CreateBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBarResponse.ProtoReflect.Descriptor instead.
func (*CreateBarResponse) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBarResponse) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

// Request to edit an existing bar.
type EditBarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bar object containing the new data. Only fields specified in the mask will be updated.
	Bar *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	// A field mask to specify which fields of the bar should be updated.
	// This allows for partial updates (e.g., only changing the 'value').
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditBarRequest) Reset() {
	*x = EditBarRequest{}
	mi := &file_pb_bar_bar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBarRequest) ProtoMessage() {}

func (x *EditBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBarRequest.ProtoReflect.Descriptor instead.
func (*EditBarRequest) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{3}
}

func (x *EditBarRequest) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

func (x *EditBarRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// Response after editing a bar, containing the full updated bar object.
type EditBarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bar object with the applied updates.
	Bar           *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditBarResponse) Reset() {
	*x = EditBarResponse{}
	mi := &file_pb_bar_bar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditBarResponse) ProtoMessage() {}

func (x *EditBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditBarResponse.ProtoReflect.Descriptor instead.
func (*EditBarResponse) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{4}
}

func (x *EditBarResponse) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

// Request to delete a bar.
type DeleteBarRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the bar to be deleted.
	BarId uint64 `protobuf:"varint,1,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	// The ID of the token the bar belongs to, for validation.
	TokenId       uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarRequest) Reset() {
	*x = DeleteBarRequest{}
	mi := &file_pb_bar_bar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarRequest) ProtoMessage() {}

func (x *DeleteBarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarRequest.ProtoReflect.Descriptor instead.
func (*DeleteBarRequest) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBarRequest) GetBarId() uint64 {
	if x != nil {
		return x.BarId
	}
	return 0
}

func (x *DeleteBarRequest) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

// Response after a delete operation.
type DeleteBarResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates whether the deletion was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// A status code or string for the operation's result (e.g., "SUCCESS", "NOT_FOUND").
	MessageStatus string `protobuf:"bytes,2,opt,name=message_status,json=messageStatus,proto3" json:"message_status,omitempty"`
	// A human-readable message describing the outcome.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBarResponse) Reset() {
	*x = DeleteBarResponse{}
	mi := &file_pb_bar_bar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBarResponse) ProtoMessage() {}

func (x *DeleteBarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBarResponse.ProtoReflect.Descriptor instead.
func (*DeleteBarResponse) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBarResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBarResponse) GetMessageStatus() string {
	if x != nil {
		return x.MessageStatus
	}
	return ""
}

func (x *DeleteBarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to get all bars for a token.
type GetBarForTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the token whose bars should be retrieved.
	TokenId       uint64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarForTokenRequest) Reset() {
	*x = GetBarForTokenRequest{}
	mi := &file_pb_bar_bar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarForTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarForTokenRequest) ProtoMessage() {}

func (x *GetBarForTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarForTokenRequest.ProtoReflect.Descriptor instead.
func (*GetBarForTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{7}
}

func (x *GetBarForTokenRequest) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

// Response containing a list of bars for a specific token.
type GetBarsForTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of all bars associated with the requested token.
	Bars          []*Bar `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBarsForTokenResponse) Reset() {
	*x = GetBarsForTokenResponse{}
	mi := &file_pb_bar_bar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBarsForTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarsForTokenResponse) ProtoMessage() {}

func (x *GetBarsForTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarsForTokenResponse.ProtoReflect.Descriptor instead.
func (*GetBarsForTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{8}
}

func (x *GetBarsForTokenResponse) GetBars() []*Bar {
	if x != nil {
		return x.Bars
	}
	return nil
}

// Event triggered when a bar's values (current or max) are updated.
type BarValuesUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bar with its updated values.
	Bar           *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarValuesUpdated) Reset() {
	*x = BarValuesUpdated{}
	mi := &file_pb_bar_bar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarValuesUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarValuesUpdated) ProtoMessage() {}

func (x *BarValuesUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarValuesUpdated.ProtoReflect.Descriptor instead.
func (*BarValuesUpdated) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{9}
}

func (x *BarValuesUpdated) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

// Event triggered when a new bar is created.
type BarCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created bar object.
	Bar           *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarCreated) Reset() {
	*x = BarCreated{}
	mi := &file_pb_bar_bar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarCreated) ProtoMessage() {}

func (x *BarCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarCreated.ProtoReflect.Descriptor instead.
func (*BarCreated) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{10}
}

func (x *BarCreated) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

// Event triggered when a bar is deleted.
type BarDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the bar that was deleted.
	BarId uint64 `protobuf:"varint,1,opt,name=bar_id,json=barId,proto3" json:"bar_id,omitempty"`
	// The ID of the token the bar belonged to.
	TokenId       uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarDeleted) Reset() {
	*x = BarDeleted{}
	mi := &file_pb_bar_bar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarDeleted) ProtoMessage() {}

func (x *BarDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarDeleted.ProtoReflect.Descriptor instead.
func (*BarDeleted) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{11}
}

func (x *BarDeleted) GetBarId() uint64 {
	if x != nil {
		return x.BarId
	}
	return 0
}

func (x *BarDeleted) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

// Event triggered for any general update to a bar's properties (e.g., name, color).
// Note: This could potentially overlap with BarValuesUpdated.
type BarUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bar with its updated data.
	Bar           *Bar `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarUpdated) Reset() {
	*x = BarUpdated{}
	mi := &file_pb_bar_bar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarUpdated) ProtoMessage() {}

func (x *BarUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bar_bar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarUpdated.ProtoReflect.Descriptor instead.
func (*BarUpdated) Descriptor() ([]byte, []int) {
	return file_pb_bar_bar_proto_rawDescGZIP(), []int{12}
}

func (x *BarUpdated) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

var File_pb_bar_bar_proto protoreflect.FileDescriptor

const file_pb_bar_bar_proto_rawDesc = "" +
	"\n" +
	"\x10pb/bar/bar.proto\x12\x03bar\x1a google/protobuf/field_mask.proto\"\x94\x01\n" +
	"\x03Bar\x12\x15\n" +
	"\x06bar_id\x18\x01 \x01(\x04R\x05barId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x05R\x05value\x12\x1b\n" +
	"\tmax_value\x18\x05 \x01(\x05R\bmaxValue\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"\x8a\x01\n" +
	"\x10CreateBarRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x04R\atokenId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\x05R\bmaxValue\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"/\n" +
	"\x11CreateBarResponse\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar\"\\\n" +
	"\x0eEditBarRequest\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"-\n" +
	"\x0fEditBarResponse\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar\"D\n" +
	"\x10DeleteBarRequest\x12\x15\n" +
	"\x06bar_id\x18\x01 \x01(\x04R\x05barId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\"n\n" +
	"\x11DeleteBarResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0emessage_status\x18\x02 \x01(\tR\rmessageStatus\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x15GetBarForTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x04R\atokenId\"7\n" +
	"\x17GetBarsForTokenResponse\x12\x1c\n" +
	"\x04bars\x18\x01 \x03(\v2\b.bar.BarR\x04bars\".\n" +
	"\x10BarValuesUpdated\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar\"(\n" +
	"\n" +
	"BarCreated\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar\">\n" +
	"\n" +
	"BarDeleted\x12\x15\n" +
	"\x06bar_id\x18\x01 \x01(\x04R\x05barId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\"(\n" +
	"\n" +
	"BarUpdated\x12\x1a\n" +
	"\x03bar\x18\x01 \x01(\v2\b.bar.BarR\x03bar2\x87\x02\n" +
	"\n" +
	"BarService\x12:\n" +
	"\tCreateBar\x12\x15.bar.CreateBarRequest\x1a\x16.bar.CreateBarResponse\x124\n" +
	"\aEditBar\x12\x13.bar.EditBarRequest\x1a\x14.bar.EditBarResponse\x12:\n" +
	"\tDeleteBar\x12\x15.bar.DeleteBarRequest\x1a\x16.bar.DeleteBarResponse\x12K\n" +
	"\x0fGetBarsForToken\x12\x1a.bar.GetBarForTokenRequest\x1a\x1c.bar.GetBarsForTokenResponseB8Z6github.com/GarotoCowboy/vttProject/api/grpc/pb/bar;barb\x06proto3"

var (
	file_pb_bar_bar_proto_rawDescOnce sync.Once
	file_pb_bar_bar_proto_rawDescData []byte
)

func file_pb_bar_bar_proto_rawDescGZIP() []byte {
	file_pb_bar_bar_proto_rawDescOnce.Do(func() {
		file_pb_bar_bar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_bar_bar_proto_rawDesc), len(file_pb_bar_bar_proto_rawDesc)))
	})
	return file_pb_bar_bar_proto_rawDescData
}

var file_pb_bar_bar_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_bar_bar_proto_goTypes = []any{
	(*Bar)(nil),                     // 0: bar.Bar
	(*CreateBarRequest)(nil),        // 1: bar.CreateBarRequest
	(*CreateBarResponse)(nil),       // 2: bar.CreateBarResponse
	(*EditBarRequest)(nil),          // 3: bar.EditBarRequest
	(*EditBarResponse)(nil),         // 4: bar.EditBarResponse
	(*DeleteBarRequest)(nil),        // 5: bar.DeleteBarRequest
	(*DeleteBarResponse)(nil),       // 6: bar.DeleteBarResponse
	(*GetBarForTokenRequest)(nil),   // 7: bar.GetBarForTokenRequest
	(*GetBarsForTokenResponse)(nil), // 8: bar.GetBarsForTokenResponse
	(*BarValuesUpdated)(nil),        // 9: bar.BarValuesUpdated
	(*BarCreated)(nil),              // 10: bar.BarCreated
	(*BarDeleted)(nil),              // 11: bar.BarDeleted
	(*BarUpdated)(nil),              // 12: bar.BarUpdated
	(*fieldmaskpb.FieldMask)(nil),   // 13: google.protobuf.FieldMask
}
var file_pb_bar_bar_proto_depIdxs = []int32{
	0,  // 0: bar.CreateBarResponse.bar:type_name -> bar.Bar
	0,  // 1: bar.EditBarRequest.bar:type_name -> bar.Bar
	13, // 2: bar.EditBarRequest.mask:type_name -> google.protobuf.FieldMask
	0,  // 3: bar.EditBarResponse.bar:type_name -> bar.Bar
	0,  // 4: bar.GetBarsForTokenResponse.bars:type_name -> bar.Bar
	0,  // 5: bar.BarValuesUpdated.bar:type_name -> bar.Bar
	0,  // 6: bar.BarCreated.bar:type_name -> bar.Bar
	0,  // 7: bar.BarUpdated.bar:type_name -> bar.Bar
	1,  // 8: bar.BarService.CreateBar:input_type -> bar.CreateBarRequest
	3,  // 9: bar.BarService.EditBar:input_type -> bar.EditBarRequest
	5,  // 10: bar.BarService.DeleteBar:input_type -> bar.DeleteBarRequest
	7,  // 11: bar.BarService.GetBarsForToken:input_type -> bar.GetBarForTokenRequest
	2,  // 12: bar.BarService.CreateBar:output_type -> bar.CreateBarResponse
	4,  // 13: bar.BarService.EditBar:output_type -> bar.EditBarResponse
	6,  // 14: bar.BarService.DeleteBar:output_type -> bar.DeleteBarResponse
	8,  // 15: bar.BarService.GetBarsForToken:output_type -> bar.GetBarsForTokenResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_bar_bar_proto_init() }
func file_pb_bar_bar_proto_init() {
	if File_pb_bar_bar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_bar_bar_proto_rawDesc), len(file_pb_bar_bar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_bar_bar_proto_goTypes,
		DependencyIndexes: file_pb_bar_bar_proto_depIdxs,
		MessageInfos:      file_pb_bar_bar_proto_msgTypes,
	}.Build()
	File_pb_bar_bar_proto = out.File
	file_pb_bar_bar_proto_goTypes = nil
	file_pb_bar_bar_proto_depIdxs = nil
}
