// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/bar/bar.proto

package bar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BarService_CreateBar_FullMethodName       = "/bar.BarService/CreateBar"
	BarService_EditBar_FullMethodName         = "/bar.BarService/EditBar"
	BarService_DeleteBar_FullMethodName       = "/bar.BarService/DeleteBar"
	BarService_GetBarsForToken_FullMethodName = "/bar.BarService/GetBarsForToken"
)

// BarServiceClient is the client API for BarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `BarService` manages operations for "bars" (e.g., health, mana) associated with tokens.
type BarServiceClient interface {
	// Creates a new bar for a specific token.
	CreateBar(ctx context.Context, in *CreateBarRequest, opts ...grpc.CallOption) (*CreateBarResponse, error)
	// Edits an existing bar using a field mask for partial updates.
	EditBar(ctx context.Context, in *EditBarRequest, opts ...grpc.CallOption) (*EditBarResponse, error)
	// Deletes a bar.
	DeleteBar(ctx context.Context, in *DeleteBarRequest, opts ...grpc.CallOption) (*DeleteBarResponse, error)
	// Retrieves all bars associated with a given token.
	GetBarsForToken(ctx context.Context, in *GetBarForTokenRequest, opts ...grpc.CallOption) (*GetBarsForTokenResponse, error)
}

type barServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBarServiceClient(cc grpc.ClientConnInterface) BarServiceClient {
	return &barServiceClient{cc}
}

func (c *barServiceClient) CreateBar(ctx context.Context, in *CreateBarRequest, opts ...grpc.CallOption) (*CreateBarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBarResponse)
	err := c.cc.Invoke(ctx, BarService_CreateBar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barServiceClient) EditBar(ctx context.Context, in *EditBarRequest, opts ...grpc.CallOption) (*EditBarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditBarResponse)
	err := c.cc.Invoke(ctx, BarService_EditBar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barServiceClient) DeleteBar(ctx context.Context, in *DeleteBarRequest, opts ...grpc.CallOption) (*DeleteBarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBarResponse)
	err := c.cc.Invoke(ctx, BarService_DeleteBar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barServiceClient) GetBarsForToken(ctx context.Context, in *GetBarForTokenRequest, opts ...grpc.CallOption) (*GetBarsForTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBarsForTokenResponse)
	err := c.cc.Invoke(ctx, BarService_GetBarsForToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BarServiceServer is the server API for BarService service.
// All implementations must embed UnimplementedBarServiceServer
// for forward compatibility.
//
// The `BarService` manages operations for "bars" (e.g., health, mana) associated with tokens.
type BarServiceServer interface {
	// Creates a new bar for a specific token.
	CreateBar(context.Context, *CreateBarRequest) (*CreateBarResponse, error)
	// Edits an existing bar using a field mask for partial updates.
	EditBar(context.Context, *EditBarRequest) (*EditBarResponse, error)
	// Deletes a bar.
	DeleteBar(context.Context, *DeleteBarRequest) (*DeleteBarResponse, error)
	// Retrieves all bars associated with a given token.
	GetBarsForToken(context.Context, *GetBarForTokenRequest) (*GetBarsForTokenResponse, error)
	mustEmbedUnimplementedBarServiceServer()
}

// UnimplementedBarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBarServiceServer struct{}

func (UnimplementedBarServiceServer) CreateBar(context.Context, *CreateBarRequest) (*CreateBarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBar not implemented")
}
func (UnimplementedBarServiceServer) EditBar(context.Context, *EditBarRequest) (*EditBarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBar not implemented")
}
func (UnimplementedBarServiceServer) DeleteBar(context.Context, *DeleteBarRequest) (*DeleteBarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBar not implemented")
}
func (UnimplementedBarServiceServer) GetBarsForToken(context.Context, *GetBarForTokenRequest) (*GetBarsForTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBarsForToken not implemented")
}
func (UnimplementedBarServiceServer) mustEmbedUnimplementedBarServiceServer() {}
func (UnimplementedBarServiceServer) testEmbeddedByValue()                    {}

// UnsafeBarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarServiceServer will
// result in compilation errors.
type UnsafeBarServiceServer interface {
	mustEmbedUnimplementedBarServiceServer()
}

func RegisterBarServiceServer(s grpc.ServiceRegistrar, srv BarServiceServer) {
	// If the following call pancis, it indicates UnimplementedBarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BarService_ServiceDesc, srv)
}

func _BarService_CreateBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServiceServer).CreateBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarService_CreateBar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServiceServer).CreateBar(ctx, req.(*CreateBarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarService_EditBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditBarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServiceServer).EditBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarService_EditBar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServiceServer).EditBar(ctx, req.(*EditBarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarService_DeleteBar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServiceServer).DeleteBar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarService_DeleteBar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServiceServer).DeleteBar(ctx, req.(*DeleteBarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarService_GetBarsForToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBarForTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServiceServer).GetBarsForToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarService_GetBarsForToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServiceServer).GetBarsForToken(ctx, req.(*GetBarForTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BarService_ServiceDesc is the grpc.ServiceDesc for BarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bar.BarService",
	HandlerType: (*BarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBar",
			Handler:    _BarService_CreateBar_Handler,
		},
		{
			MethodName: "EditBar",
			Handler:    _BarService_EditBar_Handler,
		},
		{
			MethodName: "DeleteBar",
			Handler:    _BarService_DeleteBar_Handler,
		},
		{
			MethodName: "GetBarsForToken",
			Handler:    _BarService_GetBarsForToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/bar/bar.proto",
}
