// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/tableUser/tableUser.proto

package tableUser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TableUserService_PromoteOrDemoteUser_FullMethodName = "/tableUser.TableUserService/PromoteOrDemoteUser"
)

// TableUserServiceClient is the client API for TableUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TableUserServiceClient interface {
	PromoteOrDemoteUser(ctx context.Context, in *PromoteOrDemoteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type tableUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableUserServiceClient(cc grpc.ClientConnInterface) TableUserServiceClient {
	return &tableUserServiceClient{cc}
}

func (c *tableUserServiceClient) PromoteOrDemoteUser(ctx context.Context, in *PromoteOrDemoteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TableUserService_PromoteOrDemoteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableUserServiceServer is the server API for TableUserService service.
// All implementations must embed UnimplementedTableUserServiceServer
// for forward compatibility.
type TableUserServiceServer interface {
	PromoteOrDemoteUser(context.Context, *PromoteOrDemoteUserRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedTableUserServiceServer()
}

// UnimplementedTableUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTableUserServiceServer struct{}

func (UnimplementedTableUserServiceServer) PromoteOrDemoteUser(context.Context, *PromoteOrDemoteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteOrDemoteUser not implemented")
}
func (UnimplementedTableUserServiceServer) mustEmbedUnimplementedTableUserServiceServer() {}
func (UnimplementedTableUserServiceServer) testEmbeddedByValue()                          {}

// UnsafeTableUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableUserServiceServer will
// result in compilation errors.
type UnsafeTableUserServiceServer interface {
	mustEmbedUnimplementedTableUserServiceServer()
}

func RegisterTableUserServiceServer(s grpc.ServiceRegistrar, srv TableUserServiceServer) {
	// If the following call pancis, it indicates UnimplementedTableUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TableUserService_ServiceDesc, srv)
}

func _TableUserService_PromoteOrDemoteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteOrDemoteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableUserServiceServer).PromoteOrDemoteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableUserService_PromoteOrDemoteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableUserServiceServer).PromoteOrDemoteUser(ctx, req.(*PromoteOrDemoteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TableUserService_ServiceDesc is the grpc.ServiceDesc for TableUserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableUserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tableUser.TableUserService",
	HandlerType: (*TableUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PromoteOrDemoteUser",
			Handler:    _TableUserService_PromoteOrDemoteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/tableUser/tableUser.proto",
}
