// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/tableUser/tableUser.proto

package tableUser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_UNSPECIFIED Role = 0
	Role_PLAYER      Role = 1
	Role_MASTER      Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PLAYER",
		2: "MASTER",
	}
	Role_value = map[string]int32{
		"UNSPECIFIED": 0,
		"PLAYER":      1,
		"MASTER":      2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_tableUser_tableUser_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_pb_tableUser_tableUser_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_pb_tableUser_tableUser_proto_rawDescGZIP(), []int{0}
}

type TableUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       uint64                 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=tableUser.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableUser) Reset() {
	*x = TableUser{}
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableUser) ProtoMessage() {}

func (x *TableUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableUser.ProtoReflect.Descriptor instead.
func (*TableUser) Descriptor() ([]byte, []int) {
	return file_pb_tableUser_tableUser_proto_rawDescGZIP(), []int{0}
}

func (x *TableUser) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TableUser) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TableUser) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_UNSPECIFIED
}

type PromoteOrDemoteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableId       uint64                 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=tableUser.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteOrDemoteUserRequest) Reset() {
	*x = PromoteOrDemoteUserRequest{}
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteOrDemoteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteOrDemoteUserRequest) ProtoMessage() {}

func (x *PromoteOrDemoteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteOrDemoteUserRequest.ProtoReflect.Descriptor instead.
func (*PromoteOrDemoteUserRequest) Descriptor() ([]byte, []int) {
	return file_pb_tableUser_tableUser_proto_rawDescGZIP(), []int{1}
}

func (x *PromoteOrDemoteUserRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *PromoteOrDemoteUserRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PromoteOrDemoteUserRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_UNSPECIFIED
}

type PromotedOrDemotedUserEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableUser     *TableUser             `protobuf:"bytes,1,opt,name=tableUser,proto3" json:"tableUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotedOrDemotedUserEvent) Reset() {
	*x = PromotedOrDemotedUserEvent{}
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotedOrDemotedUserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotedOrDemotedUserEvent) ProtoMessage() {}

func (x *PromotedOrDemotedUserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tableUser_tableUser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotedOrDemotedUserEvent.ProtoReflect.Descriptor instead.
func (*PromotedOrDemotedUserEvent) Descriptor() ([]byte, []int) {
	return file_pb_tableUser_tableUser_proto_rawDescGZIP(), []int{2}
}

func (x *PromotedOrDemotedUserEvent) GetTableUser() *TableUser {
	if x != nil {
		return x.TableUser
	}
	return nil
}

var File_pb_tableUser_tableUser_proto protoreflect.FileDescriptor

const file_pb_tableUser_tableUser_proto_rawDesc = "" +
	"\n" +
	"\x1cpb/tableUser/tableUser.proto\x12\ttableUser\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\tTableUser\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12#\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0f.tableUser.RoleR\x04role\"u\n" +
	"\x1aPromoteOrDemoteUserRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12#\n" +
	"\x04role\x18\x03 \x01(\x0e2\x0f.tableUser.RoleR\x04role\"P\n" +
	"\x1aPromotedOrDemotedUserEvent\x122\n" +
	"\ttableUser\x18\x01 \x01(\v2\x14.tableUser.TableUserR\ttableUser*/\n" +
	"\x04Role\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06PLAYER\x10\x01\x12\n" +
	"\n" +
	"\x06MASTER\x10\x022h\n" +
	"\x10TableUserService\x12T\n" +
	"\x13PromoteOrDemoteUser\x12%.tableUser.PromoteOrDemoteUserRequest\x1a\x16.google.protobuf.EmptyBDZBgithub.com/GarotoCowboy/vttProject/api/grpc/pb/tableUser;tableUserb\x06proto3"

var (
	file_pb_tableUser_tableUser_proto_rawDescOnce sync.Once
	file_pb_tableUser_tableUser_proto_rawDescData []byte
)

func file_pb_tableUser_tableUser_proto_rawDescGZIP() []byte {
	file_pb_tableUser_tableUser_proto_rawDescOnce.Do(func() {
		file_pb_tableUser_tableUser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_tableUser_tableUser_proto_rawDesc), len(file_pb_tableUser_tableUser_proto_rawDesc)))
	})
	return file_pb_tableUser_tableUser_proto_rawDescData
}

var file_pb_tableUser_tableUser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_tableUser_tableUser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_tableUser_tableUser_proto_goTypes = []any{
	(Role)(0),                          // 0: tableUser.Role
	(*TableUser)(nil),                  // 1: tableUser.TableUser
	(*PromoteOrDemoteUserRequest)(nil), // 2: tableUser.PromoteOrDemoteUserRequest
	(*PromotedOrDemotedUserEvent)(nil), // 3: tableUser.PromotedOrDemotedUserEvent
	(*emptypb.Empty)(nil),              // 4: google.protobuf.Empty
}
var file_pb_tableUser_tableUser_proto_depIdxs = []int32{
	0, // 0: tableUser.TableUser.role:type_name -> tableUser.Role
	0, // 1: tableUser.PromoteOrDemoteUserRequest.role:type_name -> tableUser.Role
	1, // 2: tableUser.PromotedOrDemotedUserEvent.tableUser:type_name -> tableUser.TableUser
	2, // 3: tableUser.TableUserService.PromoteOrDemoteUser:input_type -> tableUser.PromoteOrDemoteUserRequest
	4, // 4: tableUser.TableUserService.PromoteOrDemoteUser:output_type -> google.protobuf.Empty
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_tableUser_tableUser_proto_init() }
func file_pb_tableUser_tableUser_proto_init() {
	if File_pb_tableUser_tableUser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_tableUser_tableUser_proto_rawDesc), len(file_pb_tableUser_tableUser_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_tableUser_tableUser_proto_goTypes,
		DependencyIndexes: file_pb_tableUser_tableUser_proto_depIdxs,
		EnumInfos:         file_pb_tableUser_tableUser_proto_enumTypes,
		MessageInfos:      file_pb_tableUser_tableUser_proto_msgTypes,
	}.Build()
	File_pb_tableUser_tableUser_proto = out.File
	file_pb_tableUser_tableUser_proto_goTypes = nil
	file_pb_tableUser_tableUser_proto_depIdxs = nil
}
