// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/token/token.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a token template in the library.
type Token struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the token template.
	TokenId uint64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The ID of the table this token template belongs to.
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The name of the token (e.g., "Goblin Archer", "Player Character").
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The URL of the image used for this token.
	ImageUrl      string `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_pb_token_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{0}
}

func (x *Token) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *Token) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Token) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Token) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Request to create a new token template.
type CreateTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the table where this token will be created.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The name for the new token.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The image URL for the new token.
	ImageUrl      string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_pb_token_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTokenRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CreateTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

// Response after creating a token, containing the new token object.
type CreateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete token object as it was created.
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_pb_token_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Request to edit an existing token template.
type EditTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token object with the new data. `token_id` must be specified.
	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// A field mask to specify which fields should be updated (e.g., "name", "image_url").
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTokenRequest) Reset() {
	*x = EditTokenRequest{}
	mi := &file_pb_token_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTokenRequest) ProtoMessage() {}

func (x *EditTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTokenRequest.ProtoReflect.Descriptor instead.
func (*EditTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{3}
}

func (x *EditTokenRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *EditTokenRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// Response after editing a token, containing the updated token object.
type EditTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token object with the applied updates.
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditTokenResponse) Reset() {
	*x = EditTokenResponse{}
	mi := &file_pb_token_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTokenResponse) ProtoMessage() {}

func (x *EditTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTokenResponse.ProtoReflect.Descriptor instead.
func (*EditTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{4}
}

func (x *EditTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Request to delete a token template.
type DeleteTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the token to be deleted.
	TokenId uint64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The ID of the table the token belongs to, for validation.
	TableId       uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenRequest) Reset() {
	*x = DeleteTokenRequest{}
	mi := &file_pb_token_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenRequest) ProtoMessage() {}

func (x *DeleteTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenRequest.ProtoReflect.Descriptor instead.
func (*DeleteTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTokenRequest) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *DeleteTokenRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// Response for a delete operation.
type DeleteTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An empty message indicates success.
	Empty         *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTokenResponse) Reset() {
	*x = DeleteTokenResponse{}
	mi := &file_pb_token_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTokenResponse) ProtoMessage() {}

func (x *DeleteTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTokenResponse.ProtoReflect.Descriptor instead.
func (*DeleteTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTokenResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

// Request to list all token templates for a table.
type ListTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the table whose tokens are to be listed.
	TableId       uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenRequest) Reset() {
	*x = ListTokenRequest{}
	mi := &file_pb_token_token_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenRequest) ProtoMessage() {}

func (x *ListTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenRequest.ProtoReflect.Descriptor instead.
func (*ListTokenRequest) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{7}
}

func (x *ListTokenRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// Response containing a list of all token templates in a table's library.
type ListTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of token objects.
	Tokens        []*Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenResponse) Reset() {
	*x = ListTokenResponse{}
	mi := &file_pb_token_token_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenResponse) ProtoMessage() {}

func (x *ListTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenResponse.ProtoReflect.Descriptor instead.
func (*ListTokenResponse) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{8}
}

func (x *ListTokenResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Event triggered when a new token template is created.
type TokenCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created token template.
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCreated) Reset() {
	*x = TokenCreated{}
	mi := &file_pb_token_token_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCreated) ProtoMessage() {}

func (x *TokenCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCreated.ProtoReflect.Descriptor instead.
func (*TokenCreated) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{9}
}

func (x *TokenCreated) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Event triggered when a token template's properties are updated.
type TokenUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token template with its updated data.
	Token         *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUpdated) Reset() {
	*x = TokenUpdated{}
	mi := &file_pb_token_token_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUpdated) ProtoMessage() {}

func (x *TokenUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUpdated.ProtoReflect.Descriptor instead.
func (*TokenUpdated) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{10}
}

func (x *TokenUpdated) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

// Event triggered when a token template is deleted.
type TokenDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the table from which the token was deleted.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The ID of the token template that was deleted.
	TokenId       uint64 `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenDeleted) Reset() {
	*x = TokenDeleted{}
	mi := &file_pb_token_token_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenDeleted) ProtoMessage() {}

func (x *TokenDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenDeleted.ProtoReflect.Descriptor instead.
func (*TokenDeleted) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{11}
}

func (x *TokenDeleted) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *TokenDeleted) GetTokenId() uint64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

// NOTE: This event is unconventional. Typically, events broadcast a single action (create, update, delete).
// An event that sends a whole list might be intended for initial state synchronization.
type TokenListed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of tokens, possibly for syncing the entire library state at once.
	Token         []*Token `protobuf:"bytes,1,rep,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenListed) Reset() {
	*x = TokenListed{}
	mi := &file_pb_token_token_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenListed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenListed) ProtoMessage() {}

func (x *TokenListed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_token_token_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenListed.ProtoReflect.Descriptor instead.
func (*TokenListed) Descriptor() ([]byte, []int) {
	return file_pb_token_token_proto_rawDescGZIP(), []int{12}
}

func (x *TokenListed) GetToken() []*Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_pb_token_token_proto protoreflect.FileDescriptor

const file_pb_token_token_proto_rawDesc = "" +
	"\n" +
	"\x14pb/token/token.proto\x12\x05token\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\"n\n" +
	"\x05Token\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x04R\atokenId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"`\n" +
	"\x12CreateTokenRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\"9\n" +
	"\x13CreateTokenResponse\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.token.TokenR\x05token\"f\n" +
	"\x10EditTokenRequest\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.token.TokenR\x05token\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"7\n" +
	"\x11EditTokenResponse\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.token.TokenR\x05token\"J\n" +
	"\x12DeleteTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\x04R\atokenId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\"C\n" +
	"\x13DeleteTokenResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"-\n" +
	"\x10ListTokenRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\"9\n" +
	"\x11ListTokenResponse\x12$\n" +
	"\x06tokens\x18\x01 \x03(\v2\f.token.TokenR\x06tokens\"2\n" +
	"\fTokenCreated\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.token.TokenR\x05token\"2\n" +
	"\fTokenUpdated\x12\"\n" +
	"\x05token\x18\x01 \x01(\v2\f.token.TokenR\x05token\"D\n" +
	"\fTokenDeleted\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\x04R\atokenId\"1\n" +
	"\vtokenListed\x12\"\n" +
	"\x05token\x18\x01 \x03(\v2\f.token.TokenR\x05token2\xa4\x02\n" +
	"\fTokenService\x12D\n" +
	"\vCreateToken\x12\x19.token.CreateTokenRequest\x1a\x1a.token.CreateTokenResponse\x12>\n" +
	"\tEditToken\x12\x17.token.EditTokenRequest\x1a\x18.token.EditTokenResponse\x12D\n" +
	"\vDeleteToken\x12\x19.token.DeleteTokenRequest\x1a\x1a.token.DeleteTokenResponse\x12H\n" +
	"\x13ListAllTokenInTable\x12\x17.token.ListTokenRequest\x1a\x18.token.ListTokenResponseB<Z:github.com/GarotoCowboy/vttProject/api/grpc/pb/token;tokenb\x06proto3"

var (
	file_pb_token_token_proto_rawDescOnce sync.Once
	file_pb_token_token_proto_rawDescData []byte
)

func file_pb_token_token_proto_rawDescGZIP() []byte {
	file_pb_token_token_proto_rawDescOnce.Do(func() {
		file_pb_token_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_token_token_proto_rawDesc), len(file_pb_token_token_proto_rawDesc)))
	})
	return file_pb_token_token_proto_rawDescData
}

var file_pb_token_token_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_token_token_proto_goTypes = []any{
	(*Token)(nil),                 // 0: token.Token
	(*CreateTokenRequest)(nil),    // 1: token.CreateTokenRequest
	(*CreateTokenResponse)(nil),   // 2: token.CreateTokenResponse
	(*EditTokenRequest)(nil),      // 3: token.EditTokenRequest
	(*EditTokenResponse)(nil),     // 4: token.EditTokenResponse
	(*DeleteTokenRequest)(nil),    // 5: token.DeleteTokenRequest
	(*DeleteTokenResponse)(nil),   // 6: token.DeleteTokenResponse
	(*ListTokenRequest)(nil),      // 7: token.ListTokenRequest
	(*ListTokenResponse)(nil),     // 8: token.ListTokenResponse
	(*TokenCreated)(nil),          // 9: token.TokenCreated
	(*TokenUpdated)(nil),          // 10: token.TokenUpdated
	(*TokenDeleted)(nil),          // 11: token.TokenDeleted
	(*TokenListed)(nil),           // 12: token.tokenListed
	(*fieldmaskpb.FieldMask)(nil), // 13: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_pb_token_token_proto_depIdxs = []int32{
	0,  // 0: token.CreateTokenResponse.token:type_name -> token.Token
	0,  // 1: token.EditTokenRequest.token:type_name -> token.Token
	13, // 2: token.EditTokenRequest.mask:type_name -> google.protobuf.FieldMask
	0,  // 3: token.EditTokenResponse.token:type_name -> token.Token
	14, // 4: token.DeleteTokenResponse.empty:type_name -> google.protobuf.Empty
	0,  // 5: token.ListTokenResponse.tokens:type_name -> token.Token
	0,  // 6: token.TokenCreated.token:type_name -> token.Token
	0,  // 7: token.TokenUpdated.token:type_name -> token.Token
	0,  // 8: token.tokenListed.token:type_name -> token.Token
	1,  // 9: token.TokenService.CreateToken:input_type -> token.CreateTokenRequest
	3,  // 10: token.TokenService.EditToken:input_type -> token.EditTokenRequest
	5,  // 11: token.TokenService.DeleteToken:input_type -> token.DeleteTokenRequest
	7,  // 12: token.TokenService.ListAllTokenInTable:input_type -> token.ListTokenRequest
	2,  // 13: token.TokenService.CreateToken:output_type -> token.CreateTokenResponse
	4,  // 14: token.TokenService.EditToken:output_type -> token.EditTokenResponse
	6,  // 15: token.TokenService.DeleteToken:output_type -> token.DeleteTokenResponse
	8,  // 16: token.TokenService.ListAllTokenInTable:output_type -> token.ListTokenResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pb_token_token_proto_init() }
func file_pb_token_token_proto_init() {
	if File_pb_token_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_token_token_proto_rawDesc), len(file_pb_token_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_token_token_proto_goTypes,
		DependencyIndexes: file_pb_token_token_proto_depIdxs,
		MessageInfos:      file_pb_token_token_proto_msgTypes,
	}.Build()
	File_pb_token_token_proto = out.File
	file_pb_token_token_proto_goTypes = nil
	file_pb_token_token_proto_depIdxs = nil
}
