// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/scene/scene.proto

package scene

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines the type of grid for a scene.
type GridType int32

const (
	GridType_SQUARE  GridType = 0 // A standard square grid.
	GridType_HEXAGON GridType = 1 // A hexagonal grid.
)

// Enum value maps for GridType.
var (
	GridType_name = map[int32]string{
		0: "SQUARE",
		1: "HEXAGON",
	}
	GridType_value = map[string]int32{
		"SQUARE":  0,
		"HEXAGON": 1,
	}
)

func (x GridType) Enum() *GridType {
	p := new(GridType)
	*p = x
	return p
}

func (x GridType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GridType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_scene_scene_proto_enumTypes[0].Descriptor()
}

func (GridType) Type() protoreflect.EnumType {
	return &file_pb_scene_scene_proto_enumTypes[0]
}

func (x GridType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GridType.Descriptor instead.
func (GridType) EnumDescriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{0}
}

// Represents a single scene and its configuration.
type Scene struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier for the scene.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the table this scene belongs to.
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The user-defined name of the scene.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The width of the scene in grid units.
	Width uint32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	// The height of the scene in grid units.
	Height uint32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	// The URL or path to the background image for the scene.
	BackgroundImagePath string `protobuf:"bytes,6,opt,name=background_image_path,json=backgroundImagePath,proto3" json:"background_image_path,omitempty"`
	// A wrapper that indicates if the scene is visible to players. Allows distinguishing between 'false' and 'not set'.
	IsVisible *wrapperspb.BoolValue `protobuf:"bytes,7,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	// The background color of the scene, e.g., a hex code like "#000000". Used if no image is present.
	BackgroundColor string `protobuf:"bytes,8,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	// The distance each grid cell represents (e.g., 5 for 5 feet).
	GridCellDistance uint64 `protobuf:"varint,9,opt,name=grid_cell_distance,json=gridCellDistance,proto3" json:"grid_cell_distance,omitempty"`
	// The type of grid used on the scene (Square or Hexagon).
	GridType GridType `protobuf:"varint,10,opt,name=grid_type,json=gridType,proto3,enum=scene.GridType" json:"grid_type,omitempty"`
	// Timestamp of when the scene was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of the last update to the scene.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scene) Reset() {
	*x = Scene{}
	mi := &file_pb_scene_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scene) ProtoMessage() {}

func (x *Scene) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scene.ProtoReflect.Descriptor instead.
func (*Scene) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{0}
}

func (x *Scene) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *Scene) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *Scene) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scene) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Scene) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Scene) GetBackgroundImagePath() string {
	if x != nil {
		return x.BackgroundImagePath
	}
	return ""
}

func (x *Scene) GetIsVisible() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsVisible
	}
	return nil
}

func (x *Scene) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *Scene) GetGridCellDistance() uint64 {
	if x != nil {
		return x.GridCellDistance
	}
	return 0
}

func (x *Scene) GetGridType() GridType {
	if x != nil {
		return x.GridType
	}
	return GridType_SQUARE
}

func (x *Scene) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Scene) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request to create a new scene.
type CreateSceneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the table to add the scene to.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The name for the new scene.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The initial width of the scene.
	Width uint32 `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	// The initial height of the scene.
	Height uint32 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	// The initial background image path.
	BackgroundImagePath string `protobuf:"bytes,5,opt,name=background_image_path,json=backgroundImagePath,proto3" json:"background_image_path,omitempty"`
	// The initial background color.
	BackgroundColor string `protobuf:"bytes,6,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	// The initial grid cell distance.
	GridCellDistance uint64 `protobuf:"varint,7,opt,name=grid_cell_distance,json=gridCellDistance,proto3" json:"grid_cell_distance,omitempty"`
	// The type of grid for the scene.
	GridType      GridType `protobuf:"varint,8,opt,name=grid_type,json=gridType,proto3,enum=scene.GridType" json:"grid_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSceneRequest) Reset() {
	*x = CreateSceneRequest{}
	mi := &file_pb_scene_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneRequest) ProtoMessage() {}

func (x *CreateSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneRequest.ProtoReflect.Descriptor instead.
func (*CreateSceneRequest) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSceneRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CreateSceneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSceneRequest) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateSceneRequest) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateSceneRequest) GetBackgroundImagePath() string {
	if x != nil {
		return x.BackgroundImagePath
	}
	return ""
}

func (x *CreateSceneRequest) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *CreateSceneRequest) GetGridCellDistance() uint64 {
	if x != nil {
		return x.GridCellDistance
	}
	return 0
}

func (x *CreateSceneRequest) GetGridType() GridType {
	if x != nil {
		return x.GridType
	}
	return GridType_SQUARE
}

// Response after creating a scene, containing the new scene object.
type CreateSceneResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The complete scene object as it was created.
	Scene         *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSceneResponse) Reset() {
	*x = CreateSceneResponse{}
	mi := &file_pb_scene_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSceneResponse) ProtoMessage() {}

func (x *CreateSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSceneResponse.ProtoReflect.Descriptor instead.
func (*CreateSceneResponse) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// Request to edit an existing scene.
type EditSceneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scene object containing the new data. `scene_id` must be specified.
	Scene *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	// A field mask to specify which fields of the scene should be updated.
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSceneRequest) Reset() {
	*x = EditSceneRequest{}
	mi := &file_pb_scene_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSceneRequest) ProtoMessage() {}

func (x *EditSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSceneRequest.ProtoReflect.Descriptor instead.
func (*EditSceneRequest) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{3}
}

func (x *EditSceneRequest) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

func (x *EditSceneRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

// Response after editing a scene, containing the full updated scene object.
type EditSceneResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scene object with the applied updates.
	Scene         *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditSceneResponse) Reset() {
	*x = EditSceneResponse{}
	mi := &file_pb_scene_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditSceneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditSceneResponse) ProtoMessage() {}

func (x *EditSceneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditSceneResponse.ProtoReflect.Descriptor instead.
func (*EditSceneResponse) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{4}
}

func (x *EditSceneResponse) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// Request to delete a scene.
type DeleteSceneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the scene to be deleted.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the table the scene belongs to, for validation.
	TableId       uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSceneRequest) Reset() {
	*x = DeleteSceneRequest{}
	mi := &file_pb_scene_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSceneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSceneRequest) ProtoMessage() {}

func (x *DeleteSceneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSceneRequest.ProtoReflect.Descriptor instead.
func (*DeleteSceneRequest) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSceneRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *DeleteSceneRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

// Request to list all scenes for a table.
type ListAllScenesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the table whose scenes should be retrieved.
	TableId uint64 `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The maximum number of scenes to return per page.
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A token for retrieving a specific page of results.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllScenesRequest) Reset() {
	*x = ListAllScenesRequest{}
	mi := &file_pb_scene_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllScenesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllScenesRequest) ProtoMessage() {}

func (x *ListAllScenesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllScenesRequest.ProtoReflect.Descriptor instead.
func (*ListAllScenesRequest) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{6}
}

func (x *ListAllScenesRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *ListAllScenesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAllScenesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response containing a paginated list of scenes.
type ListAllScenesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of scenes for the requested page.
	Scenes []*Scene `protobuf:"bytes,1,rep,name=scenes,proto3" json:"scenes,omitempty"`
	// A token to be used in the next request to fetch the subsequent page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllScenesResponse) Reset() {
	*x = ListAllScenesResponse{}
	mi := &file_pb_scene_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllScenesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllScenesResponse) ProtoMessage() {}

func (x *ListAllScenesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllScenesResponse.ProtoReflect.Descriptor instead.
func (*ListAllScenesResponse) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllScenesResponse) GetScenes() []*Scene {
	if x != nil {
		return x.Scenes
	}
	return nil
}

func (x *ListAllScenesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Event triggered when a new scene is created.
type SceneCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created scene object.
	Scene         *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneCreated) Reset() {
	*x = SceneCreated{}
	mi := &file_pb_scene_scene_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneCreated) ProtoMessage() {}

func (x *SceneCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneCreated.ProtoReflect.Descriptor instead.
func (*SceneCreated) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{8}
}

func (x *SceneCreated) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// Event triggered when a scene's properties are updated.
type SceneUpdated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scene object with its updated data.
	Scene         *Scene `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneUpdated) Reset() {
	*x = SceneUpdated{}
	mi := &file_pb_scene_scene_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneUpdated) ProtoMessage() {}

func (x *SceneUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneUpdated.ProtoReflect.Descriptor instead.
func (*SceneUpdated) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{9}
}

func (x *SceneUpdated) GetScene() *Scene {
	if x != nil {
		return x.Scene
	}
	return nil
}

// Event triggered when a scene is deleted.
type SceneDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene that was deleted.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the table the scene belonged to.
	TableId       uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SceneDeleted) Reset() {
	*x = SceneDeleted{}
	mi := &file_pb_scene_scene_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SceneDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneDeleted) ProtoMessage() {}

func (x *SceneDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pb_scene_scene_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneDeleted.ProtoReflect.Descriptor instead.
func (*SceneDeleted) Descriptor() ([]byte, []int) {
	return file_pb_scene_scene_proto_rawDescGZIP(), []int{10}
}

func (x *SceneDeleted) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SceneDeleted) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

var File_pb_scene_scene_proto protoreflect.FileDescriptor

const file_pb_scene_scene_proto_rawDesc = "" +
	"\n" +
	"\x14pb/scene/scene.proto\x12\x05scene\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xeb\x03\n" +
	"\x05Scene\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x122\n" +
	"\x15background_image_path\x18\x06 \x01(\tR\x13backgroundImagePath\x129\n" +
	"\n" +
	"is_visible\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\tisVisible\x12)\n" +
	"\x10background_color\x18\b \x01(\tR\x0fbackgroundColor\x12,\n" +
	"\x12grid_cell_distance\x18\t \x01(\x04R\x10gridCellDistance\x12,\n" +
	"\tgrid_type\x18\n" +
	" \x01(\x0e2\x0f.scene.GridTypeR\bgridType\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\x12CreateSceneRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05width\x18\x03 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\rR\x06height\x122\n" +
	"\x15background_image_path\x18\x05 \x01(\tR\x13backgroundImagePath\x12)\n" +
	"\x10background_color\x18\x06 \x01(\tR\x0fbackgroundColor\x12,\n" +
	"\x12grid_cell_distance\x18\a \x01(\x04R\x10gridCellDistance\x12,\n" +
	"\tgrid_type\x18\b \x01(\x0e2\x0f.scene.GridTypeR\bgridType\"9\n" +
	"\x13CreateSceneResponse\x12\"\n" +
	"\x05scene\x18\x01 \x01(\v2\f.scene.SceneR\x05scene\"f\n" +
	"\x10EditSceneRequest\x12\"\n" +
	"\x05scene\x18\x01 \x01(\v2\f.scene.SceneR\x05scene\x12.\n" +
	"\x04mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"7\n" +
	"\x11EditSceneResponse\x12\"\n" +
	"\x05scene\x18\x01 \x01(\v2\f.scene.SceneR\x05scene\"J\n" +
	"\x12DeleteSceneRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\"m\n" +
	"\x14ListAllScenesRequest\x12\x19\n" +
	"\btable_id\x18\x01 \x01(\x04R\atableId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"e\n" +
	"\x15ListAllScenesResponse\x12$\n" +
	"\x06scenes\x18\x01 \x03(\v2\f.scene.SceneR\x06scenes\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\fSceneCreated\x12\"\n" +
	"\x05scene\x18\x01 \x01(\v2\f.scene.SceneR\x05scene\"2\n" +
	"\fSceneUpdated\x12\"\n" +
	"\x05scene\x18\x01 \x01(\v2\f.scene.SceneR\x05scene\"D\n" +
	"\fSceneDeleted\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId*#\n" +
	"\bGridType\x12\n" +
	"\n" +
	"\x06SQUARE\x10\x00\x12\v\n" +
	"\aHEXAGON\x10\x012\xaa\x02\n" +
	"\fSceneService\x12D\n" +
	"\vCreateScene\x12\x19.scene.CreateSceneRequest\x1a\x1a.scene.CreateSceneResponse\x12>\n" +
	"\tEditScene\x12\x17.scene.EditSceneRequest\x1a\x18.scene.EditSceneResponse\x12@\n" +
	"\vDeleteScene\x12\x19.scene.DeleteSceneRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x15ListAllScenesForTable\x12\x1b.scene.ListAllScenesRequest\x1a\x1c.scene.ListAllScenesResponseB<Z:github.com/GarotoCowboy/vttProject/api/grpc/pb/scene;sceneb\x06proto3"

var (
	file_pb_scene_scene_proto_rawDescOnce sync.Once
	file_pb_scene_scene_proto_rawDescData []byte
)

func file_pb_scene_scene_proto_rawDescGZIP() []byte {
	file_pb_scene_scene_proto_rawDescOnce.Do(func() {
		file_pb_scene_scene_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_scene_scene_proto_rawDesc), len(file_pb_scene_scene_proto_rawDesc)))
	})
	return file_pb_scene_scene_proto_rawDescData
}

var file_pb_scene_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_scene_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pb_scene_scene_proto_goTypes = []any{
	(GridType)(0),                 // 0: scene.GridType
	(*Scene)(nil),                 // 1: scene.Scene
	(*CreateSceneRequest)(nil),    // 2: scene.CreateSceneRequest
	(*CreateSceneResponse)(nil),   // 3: scene.CreateSceneResponse
	(*EditSceneRequest)(nil),      // 4: scene.EditSceneRequest
	(*EditSceneResponse)(nil),     // 5: scene.EditSceneResponse
	(*DeleteSceneRequest)(nil),    // 6: scene.DeleteSceneRequest
	(*ListAllScenesRequest)(nil),  // 7: scene.ListAllScenesRequest
	(*ListAllScenesResponse)(nil), // 8: scene.ListAllScenesResponse
	(*SceneCreated)(nil),          // 9: scene.SceneCreated
	(*SceneUpdated)(nil),          // 10: scene.SceneUpdated
	(*SceneDeleted)(nil),          // 11: scene.SceneDeleted
	(*wrapperspb.BoolValue)(nil),  // 12: google.protobuf.BoolValue
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 14: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 15: google.protobuf.Empty
}
var file_pb_scene_scene_proto_depIdxs = []int32{
	12, // 0: scene.Scene.is_visible:type_name -> google.protobuf.BoolValue
	0,  // 1: scene.Scene.grid_type:type_name -> scene.GridType
	13, // 2: scene.Scene.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: scene.Scene.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: scene.CreateSceneRequest.grid_type:type_name -> scene.GridType
	1,  // 5: scene.CreateSceneResponse.scene:type_name -> scene.Scene
	1,  // 6: scene.EditSceneRequest.scene:type_name -> scene.Scene
	14, // 7: scene.EditSceneRequest.mask:type_name -> google.protobuf.FieldMask
	1,  // 8: scene.EditSceneResponse.scene:type_name -> scene.Scene
	1,  // 9: scene.ListAllScenesResponse.scenes:type_name -> scene.Scene
	1,  // 10: scene.SceneCreated.scene:type_name -> scene.Scene
	1,  // 11: scene.SceneUpdated.scene:type_name -> scene.Scene
	2,  // 12: scene.SceneService.CreateScene:input_type -> scene.CreateSceneRequest
	4,  // 13: scene.SceneService.EditScene:input_type -> scene.EditSceneRequest
	6,  // 14: scene.SceneService.DeleteScene:input_type -> scene.DeleteSceneRequest
	7,  // 15: scene.SceneService.ListAllScenesForTable:input_type -> scene.ListAllScenesRequest
	3,  // 16: scene.SceneService.CreateScene:output_type -> scene.CreateSceneResponse
	5,  // 17: scene.SceneService.EditScene:output_type -> scene.EditSceneResponse
	15, // 18: scene.SceneService.DeleteScene:output_type -> google.protobuf.Empty
	8,  // 19: scene.SceneService.ListAllScenesForTable:output_type -> scene.ListAllScenesResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pb_scene_scene_proto_init() }
func file_pb_scene_scene_proto_init() {
	if File_pb_scene_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_scene_scene_proto_rawDesc), len(file_pb_scene_scene_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_scene_scene_proto_goTypes,
		DependencyIndexes: file_pb_scene_scene_proto_depIdxs,
		EnumInfos:         file_pb_scene_scene_proto_enumTypes,
		MessageInfos:      file_pb_scene_scene_proto_msgTypes,
	}.Build()
	File_pb_scene_scene_proto = out.File
	file_pb_scene_scene_proto_goTypes = nil
	file_pb_scene_scene_proto_depIdxs = nil
}
