// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: pb/scene/scene.proto

package scene

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SceneService_CreateScene_FullMethodName           = "/scene.SceneService/CreateScene"
	SceneService_EditScene_FullMethodName             = "/scene.SceneService/EditScene"
	SceneService_DeleteScene_FullMethodName           = "/scene.SceneService/DeleteScene"
	SceneService_ListAllScenesForTable_FullMethodName = "/scene.SceneService/ListAllScenesForTable"
)

// SceneServiceClient is the client API for SceneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The `SceneService` manages scenes (e.g., maps, battlemaps) within a table.
type SceneServiceClient interface {
	// Creates a new scene for a table.
	CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneResponse, error)
	// Edits the properties of an existing scene using a field mask for partial updates.
	EditScene(ctx context.Context, in *EditSceneRequest, opts ...grpc.CallOption) (*EditSceneResponse, error)
	// Deletes a scene from a table.
	DeleteScene(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Lists all scenes associated with a given table, with support for pagination.
	ListAllScenesForTable(ctx context.Context, in *ListAllScenesRequest, opts ...grpc.CallOption) (*ListAllScenesResponse, error)
}

type sceneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSceneServiceClient(cc grpc.ClientConnInterface) SceneServiceClient {
	return &sceneServiceClient{cc}
}

func (c *sceneServiceClient) CreateScene(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*CreateSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSceneResponse)
	err := c.cc.Invoke(ctx, SceneService_CreateScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneServiceClient) EditScene(ctx context.Context, in *EditSceneRequest, opts ...grpc.CallOption) (*EditSceneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditSceneResponse)
	err := c.cc.Invoke(ctx, SceneService_EditScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneServiceClient) DeleteScene(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SceneService_DeleteScene_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sceneServiceClient) ListAllScenesForTable(ctx context.Context, in *ListAllScenesRequest, opts ...grpc.CallOption) (*ListAllScenesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAllScenesResponse)
	err := c.cc.Invoke(ctx, SceneService_ListAllScenesForTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SceneServiceServer is the server API for SceneService service.
// All implementations must embed UnimplementedSceneServiceServer
// for forward compatibility.
//
// The `SceneService` manages scenes (e.g., maps, battlemaps) within a table.
type SceneServiceServer interface {
	// Creates a new scene for a table.
	CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneResponse, error)
	// Edits the properties of an existing scene using a field mask for partial updates.
	EditScene(context.Context, *EditSceneRequest) (*EditSceneResponse, error)
	// Deletes a scene from a table.
	DeleteScene(context.Context, *DeleteSceneRequest) (*emptypb.Empty, error)
	// Lists all scenes associated with a given table, with support for pagination.
	ListAllScenesForTable(context.Context, *ListAllScenesRequest) (*ListAllScenesResponse, error)
	mustEmbedUnimplementedSceneServiceServer()
}

// UnimplementedSceneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSceneServiceServer struct{}

func (UnimplementedSceneServiceServer) CreateScene(context.Context, *CreateSceneRequest) (*CreateSceneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScene not implemented")
}
func (UnimplementedSceneServiceServer) EditScene(context.Context, *EditSceneRequest) (*EditSceneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditScene not implemented")
}
func (UnimplementedSceneServiceServer) DeleteScene(context.Context, *DeleteSceneRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteScene not implemented")
}
func (UnimplementedSceneServiceServer) ListAllScenesForTable(context.Context, *ListAllScenesRequest) (*ListAllScenesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllScenesForTable not implemented")
}
func (UnimplementedSceneServiceServer) mustEmbedUnimplementedSceneServiceServer() {}
func (UnimplementedSceneServiceServer) testEmbeddedByValue()                      {}

// UnsafeSceneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SceneServiceServer will
// result in compilation errors.
type UnsafeSceneServiceServer interface {
	mustEmbedUnimplementedSceneServiceServer()
}

func RegisterSceneServiceServer(s grpc.ServiceRegistrar, srv SceneServiceServer) {
	// If the following call pancis, it indicates UnimplementedSceneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SceneService_ServiceDesc, srv)
}

func _SceneService_CreateScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneServiceServer).CreateScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneService_CreateScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneServiceServer).CreateScene(ctx, req.(*CreateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneService_EditScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneServiceServer).EditScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneService_EditScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneServiceServer).EditScene(ctx, req.(*EditSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneService_DeleteScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneServiceServer).DeleteScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneService_DeleteScene_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneServiceServer).DeleteScene(ctx, req.(*DeleteSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SceneService_ListAllScenesForTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAllScenesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SceneServiceServer).ListAllScenesForTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SceneService_ListAllScenesForTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SceneServiceServer).ListAllScenesForTable(ctx, req.(*ListAllScenesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SceneService_ServiceDesc is the grpc.ServiceDesc for SceneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SceneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scene.SceneService",
	HandlerType: (*SceneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateScene",
			Handler:    _SceneService_CreateScene_Handler,
		},
		{
			MethodName: "EditScene",
			Handler:    _SceneService_EditScene_Handler,
		},
		{
			MethodName: "DeleteScene",
			Handler:    _SceneService_DeleteScene_Handler,
		},
		{
			MethodName: "ListAllScenesForTable",
			Handler:    _SceneService_ListAllScenesForTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/scene/scene.proto",
}
