package tormenta20Rules

var skillAttributeMap = map[string]Attribute{
	"Acrobatics":    Dexterity,
	"Dressage":      Charisma,
	"Athletics":     Strength,
	"Performance":   Charisma,
	"Riding":        Dexterity,
	"Knowledge":     Intelligence,
	"Healing":       Wisdom,
	"Diplomacy":     Charisma,
	"Deception":     Charisma,
	"Fortitude":     Constitution,
	"Stealth":       Dexterity,
	"Warfare":       Intelligence,
	"Initiative":    Dexterity,
	"Intimidation":  Charisma,
	"Intuition":     Wisdom,
	"Investigation": Intelligence,
	"Gambling":      Charisma,
	"Thieving":      Dexterity,
	"Fighting":      Strength,
	"Mysticism":     Intelligence,
	"Nobility":      Intelligence,
	"Craft1":        Intelligence,
	"Craft2":        Intelligence,
	"Perception":    Wisdom,
	"Piloting":      Dexterity,
	"Aiming":        Dexterity,
	"Reflexes":      Dexterity,
	"Religion":      Wisdom,
	"Survival":      Wisdom,
	"Willpower":     Wisdom,
}
