// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0--rc2
// source: pb/sync/sync.proto

package sync

import (
	bar "github.com/GarotoCowboy/vttProject/api/grpc/pb/bar"
	chat "github.com/GarotoCowboy/vttProject/api/grpc/pb/chat"
	imageLibrary "github.com/GarotoCowboy/vttProject/api/grpc/pb/imageLibrary"
	permission "github.com/GarotoCowboy/vttProject/api/grpc/pb/permission"
	placedImage "github.com/GarotoCowboy/vttProject/api/grpc/pb/placedImage"
	placedToken "github.com/GarotoCowboy/vttProject/api/grpc/pb/placedToken"
	scene "github.com/GarotoCowboy/vttProject/api/grpc/pb/scene"
	tableUser "github.com/GarotoCowboy/vttProject/api/grpc/pb/tableUser"
	token "github.com/GarotoCowboy/vttProject/api/grpc/pb/token"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The initial message sent by a client to begin a sync session.
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The specific scene the client is currently viewing. Events specific to this scene will be prioritized.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The table (or game session) the client is part of. The client will receive all table-wide events.
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// The authentication token of the user to validate the session.
	AuthToken     string `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pb_sync_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sync_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pb_sync_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SyncRequest) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *SyncRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

// A message streamed from the server to the client, containing a single state-changing event.
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the scene this event is primarily associated with, if applicable.
	SceneId uint64 `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	// The ID of the table this event belongs to.
	TableId uint64 `protobuf:"varint,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// An event payload. Only one of these fields will be set per message,
	// indicating exactly what action occurred.
	//
	// Types that are valid to be assigned to Action:
	//
	//	*SyncResponse_PlacedTokenCreated
	//	*SyncResponse_PlacedTokenUpdated
	//	*SyncResponse_PlacedTokenMoved
	//	*SyncResponse_PlacedTokenDeleted
	//	*SyncResponse_PlacedObjectAccessUpdated
	//	*SyncResponse_SceneCreated
	//	*SyncResponse_SceneUpdated
	//	*SyncResponse_SceneDeleted
	//	*SyncResponse_TokenCreated
	//	*SyncResponse_TokenDeleted
	//	*SyncResponse_TokenUpdated
	//	*SyncResponse_BarValueUpdated
	//	*SyncResponse_BarCreated
	//	*SyncResponse_BarDeleted
	//	*SyncResponse_BarUpdate
	//	*SyncResponse_ImageUploaded
	//	*SyncResponse_ImageUpdated
	//	*SyncResponse_ImageDeleted
	//	*SyncResponse_LibraryObjectVisiblityUpdated
	//	*SyncResponse_MessageSended
	//	*SyncResponse_MessageUpdated
	//	*SyncResponse_MessageDeleted
	//	*SyncResponse_UserPromotedDemoted
	//	*SyncResponse_PlacedImageCreated
	//	*SyncResponse_PlacedImageUpdated
	//	*SyncResponse_PlacedImageMoved
	//	*SyncResponse_PlacedImageDeleted
	Action        isSyncResponse_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pb_sync_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_sync_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pb_sync_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetSceneId() uint64 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *SyncResponse) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *SyncResponse) GetAction() isSyncResponse_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *SyncResponse) GetPlacedTokenCreated() *placedToken.PlacedTokenCreated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedTokenCreated); ok {
			return x.PlacedTokenCreated
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedTokenUpdated() *placedToken.PlacedTokenUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedTokenUpdated); ok {
			return x.PlacedTokenUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedTokenMoved() *placedToken.PlacedTokenMoved {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedTokenMoved); ok {
			return x.PlacedTokenMoved
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedTokenDeleted() *placedToken.PlacedTokenDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedTokenDeleted); ok {
			return x.PlacedTokenDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedObjectAccessUpdated() *permission.PlacedObjectAccessUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedObjectAccessUpdated); ok {
			return x.PlacedObjectAccessUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetSceneCreated() *scene.SceneCreated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_SceneCreated); ok {
			return x.SceneCreated
		}
	}
	return nil
}

func (x *SyncResponse) GetSceneUpdated() *scene.SceneUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_SceneUpdated); ok {
			return x.SceneUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetSceneDeleted() *scene.SceneDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_SceneDeleted); ok {
			return x.SceneDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetTokenCreated() *token.TokenCreated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_TokenCreated); ok {
			return x.TokenCreated
		}
	}
	return nil
}

func (x *SyncResponse) GetTokenDeleted() *token.TokenDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_TokenDeleted); ok {
			return x.TokenDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetTokenUpdated() *token.TokenUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_TokenUpdated); ok {
			return x.TokenUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetBarValueUpdated() *bar.BarValuesUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_BarValueUpdated); ok {
			return x.BarValueUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetBarCreated() *bar.BarCreated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_BarCreated); ok {
			return x.BarCreated
		}
	}
	return nil
}

func (x *SyncResponse) GetBarDeleted() *bar.BarDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_BarDeleted); ok {
			return x.BarDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetBarUpdate() *bar.BarUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_BarUpdate); ok {
			return x.BarUpdate
		}
	}
	return nil
}

func (x *SyncResponse) GetImageUploaded() *imageLibrary.ImageUploaded {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_ImageUploaded); ok {
			return x.ImageUploaded
		}
	}
	return nil
}

func (x *SyncResponse) GetImageUpdated() *imageLibrary.ImageUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_ImageUpdated); ok {
			return x.ImageUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetImageDeleted() *imageLibrary.ImageDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_ImageDeleted); ok {
			return x.ImageDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetLibraryObjectVisiblityUpdated() *permission.LibraryObjectVisibilityUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_LibraryObjectVisiblityUpdated); ok {
			return x.LibraryObjectVisiblityUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetMessageSended() *chat.ChatMessageSent {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_MessageSended); ok {
			return x.MessageSended
		}
	}
	return nil
}

func (x *SyncResponse) GetMessageUpdated() *chat.ChatMessageUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_MessageUpdated); ok {
			return x.MessageUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetMessageDeleted() *chat.ChatMessageDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

func (x *SyncResponse) GetUserPromotedDemoted() *tableUser.PromotedOrDemotedUserEvent {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_UserPromotedDemoted); ok {
			return x.UserPromotedDemoted
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedImageCreated() *placedImage.PlacedImageCreated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedImageCreated); ok {
			return x.PlacedImageCreated
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedImageUpdated() *placedImage.PlacedImageUpdated {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedImageUpdated); ok {
			return x.PlacedImageUpdated
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedImageMoved() *placedImage.PlacedImageMoved {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedImageMoved); ok {
			return x.PlacedImageMoved
		}
	}
	return nil
}

func (x *SyncResponse) GetPlacedImageDeleted() *placedImage.PlacedImageDeleted {
	if x != nil {
		if x, ok := x.Action.(*SyncResponse_PlacedImageDeleted); ok {
			return x.PlacedImageDeleted
		}
	}
	return nil
}

type isSyncResponse_Action interface {
	isSyncResponse_Action()
}

type SyncResponse_PlacedTokenCreated struct {
	// PlacedToken Events
	PlacedTokenCreated *placedToken.PlacedTokenCreated `protobuf:"bytes,3,opt,name=placed_token_created,json=placedTokenCreated,proto3,oneof"`
}

type SyncResponse_PlacedTokenUpdated struct {
	PlacedTokenUpdated *placedToken.PlacedTokenUpdated `protobuf:"bytes,4,opt,name=placed_token_updated,json=placedTokenUpdated,proto3,oneof"`
}

type SyncResponse_PlacedTokenMoved struct {
	PlacedTokenMoved *placedToken.PlacedTokenMoved `protobuf:"bytes,5,opt,name=placed_token_moved,json=placedTokenMoved,proto3,oneof"`
}

type SyncResponse_PlacedTokenDeleted struct {
	PlacedTokenDeleted *placedToken.PlacedTokenDeleted `protobuf:"bytes,6,opt,name=placed_token_deleted,json=placedTokenDeleted,proto3,oneof"`
}

type SyncResponse_PlacedObjectAccessUpdated struct {
	// Permission Events for Placed Objects
	PlacedObjectAccessUpdated *permission.PlacedObjectAccessUpdated `protobuf:"bytes,7,opt,name=placed_object_access_updated,json=placedObjectAccessUpdated,proto3,oneof"`
}

type SyncResponse_SceneCreated struct {
	// Scene Events
	SceneCreated *scene.SceneCreated `protobuf:"bytes,9,opt,name=scene_created,json=sceneCreated,proto3,oneof"`
}

type SyncResponse_SceneUpdated struct {
	SceneUpdated *scene.SceneUpdated `protobuf:"bytes,8,opt,name=scene_updated,json=sceneUpdated,proto3,oneof"`
}

type SyncResponse_SceneDeleted struct {
	SceneDeleted *scene.SceneDeleted `protobuf:"bytes,10,opt,name=scene_deleted,json=sceneDeleted,proto3,oneof"`
}

type SyncResponse_TokenCreated struct {
	// Token Library Events
	TokenCreated *token.TokenCreated `protobuf:"bytes,11,opt,name=token_created,json=tokenCreated,proto3,oneof"`
}

type SyncResponse_TokenDeleted struct {
	TokenDeleted *token.TokenDeleted `protobuf:"bytes,12,opt,name=token_deleted,json=tokenDeleted,proto3,oneof"`
}

type SyncResponse_TokenUpdated struct {
	TokenUpdated *token.TokenUpdated `protobuf:"bytes,13,opt,name=token_updated,json=tokenUpdated,proto3,oneof"`
}

type SyncResponse_BarValueUpdated struct {
	// Bar Events (for tokens)
	BarValueUpdated *bar.BarValuesUpdated `protobuf:"bytes,14,opt,name=bar_value_updated,json=barValueUpdated,proto3,oneof"`
}

type SyncResponse_BarCreated struct {
	BarCreated *bar.BarCreated `protobuf:"bytes,15,opt,name=bar_created,json=barCreated,proto3,oneof"`
}

type SyncResponse_BarDeleted struct {
	BarDeleted *bar.BarDeleted `protobuf:"bytes,16,opt,name=bar_deleted,json=barDeleted,proto3,oneof"`
}

type SyncResponse_BarUpdate struct {
	BarUpdate *bar.BarUpdated `protobuf:"bytes,17,opt,name=bar_update,json=barUpdate,proto3,oneof"`
}

type SyncResponse_ImageUploaded struct {
	// Image Library Events
	ImageUploaded *imageLibrary.ImageUploaded `protobuf:"bytes,18,opt,name=image_uploaded,json=imageUploaded,proto3,oneof"`
}

type SyncResponse_ImageUpdated struct {
	ImageUpdated *imageLibrary.ImageUpdated `protobuf:"bytes,19,opt,name=image_updated,json=imageUpdated,proto3,oneof"`
}

type SyncResponse_ImageDeleted struct {
	ImageDeleted *imageLibrary.ImageDeleted `protobuf:"bytes,20,opt,name=image_deleted,json=imageDeleted,proto3,oneof"`
}

type SyncResponse_LibraryObjectVisiblityUpdated struct {
	// Permission Events for Library Objects
	LibraryObjectVisiblityUpdated *permission.LibraryObjectVisibilityUpdated `protobuf:"bytes,21,opt,name=library_object_visiblity_updated,json=libraryObjectVisiblityUpdated,proto3,oneof"`
}

type SyncResponse_MessageSended struct {
	// Chat Events
	MessageSended *chat.ChatMessageSent `protobuf:"bytes,22,opt,name=message_sended,json=messageSended,proto3,oneof"`
}

type SyncResponse_MessageUpdated struct {
	MessageUpdated *chat.ChatMessageUpdated `protobuf:"bytes,23,opt,name=message_updated,json=messageUpdated,proto3,oneof"`
}

type SyncResponse_MessageDeleted struct {
	MessageDeleted *chat.ChatMessageDeleted `protobuf:"bytes,24,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type SyncResponse_UserPromotedDemoted struct {
	// tableUser events
	UserPromotedDemoted *tableUser.PromotedOrDemotedUserEvent `protobuf:"bytes,25,opt,name=user_promoted_demoted,json=userPromotedDemoted,proto3,oneof"`
}

type SyncResponse_PlacedImageCreated struct {
	// placedImage events
	PlacedImageCreated *placedImage.PlacedImageCreated `protobuf:"bytes,26,opt,name=placed_image_created,json=placedImageCreated,proto3,oneof"`
}

type SyncResponse_PlacedImageUpdated struct {
	PlacedImageUpdated *placedImage.PlacedImageUpdated `protobuf:"bytes,27,opt,name=placed_image_updated,json=placedImageUpdated,proto3,oneof"`
}

type SyncResponse_PlacedImageMoved struct {
	PlacedImageMoved *placedImage.PlacedImageMoved `protobuf:"bytes,28,opt,name=placed_image_moved,json=placedImageMoved,proto3,oneof"`
}

type SyncResponse_PlacedImageDeleted struct {
	PlacedImageDeleted *placedImage.PlacedImageDeleted `protobuf:"bytes,29,opt,name=placed_image_deleted,json=placedImageDeleted,proto3,oneof"`
}

func (*SyncResponse_PlacedTokenCreated) isSyncResponse_Action() {}

func (*SyncResponse_PlacedTokenUpdated) isSyncResponse_Action() {}

func (*SyncResponse_PlacedTokenMoved) isSyncResponse_Action() {}

func (*SyncResponse_PlacedTokenDeleted) isSyncResponse_Action() {}

func (*SyncResponse_PlacedObjectAccessUpdated) isSyncResponse_Action() {}

func (*SyncResponse_SceneCreated) isSyncResponse_Action() {}

func (*SyncResponse_SceneUpdated) isSyncResponse_Action() {}

func (*SyncResponse_SceneDeleted) isSyncResponse_Action() {}

func (*SyncResponse_TokenCreated) isSyncResponse_Action() {}

func (*SyncResponse_TokenDeleted) isSyncResponse_Action() {}

func (*SyncResponse_TokenUpdated) isSyncResponse_Action() {}

func (*SyncResponse_BarValueUpdated) isSyncResponse_Action() {}

func (*SyncResponse_BarCreated) isSyncResponse_Action() {}

func (*SyncResponse_BarDeleted) isSyncResponse_Action() {}

func (*SyncResponse_BarUpdate) isSyncResponse_Action() {}

func (*SyncResponse_ImageUploaded) isSyncResponse_Action() {}

func (*SyncResponse_ImageUpdated) isSyncResponse_Action() {}

func (*SyncResponse_ImageDeleted) isSyncResponse_Action() {}

func (*SyncResponse_LibraryObjectVisiblityUpdated) isSyncResponse_Action() {}

func (*SyncResponse_MessageSended) isSyncResponse_Action() {}

func (*SyncResponse_MessageUpdated) isSyncResponse_Action() {}

func (*SyncResponse_MessageDeleted) isSyncResponse_Action() {}

func (*SyncResponse_UserPromotedDemoted) isSyncResponse_Action() {}

func (*SyncResponse_PlacedImageCreated) isSyncResponse_Action() {}

func (*SyncResponse_PlacedImageUpdated) isSyncResponse_Action() {}

func (*SyncResponse_PlacedImageMoved) isSyncResponse_Action() {}

func (*SyncResponse_PlacedImageDeleted) isSyncResponse_Action() {}

var File_pb_sync_sync_proto protoreflect.FileDescriptor

const file_pb_sync_sync_proto_rawDesc = "" +
	"\n" +
	"\x12pb/sync/sync.proto\x12\x04sync\x1a\x10pb/bar/bar.proto\x1a\x14pb/token/token.proto\x1a\x14pb/scene/scene.proto\x1a\"pb/imageLibrary/imageLibrary.proto\x1a pb/placedToken/placedToken.proto\x1a\x1epb/permission/permission.proto\x1a\x12pb/chat/chat.proto\x1a\x1cpb/tableUser/tableUser.proto\x1a pb/placedImage/placedImage.proto\"b\n" +
	"\vSyncRequest\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\"\x88\x10\n" +
	"\fSyncResponse\x12\x19\n" +
	"\bscene_id\x18\x01 \x01(\x04R\asceneId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\x04R\atableId\x12S\n" +
	"\x14placed_token_created\x18\x03 \x01(\v2\x1f.placedToken.PlacedTokenCreatedH\x00R\x12placedTokenCreated\x12S\n" +
	"\x14placed_token_updated\x18\x04 \x01(\v2\x1f.placedToken.PlacedTokenUpdatedH\x00R\x12placedTokenUpdated\x12M\n" +
	"\x12placed_token_moved\x18\x05 \x01(\v2\x1d.placedToken.PlacedTokenMovedH\x00R\x10placedTokenMoved\x12S\n" +
	"\x14placed_token_deleted\x18\x06 \x01(\v2\x1f.placedToken.PlacedTokenDeletedH\x00R\x12placedTokenDeleted\x12h\n" +
	"\x1cplaced_object_access_updated\x18\a \x01(\v2%.permission.PlacedObjectAccessUpdatedH\x00R\x19placedObjectAccessUpdated\x12:\n" +
	"\rscene_created\x18\t \x01(\v2\x13.scene.SceneCreatedH\x00R\fsceneCreated\x12:\n" +
	"\rscene_updated\x18\b \x01(\v2\x13.scene.SceneUpdatedH\x00R\fsceneUpdated\x12:\n" +
	"\rscene_deleted\x18\n" +
	" \x01(\v2\x13.scene.SceneDeletedH\x00R\fsceneDeleted\x12:\n" +
	"\rtoken_created\x18\v \x01(\v2\x13.token.TokenCreatedH\x00R\ftokenCreated\x12:\n" +
	"\rtoken_deleted\x18\f \x01(\v2\x13.token.TokenDeletedH\x00R\ftokenDeleted\x12:\n" +
	"\rtoken_updated\x18\r \x01(\v2\x13.token.TokenUpdatedH\x00R\ftokenUpdated\x12C\n" +
	"\x11bar_value_updated\x18\x0e \x01(\v2\x15.bar.BarValuesUpdatedH\x00R\x0fbarValueUpdated\x122\n" +
	"\vbar_created\x18\x0f \x01(\v2\x0f.bar.BarCreatedH\x00R\n" +
	"barCreated\x122\n" +
	"\vbar_deleted\x18\x10 \x01(\v2\x0f.bar.BarDeletedH\x00R\n" +
	"barDeleted\x120\n" +
	"\n" +
	"bar_update\x18\x11 \x01(\v2\x0f.bar.BarUpdatedH\x00R\tbarUpdate\x12E\n" +
	"\x0eimage_uploaded\x18\x12 \x01(\v2\x1c.image_library.ImageUploadedH\x00R\rimageUploaded\x12B\n" +
	"\rimage_updated\x18\x13 \x01(\v2\x1b.image_library.ImageUpdatedH\x00R\fimageUpdated\x12B\n" +
	"\rimage_deleted\x18\x14 \x01(\v2\x1b.image_library.ImageDeletedH\x00R\fimageDeleted\x12u\n" +
	" library_object_visiblity_updated\x18\x15 \x01(\v2*.permission.LibraryObjectVisibilityUpdatedH\x00R\x1dlibraryObjectVisiblityUpdated\x12>\n" +
	"\x0emessage_sended\x18\x16 \x01(\v2\x15.chat.ChatMessageSentH\x00R\rmessageSended\x12C\n" +
	"\x0fmessage_updated\x18\x17 \x01(\v2\x18.chat.ChatMessageUpdatedH\x00R\x0emessageUpdated\x12C\n" +
	"\x0fmessage_deleted\x18\x18 \x01(\v2\x18.chat.ChatMessageDeletedH\x00R\x0emessageDeleted\x12[\n" +
	"\x15user_promoted_demoted\x18\x19 \x01(\v2%.tableUser.PromotedOrDemotedUserEventH\x00R\x13userPromotedDemoted\x12S\n" +
	"\x14placed_image_created\x18\x1a \x01(\v2\x1f.placedImage.PlacedImageCreatedH\x00R\x12placedImageCreated\x12S\n" +
	"\x14placed_image_updated\x18\x1b \x01(\v2\x1f.placedImage.PlacedImageUpdatedH\x00R\x12placedImageUpdated\x12M\n" +
	"\x12placed_image_moved\x18\x1c \x01(\v2\x1d.placedImage.PlacedImageMovedH\x00R\x10placedImageMoved\x12S\n" +
	"\x14placed_image_deleted\x18\x1d \x01(\v2\x1f.placedImage.PlacedImageDeletedH\x00R\x12placedImageDeletedB\b\n" +
	"\x06action2@\n" +
	"\vSyncService\x121\n" +
	"\x04Sync\x12\x11.sync.SyncRequest\x1a\x12.sync.SyncResponse(\x010\x01B:Z8github.com/GarotoCowboy/vttProject/api/grpc/pb/sync;syncb\x06proto3"

var (
	file_pb_sync_sync_proto_rawDescOnce sync.Once
	file_pb_sync_sync_proto_rawDescData []byte
)

func file_pb_sync_sync_proto_rawDescGZIP() []byte {
	file_pb_sync_sync_proto_rawDescOnce.Do(func() {
		file_pb_sync_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_sync_sync_proto_rawDesc), len(file_pb_sync_sync_proto_rawDesc)))
	})
	return file_pb_sync_sync_proto_rawDescData
}

var file_pb_sync_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_sync_sync_proto_goTypes = []any{
	(*SyncRequest)(nil),                               // 0: sync.SyncRequest
	(*SyncResponse)(nil),                              // 1: sync.SyncResponse
	(*placedToken.PlacedTokenCreated)(nil),            // 2: placedToken.PlacedTokenCreated
	(*placedToken.PlacedTokenUpdated)(nil),            // 3: placedToken.PlacedTokenUpdated
	(*placedToken.PlacedTokenMoved)(nil),              // 4: placedToken.PlacedTokenMoved
	(*placedToken.PlacedTokenDeleted)(nil),            // 5: placedToken.PlacedTokenDeleted
	(*permission.PlacedObjectAccessUpdated)(nil),      // 6: permission.PlacedObjectAccessUpdated
	(*scene.SceneCreated)(nil),                        // 7: scene.SceneCreated
	(*scene.SceneUpdated)(nil),                        // 8: scene.SceneUpdated
	(*scene.SceneDeleted)(nil),                        // 9: scene.SceneDeleted
	(*token.TokenCreated)(nil),                        // 10: token.TokenCreated
	(*token.TokenDeleted)(nil),                        // 11: token.TokenDeleted
	(*token.TokenUpdated)(nil),                        // 12: token.TokenUpdated
	(*bar.BarValuesUpdated)(nil),                      // 13: bar.BarValuesUpdated
	(*bar.BarCreated)(nil),                            // 14: bar.BarCreated
	(*bar.BarDeleted)(nil),                            // 15: bar.BarDeleted
	(*bar.BarUpdated)(nil),                            // 16: bar.BarUpdated
	(*imageLibrary.ImageUploaded)(nil),                // 17: image_library.ImageUploaded
	(*imageLibrary.ImageUpdated)(nil),                 // 18: image_library.ImageUpdated
	(*imageLibrary.ImageDeleted)(nil),                 // 19: image_library.ImageDeleted
	(*permission.LibraryObjectVisibilityUpdated)(nil), // 20: permission.LibraryObjectVisibilityUpdated
	(*chat.ChatMessageSent)(nil),                      // 21: chat.ChatMessageSent
	(*chat.ChatMessageUpdated)(nil),                   // 22: chat.ChatMessageUpdated
	(*chat.ChatMessageDeleted)(nil),                   // 23: chat.ChatMessageDeleted
	(*tableUser.PromotedOrDemotedUserEvent)(nil),      // 24: tableUser.PromotedOrDemotedUserEvent
	(*placedImage.PlacedImageCreated)(nil),            // 25: placedImage.PlacedImageCreated
	(*placedImage.PlacedImageUpdated)(nil),            // 26: placedImage.PlacedImageUpdated
	(*placedImage.PlacedImageMoved)(nil),              // 27: placedImage.PlacedImageMoved
	(*placedImage.PlacedImageDeleted)(nil),            // 28: placedImage.PlacedImageDeleted
}
var file_pb_sync_sync_proto_depIdxs = []int32{
	2,  // 0: sync.SyncResponse.placed_token_created:type_name -> placedToken.PlacedTokenCreated
	3,  // 1: sync.SyncResponse.placed_token_updated:type_name -> placedToken.PlacedTokenUpdated
	4,  // 2: sync.SyncResponse.placed_token_moved:type_name -> placedToken.PlacedTokenMoved
	5,  // 3: sync.SyncResponse.placed_token_deleted:type_name -> placedToken.PlacedTokenDeleted
	6,  // 4: sync.SyncResponse.placed_object_access_updated:type_name -> permission.PlacedObjectAccessUpdated
	7,  // 5: sync.SyncResponse.scene_created:type_name -> scene.SceneCreated
	8,  // 6: sync.SyncResponse.scene_updated:type_name -> scene.SceneUpdated
	9,  // 7: sync.SyncResponse.scene_deleted:type_name -> scene.SceneDeleted
	10, // 8: sync.SyncResponse.token_created:type_name -> token.TokenCreated
	11, // 9: sync.SyncResponse.token_deleted:type_name -> token.TokenDeleted
	12, // 10: sync.SyncResponse.token_updated:type_name -> token.TokenUpdated
	13, // 11: sync.SyncResponse.bar_value_updated:type_name -> bar.BarValuesUpdated
	14, // 12: sync.SyncResponse.bar_created:type_name -> bar.BarCreated
	15, // 13: sync.SyncResponse.bar_deleted:type_name -> bar.BarDeleted
	16, // 14: sync.SyncResponse.bar_update:type_name -> bar.BarUpdated
	17, // 15: sync.SyncResponse.image_uploaded:type_name -> image_library.ImageUploaded
	18, // 16: sync.SyncResponse.image_updated:type_name -> image_library.ImageUpdated
	19, // 17: sync.SyncResponse.image_deleted:type_name -> image_library.ImageDeleted
	20, // 18: sync.SyncResponse.library_object_visiblity_updated:type_name -> permission.LibraryObjectVisibilityUpdated
	21, // 19: sync.SyncResponse.message_sended:type_name -> chat.ChatMessageSent
	22, // 20: sync.SyncResponse.message_updated:type_name -> chat.ChatMessageUpdated
	23, // 21: sync.SyncResponse.message_deleted:type_name -> chat.ChatMessageDeleted
	24, // 22: sync.SyncResponse.user_promoted_demoted:type_name -> tableUser.PromotedOrDemotedUserEvent
	25, // 23: sync.SyncResponse.placed_image_created:type_name -> placedImage.PlacedImageCreated
	26, // 24: sync.SyncResponse.placed_image_updated:type_name -> placedImage.PlacedImageUpdated
	27, // 25: sync.SyncResponse.placed_image_moved:type_name -> placedImage.PlacedImageMoved
	28, // 26: sync.SyncResponse.placed_image_deleted:type_name -> placedImage.PlacedImageDeleted
	0,  // 27: sync.SyncService.Sync:input_type -> sync.SyncRequest
	1,  // 28: sync.SyncService.Sync:output_type -> sync.SyncResponse
	28, // [28:29] is the sub-list for method output_type
	27, // [27:28] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_pb_sync_sync_proto_init() }
func file_pb_sync_sync_proto_init() {
	if File_pb_sync_sync_proto != nil {
		return
	}
	file_pb_sync_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*SyncResponse_PlacedTokenCreated)(nil),
		(*SyncResponse_PlacedTokenUpdated)(nil),
		(*SyncResponse_PlacedTokenMoved)(nil),
		(*SyncResponse_PlacedTokenDeleted)(nil),
		(*SyncResponse_PlacedObjectAccessUpdated)(nil),
		(*SyncResponse_SceneCreated)(nil),
		(*SyncResponse_SceneUpdated)(nil),
		(*SyncResponse_SceneDeleted)(nil),
		(*SyncResponse_TokenCreated)(nil),
		(*SyncResponse_TokenDeleted)(nil),
		(*SyncResponse_TokenUpdated)(nil),
		(*SyncResponse_BarValueUpdated)(nil),
		(*SyncResponse_BarCreated)(nil),
		(*SyncResponse_BarDeleted)(nil),
		(*SyncResponse_BarUpdate)(nil),
		(*SyncResponse_ImageUploaded)(nil),
		(*SyncResponse_ImageUpdated)(nil),
		(*SyncResponse_ImageDeleted)(nil),
		(*SyncResponse_LibraryObjectVisiblityUpdated)(nil),
		(*SyncResponse_MessageSended)(nil),
		(*SyncResponse_MessageUpdated)(nil),
		(*SyncResponse_MessageDeleted)(nil),
		(*SyncResponse_UserPromotedDemoted)(nil),
		(*SyncResponse_PlacedImageCreated)(nil),
		(*SyncResponse_PlacedImageUpdated)(nil),
		(*SyncResponse_PlacedImageMoved)(nil),
		(*SyncResponse_PlacedImageDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_sync_sync_proto_rawDesc), len(file_pb_sync_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_sync_sync_proto_goTypes,
		DependencyIndexes: file_pb_sync_sync_proto_depIdxs,
		MessageInfos:      file_pb_sync_sync_proto_msgTypes,
	}.Build()
	File_pb_sync_sync_proto = out.File
	file_pb_sync_sync_proto_goTypes = nil
	file_pb_sync_sync_proto_depIdxs = nil
}
