// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Pedro Henrique Marques",
            "email": "comercial.pedromarques@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/table": {
            "get": {
                "description": "Get a table by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Get Table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.TableResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Table by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Update table",
                "parameters": [
                    {
                        "description": "Table data",
                        "name": "tableDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tableDTO.UpdateTableRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Table Created sucessfully",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.TableResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create table",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Create table",
                "parameters": [
                    {
                        "description": "table data",
                        "name": "table",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tableDTO.CreateTableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "table Created Sucessfully",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.TableResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Table by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "Delete a Table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/table/character": {
            "post": {
                "description": "Create Character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Character"
                ],
                "summary": "Create a Character",
                "parameters": [
                    {
                        "description": "Character data",
                        "name": "character",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/characterDTO.CreateCharacterSwaggerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "characterhandler Created sucessfully",
                        "schema": {
                            "$ref": "#/definitions/characterDTO.CharacterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/characterDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/characterDTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tableUser": {
            "get": {
                "description": "Get a table tableUser by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TableUser"
                ],
                "summary": "Get TableUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Table User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.TableUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create tableUser",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TableUser"
                ],
                "summary": "Create tableUser",
                "parameters": [
                    {
                        "description": "tableUser data",
                        "name": "tableUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.CreateTableUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "tableUser Created Sucessfully",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.TableUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a TableUser by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TableUser"
                ],
                "summary": "Delete a TableUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "TableUser ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableUserDTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tables": {
            "get": {
                "description": "Get list of tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table"
                ],
                "summary": "List Tables",
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.TableResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/tableDTO.TableResponse"
                        }
                    }
                }
            }
        },
        "/tableUser": {
            "get": {
                "description": "Get a userDTO by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "$ref": "#/definitions/userDTO.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update User by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update tableUser",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "userDTO",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.UpdateUserRequest"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User Created sucessfully",
                        "schema": {
                            "$ref": "#/definitions/userDTO.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "tableUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDTO.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User Created sucessfully",
                        "schema": {
                            "$ref": "#/definitions/userDTO.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a userDTO by ID via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete a User",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid ID supplied",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User Not Found",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get list of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "List Users",
                "responses": {
                    "200": {
                        "description": "No content",
                        "schema": {
                            "$ref": "#/definitions/userDTO.UserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/userDTO.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "characterDTO.CharacterResponse": {
            "type": "object",
            "properties": {
                "character_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "player_name": {
                    "type": "string"
                },
                "sheet_data": {
                    "$ref": "#/definitions/characterDTO.T20SheetDto"
                },
                "system_key": {
                    "type": "string"
                },
                "table_user_id": {
                    "type": "integer"
                },
                "tableUser": {}
            }
        },
        "characterDTO.CreateCharacterSwaggerRequest": {
            "type": "object",
            "properties": {
                "character_name": {
                    "type": "string",
                    "example": "Guts"
                },
                "player_name": {
                    "type": "string",
                    "example": "Pedro"
                },
                "sheet_data": {
                    "description": "Aqui sim é a struct da ficha",
                    "allOf": [
                        {
                            "$ref": "#/definitions/characterDTO.T20SheetDto"
                        }
                    ]
                },
                "system_key": {
                    "type": "integer",
                    "example": 1
                },
                "table_user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "characterDTO.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "characterDTO.T20SheetDto": {
            "type": "object",
            "properties": {
                "abilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ability"
                    }
                },
                "armor": {
                    "$ref": "#/definitions/models.Armor"
                },
                "attacks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Attack"
                    }
                },
                "attributes": {
                    "$ref": "#/definitions/models.Attributes"
                },
                "characterID": {
                    "type": "integer"
                },
                "character_info": {
                    "$ref": "#/definitions/models.CharacterInfo"
                },
                "class_and_level": {
                    "$ref": "#/definitions/models.ClassAndLevel"
                },
                "equipment_items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.EquipmentItem"
                    }
                },
                "hp_points": {
                    "$ref": "#/definitions/models.HpPoints"
                },
                "mana_points": {
                    "$ref": "#/definitions/models.ManaPoints"
                },
                "skills": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.Skill"
                    }
                }
            }
        },
        "models.Ability": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Armor": {
            "type": "object",
            "properties": {
                "armorBonus": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "dexterityBonus": {
                    "type": "boolean"
                },
                "otherBonus": {
                    "type": "integer"
                },
                "shieldBonus": {
                    "type": "integer"
                }
            }
        },
        "models.Attack": {
            "type": "object",
            "properties": {
                "critical": {
                    "type": "string"
                },
                "damage": {
                    "type": "string"
                },
                "damageType": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "range": {
                    "type": "string"
                },
                "test": {
                    "type": "string"
                }
            }
        },
        "models.Attributes": {
            "type": "object",
            "properties": {
                "charisma": {
                    "type": "integer"
                },
                "constitution": {
                    "type": "integer"
                },
                "dexterity": {
                    "type": "integer"
                },
                "intelligence": {
                    "type": "integer"
                },
                "strength": {
                    "type": "integer"
                },
                "wisdom": {
                    "type": "integer"
                }
            }
        },
        "models.CharacterInfo": {
            "type": "object",
            "properties": {
                "deity": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "race": {
                    "type": "string"
                }
            }
        },
        "models.ClassAndLevel": {
            "type": "object",
            "properties": {
                "class": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                }
            }
        },
        "models.EquipmentItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "models.HpPoints": {
            "type": "object",
            "properties": {
                "actual": {
                    "type": "integer"
                },
                "maxHp": {
                    "type": "integer"
                },
                "tempHp": {
                    "type": "integer"
                }
            }
        },
        "models.ManaPoints": {
            "type": "object",
            "properties": {
                "actual": {
                    "type": "integer"
                },
                "maxMana": {
                    "type": "integer"
                },
                "tempMana": {
                    "type": "integer"
                }
            }
        },
        "models.Skill": {
            "type": "object",
            "properties": {
                "armorPenalty": {
                    "type": "boolean"
                },
                "bonus": {
                    "type": "integer"
                },
                "currentBaseAttribute": {
                    "type": "string"
                },
                "defaultBaseAttribute": {
                    "type": "string"
                },
                "onlyTrained": {
                    "type": "boolean"
                },
                "otherBonus": {
                    "type": "integer"
                },
                "trained": {
                    "type": "boolean"
                }
            }
        },
        "tableDTO.CreateTableRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "password": {
                    "description": "InviteLink string             ` + "`" + `json:\"invite_link\"` + "`" + `",
                    "type": "string"
                }
            }
        },
        "tableDTO.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "tableDTO.TableResponse": {
            "type": "object",
            "properties": {
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "invite_link": {
                    "type": "string"
                },
                "owner": {},
                "owner_id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "tableDTO.UpdateTableRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "tableUserDTO.CreateTableUserRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "integer"
                },
                "table_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "tableUserDTO.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "tableUserDTO.TableUserResponse": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "role": {
                    "description": "Role represents a function that tableUser will be in the table\nEnum: 1,2\n1 to Player, 2 to GameMaster",
                    "type": "integer"
                },
                "table": {},
                "table_id": {
                    "type": "integer"
                },
                "tableUser": {},
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "userDTO.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "imagelink": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "userDTO.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "userDTO.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "imagelink": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "userDTO.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageLink": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "VTT API",
	Description:      "The VTT API for managing a VTT.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
